= Archiving and Discovery
:toc:

Zimbra Archiving and Discovery is an optional feature that archives messages, delivered to or sent by {product-name}, and
searches across mailboxes.

Configuration of archiving options is on a per account basis. Each account enabled for archiving requires a {product-family} archive license. After enabling this feature, the mailbox receives a copy of all emails from or to that account. The archiving process is transparent to account users.

Discovery allows you to conduct a search for email messages across live and archived mailboxes and copy the results to a specified mailbox.

== How Archiving Works

When a message is sent or received by a user, the message routes
through the Postfix MTA. The Postfix MTA allows integrated software to
perform actions on messages in flight. When enabled, Zimbra Archiving integrates with an MTA hook and the Amavisd-New utility to fork a copy of the message.

The *does recipient or sender have archiving enabled* check is performed on the SMTP standard envelope and not on the From or To/Cc headers. Since this feature checks the envelopes, it makes copies of *Bcc* and messages sent to other distribution lists for archiving.

.Sending messages with archiving enabled
====
For example, if User A sends a message to User B, and if User B's archiving feature is enabled, the MTA delivers two messages — one to User B’s mailbox and one to User B’s archive mailbox. The message received in User B’s mailbox looks normal, as shown in the following example:

----
Received: from localhost (localhost.localdomain [127.0.0.1])…
From: userA@example.com
To:userB@example.com
Subject: New License Key
Message-ID: <015f01c717fe$70f042d1$b1d6f61d@thom>
Date: Mon, 04 Nov 2008 23:48:18 -0000

Hi B,

Can you send me the license key for the software again?

Thanks, A
----

The message received in User B’s archive mailbox contains additional
*X-Envelope-From* and *X-Envelope-To* headers. These headers show the
real email address who sent the message and each of the email
addresses that received the message.

----
Received: from localhost (localhost.localdomain [127.0.0.1])…
From: userA@example.com
To:userB@example.com
Subject: New License Key
Message-ID: <015f01c717fe$70f042d1$b1d6f61d@thom>
X-Envelope-From: userA@example.com
X-Envelope-To: userB@example.com
Date: Mon, 04 Nov 2008 23:48:18 -0000

Hi B,

Can you send me the license key for the software again?

Thanks, A
----
====

Zimbra archiving can be set up to create archiving accounts that are
maintainable within {product-name} or work with third-party archiving systems using SMTP forwarding to send messages to a third-party archive server. For third-party archiving, {product-name} is
configured to act as the forwarding agent.

== How Discovery Works

The discovery feature of Archiving and Discovery is used to search across
live^*^ and archive mailboxes for email messages and attachments.  You can run the discovery tool from the Administration Console and use it to copy the results to a target mailbox that you specify.

^*^ A live mailbox is an account on the system apart from archive accounts and system accounts.

You can search outgoing and incoming emails by date, from, to, cc, subject,
keywords, and attachments. You can also create queries to search by name, dates and time ranges, distribution list, and aliases.

Target mailbox saves the search results. You can organize your search
results by creating different target mailboxes or by creating individual
folders within a target mailbox for each search you run. Each message header copied to the target mailbox carries *X-zimbra-Source*
header information. This header label includes the account ID, the account
name, and the server where the account resides.

You can see the results of the search by logging on to the target mailbox
address.

== Installing the Archiving Package

You can install the archiving package on an existing single-server
deployment or on a multi-server deployment.

If the mailbox server and the MTA server reside on the same node, you
configure and enable archiving as a single process. If your mailbox and MTA servers are on separate nodes, the zimbra-archive package is installed
first on at least one mailbox server, and then the archiving component is
enabled on each MTA in the deployment.

=== Installing zimbra-archiving in a Single-Server Environment

The following scenario assumes that the LDAP, MTA, mailstore, and archiving servers are on the same node.

. Refer to the {product-name} Single Server Installation Guide to
open an SSH connection to the {product-name} server. Log on to the
server as *root* and run the command `./install.sh` to begin the upgrade
process.

. Accept the license agreement and type *Yes* to run the upgrade.

. Type *Yes* for zimbra-archiving when presented with the packages to be
installed.

The upgrade process begins and installs the archiving package. At
this point, the Discovery feature is installed and ready to use.

To enable archiving, switch user to *zimbra* and enable archiving on the
MTA server.
[source,bash]
----
zmprov ms <zmhostname> +zimbraServiceEnabled archiving
----

Restart the server.
[source,bash]
----
zmcontrol restart
----

=== Installing zimbra-archiving in a Multi-Server Environment

The following upgrade scenario is adding a new server assigned as
an archiving server to your {product-name} environment.

Before beginning the install process, record the following information.
You need this information when you install the archiving server. Run the
`zmlocalconfig -s` command to find the information.

----
LDAP Admin Password _____________________
LDAP Hostname       _____________________
LDAP Port           _____________________
----

Refer to the Multiple-Server Installation chapter in the {product-name}
Multi-Server Installation guide for detailed steps on installing the
packages.

. Open an SSH connection to the mailbox server configured for
archiving. Log on to the server as *root* and unpack the Zimbra
software. Run the command `./install.sh` to begin the install process.

. Type *y* and press *Enter* to install the following packages:
+
* `zimbra-store`
* `zimbra-archiving`
+
The installation process installs the `zimbra-core` package by default.

. Type *y* and press *Enter* to modify the system.

. The Main menu displays the default entries for the Zimbra component you
are installing. To expand the menu, type *x* and press *Enter*.

. Select the *Common Configuration* menu and configure the LDAP Hostname,
LDAP password, and LDAP port.

. Select the *zimbra-store* menu and configure the Admin password and the
License file location.

Complete the installation process following the steps in the Multi-server
Installation guide, under Installing Zimbra Mailbox Server.

At this point, the Discovery feature is installed and ready to use.

== Manage Archiving From the Administration Console

After installing the Archiving feature, you can set up archiving and manage it from the Administration Console.

=== Enable Archiving

Admin Console: ::
*Home > Configure > Global Settings > MTA*,
from *Archiving Configuration* check *Enable archiving*

Restart {product-abbrev} from the command line
[source,bash]
----
zmcontrol restart
----

=== Creating a Dedicated Archive COS

You can configure attributes in the COS to set mailbox features, quotas, and passwords, turn off spam and virus checks, and hide the archive
accounts from GAL.

Admin Console: ::
*Home > Configure > Class of Service*, from the *Gear* icon select *New*

. Change *Features* and *Preferences* as required for an Archiving COS.

. If you have a dedicated archiving server, in the Server Pool page, deselect
the archiving server from the list. In a multi-server deployment with a
dedicated archive server, the server should be removed from the COS server pool to prevent the re-assignment of the archive server to new accounts.
+
NOTE:
Do not perform these steps to remove the server from the server pool in a
single-server deployment. Creating a dedicated archiving COS is a good idea as this makes it easy to create archive mailboxes with the same configuration options.
+
. Modify the options on the *Advanced* page if required.

. In the *Archiving* page, check the *Enable archiving* box to make this an archiving COS.

. If you want to change the format for the naming scheme for archive
accounts, modify the two template fields. See the
<<setting_up_an_archive_account_name,Setting Up an Archive Account Name>>
section for more information.

. Click *Finish*.

[[setting_up_an_archive_account_name]]
=== Setting Up an Archive Account Name

Use attributes to create and manage the naming scheme for archive
accounts. You can set up these attributes either by COS or by account.  For
COS, these attributes can be changed from the Administration Console, COS, or individual account’s Archiving page.

* *Account date template* sets the date format used in the name
template. The default is `yyyyMMdd`. Adding the date to the account name makes it easier to roll off older data from the system to backups.

* *Account name template* sets up the format of the archive mailbox name. The default value is `${USER} ${DATE}@${DOMAIN}.archive`.

The archive account address would be similar to the following example:

`user-20070510@example.com.archive`

If you change the default value, you must use syntax that creates a valid
email address. 

NOTE:
Adding `.archive` at the end of each email account creates archive mailboxes in a non-routable domain and prevents spoofing of the archives.

When the template based on the `zimbraArchiveAccountDateTemplate` attribute is set up, `amavisArchiveQuarantineAccount` is updated to the new template name after running `zmconfigarchive`.

==== Administering the archive server

The `amavisd-new` server process controls account archiving as well as
antivirus and anti-spam processes. The `zmarchivectl` command can be used to start, stop, restart, or obtain the status of the `amavisd-new` server process that controls account archiving. Exercise caution when starting or stopping the archiving process as it is a shared server process between archiving, antivirus, and anti-spam processes. Taking action on any of them affects other enabled services in your deployment.

If you want to disable archiving and not the antivirus, or anti-spam services, disable the respective service either through the CLI or through the Administration Console.

=== Set Up Archiving for a Users Mailbox
Under *Home* > *Manage*, right-click a user's account and click *Edit*. Open the *Archiving* page for this account.

Four attributes manage the archive feature for accounts; two configure a mailbox, and two create the archive account names.

Of the two attributes managing the primary user’s mailbox, one attribute enables archiving, and the other shows the message archive location.

Currently archived to:: If this option is unset, archiving is not enabled. Click *Enable Archiving* on the bottom.

Archived accounts:: It contains the list of all archive addresses used by this user's account. Click an address and click *Select* to use that address as the archiving address.

== Archive Mailboxes

You can create an archive mailbox with or without an assigned COS. You can also forward emails marked for archiving to a third-party archiving server.

NOTE:
Zimbra Licensing counts each account, with archiving enabled, against the number of Zimbra licenses purchased for archiving.  Archive mailboxes appear in the Administration Console along with the live accounts. To see the current license information, go to the Administration Console: +
*Home > Configure > Global Settings > License*.

=== Creating an archive mailbox and assigning a COS

Archive accounts are created based on the Zimbra Archive name templates.

* The attribute -- `zimbraIsSystemResource` -- is added to the archive
account and set to TRUE.

* The archive account is displayed in the Administration Console.

* When a message arrives in a mailbox with archiving enabled, archiving mailbox receives a copy of
the message.

Log on as `zimbra`, and use `zmarchiveconfig` command:
[source,bash]
----
zmarchiveconfig enable <account@example.com> archive-cos <archive>
----

=== Creating an Archive Mailbox with No COS or Password

If the archive account is not assigned a COS, the following settings are
set by default.

* Mailbox quota is set to 0, unlimited quota.

* Spam and virus checks are disabled.

* Hide in GAL is enabled, so the archive account does not display in the
  GAL

Log on as `zimbra`, and use the `zmarchiveconfig` command:
[source,bash]
----
zmarchiveconfig enable <user@example.com>
----

=== Enabling Archive Forwarding to a Third-party Archiving Server

If you do not maintain the archive account within {product-name},
you do not need to set a password, COS, or other attributes.

Log on as `zimbra`, and use the `zmarchiveconfig` command:
[source,bash]
----
zmarchiveconfig enable <account@example.com> \
 archive-address account-archive@offsite.com \
 archive-create false
----

== Searching Across Mailboxes

After installing the archiving and discovery feature, you can search
across mailboxes either from the Administration Console or through the
command line interface.

NOTE:
You do not need to have any archive mailboxes configured to search across
mailboxes, however, you must install the Archiving package.

You can assign a user to run the mailbox searches from the Administration
Console by creating a delegated administrator with rights to access the
mailbox search tool.

=== Cross Mailbox Search from the Administration Console

The discovery tool, *Search Mail*, is added to *Tools and Migration* on the
Navigation pane right alongside the archiving package.
. Click *Home* > *Tools and Migration* > *Search Mail*. From the *Gear* icon select *New*.
. To set up a cross-mailbox search, configure the following information.

Search Query::
Enter a query to search the mailbox for specific emails. To understand the search grammar used for Zimbra's Search feature, please refer to <<#query_language_description, Query Language Description>> for more information.

IMPORTANT: Cross mailbox search results appear under a target mailbox. In case the target mailbox has a mail quota, cross mailbox search does not deliver messages to the target mailbox once it's full.

Search Results::
* *Server name*: Choose a server from the drop-down to search for emails.
* *Target mailbox for results*: Choose an email account (mailbox) to copy the search results.
Mail folder for results::
* *Mail folders for results*: One target mailbox and folder is present  already. You can use this mailbox for all your search results
and create new folders for each search, or you can create a new target
mailbox for each separate search.
+
A target mailbox is like any other mailbox and can have any features or
preferences that are defined by the COS or by account. Target mailboxes appear in the Administration Console Accounts list. You might want to give
the target mailboxes account names that identify them as target mailboxes
for cross-mailbox searches and configure a COS specific for target
mailboxes to be able to manage access.
+
* *Maximum number of results [use ‘0’ for unlimited]*: The default is
500 results.

* *Maximum number of results to fetch from each mailbox*: Choose a value between 1 and 10,000,000
+
NOTE: If you have set a ‘Maximum number of results’ it may trim output even when the search has more results to show.

Accounts::
You can choose to *Select all accounts* or *Select accounts to search*. When *Select accounts to search* is selected, you have to specify the mailboxes or accounts to search.
+
* Check *Show archives and system resources* to include email addresses related to spam, quarantine, and other services in your search. 

Scope:: Define the scope of the search
+
* Search Mail Archives
* Search Live Mail
* Search in Dumpster Folder (if enabled for accounts)

Notification::
You can select to send an email notification when the search completes. The email notification includes the search task ID and status on
the subject line and you can specify the type of information to include in
the message, such as the number of messages found, the list of addresses
resulting from the search and the search query used.

As the search runs, the *Search Mailbox Content* pane lists the search and the status. Click *Refresh* to update this page.

Delete the search task when it completes because it occupies server
memory. When the server restarts, it deletes past searches.

When you use the discovery feature in the Administration Console, the tool
makes copies of messages in the target mailbox you create. The messages
occupy server space, increasing the size of your server. You might want to
delete these messages from the target mailbox when they are no longer
needed.
