= IMAP
:toc:

{product-name} has a built-in IMAP server which is installed by default and is part of zimbra-mailboxd process (<<mailboxserver.adoc#zimbra_mailbox_server, Zimbra Mailbox Server>>).

== Common IMAP Configuration settings

The following global and server level configuration attributes are available to control and tune the IMAP service.

* *zimbraImapServerEnabled*. When set to TRUE, in-process IMAP server is enabled. When set to FALSE, in-process IMAP server is disabled. Default value is TRUE.
* *zimbraImapSSLServerEnabled*. When set to TRUE, in-process IMAP SSL server is enabled. When set to FALSE, in-process IMAP SSL server is disabled. Default value is TRUE
* *zimbraImapBindAddress* (can be set only on server level). Specifies interface address on which in-process IMAP server should listen; if empty, binds to all interfaces.
* *zimbraImapBindPort*. Specifies port number on which in-process IMAP server should listen. Default value is 7143.
* *zimbraImapSSLBindAddress* (can be set only on server level). Specifies interface address on which in-process IMAP SSL server should listen; if empty, binds to all interfaces.
* *zimbraImapSSLBindPort*. Specifies port number on which in-process IMAP SSL server should listen on. Default value is 7993.
* *zimbraImapNumThreads*. Specifies number of threads in IMAP handler's thread pool. {product-name} uses IMAP NIO by default, which allows each IMAP handler thread to handle multiple connections. The default value of 200 is sufficient to handle up to 10,000 active IMAP clients.
* *zimbraImapCleartextLoginEnabled*. Specifies whether or not to allow cleartext logins over a non SSL/TLS connection. Default value is FALSE.
* *zimbraImapProxyBindPort*. Specifies port number on which IMAP proxy server should listen. Default value is 143. See <<proxy.adoc#zimbra_proxy_components, Zimbra Proxy Components>> for more information.
* *zimbraImapSSLProxyBindPort*. Specifies port number on which IMAP SSL proxy server should listen. Default value is 993. See <<proxy.adoc#zimbra_proxy_components, Zimbra Proxy Components>> for more information.
 * *zimbraImapMaxRequestSize*. Specifies maximum size of IMAP request in bytes excluding literal data. *Note:* this setting does not apply to IMAP LOGIN requests. IMAP LOGIN requests are handled by IMAP Proxy (<<proxy.adoc#zimbra_proxy_components, Zimbra Proxy Components>>) and are limited to 256 characters.
 * *zimbraImapInactiveSessionCacheMaxDiskSize*. Specifies the maximum disk size of inactive IMAP cache in Bytes before eviction. By default this value is 10GB. This is a rough limit, because due to internals of Ehcache actual size on disk will often exceed this limit by a modest margin.
 * *zimbraImapInactiveSessionEhcacheSize*. Specifies the maximum heap size of the inactive session cache in Bytes before eviction. By default this value is 1 megabyte. This is a rough limit, because due to internals of Ehcache actual size in memory will often exceed this limit by a modest margin.
 * *zimbraImapActiveSessionEhcacheMaxDiskSize*. Specifies the maximum amount of disk space the imap active session cache will consume in Bytes before eviction. By default this value is 100 gigabytes. This is a rough limit, because due to internals of ehcache actual size in memory will often exceed this limit by a modest margin.
