= Introduction
include::settings.adoc[]

{product-name} is a full-featured messaging and collaboration solution that includes email, address book, calendaring, tasks, and Web document authoring.

== Audience

This guide is for system administrators responsible for installing, maintaining, and supporting the server deployment of {product-name}.

Readers of this guide should have the following recommended knowledge and skill sets:

* Familiarity with the associated technologies and standards
* Linux operating system and open source concepts
* Industry practices for mail system management

== Third-Party Components

Where possible, {product-name} adheres to existing industry standards and open source implementations for backup management, user authentication, operating platform, and database management.
However, it only supports the specific implementations described in the {product-name} architecture overview in the Product Overview chapter as officially tested and certified.
This document might occasionally note when other tools are available in the marketplace, but such mention does not constitute an endorsement or certification.

== Support and Contact Information

* Contact {product-short} Sales to purchase {product-name} {product-version}.
* {product-name} customers can contact support at **support@zimbra.com**.
* Explore the https://forums.zimbra.org/[{product-short} Forums] for answers to installation or configuration problems.
* Join the {product-short} Community Forum, to participate and learn more about {product-name}.
* Send an email to **feedback@zimbra.com** to let us know what you like about the product and what you would like to see in the product.
If you prefer, post your ideas to the {product-short} Forum.

For additional product information, the following resources are available:

* https://wiki.zimbra.com[Zimbra Wiki]
* https://wiki.zimbra.com/wiki/Security_Center[Security Center]