= Licensing
:toc:

To create accounts, you require a Zimbra license. When you
purchase, renew, or change the Zimbra license, you must update the Zimbra server
with the new license information.

== License Types

{product-name} licensing gives administrators better visibility and control
into the licensed features they plan to deploy. You can monitor usages and
manage the following license types.

[cols="25,75",options="header",grid="rows"]
|=======================================================================
| License limitations |To set maximum number of...

|Accounts limit |
It shows the number of accounts you can create and the accounts already created.

|Mobile accounts limit |
It shows the number of accounts you can create and the accounts already created for mobile devices.

|Touch client accounts limit |
Accounts that can have the touch client mobile feature enabled.

|MAPI accounts limit |
It is a count of accounts that can use Zimbra Connector for Microsoft Outlook (ZCO).

|Exchange web services (EWS) accounts limit |
Accounts that can use EWS for connecting to an Exchange server. EWS is a
separately licensed add-on.

|High-fidelity document preview |
It shows the accounts that can use the High-Fidelity document preview. The installation of LibreOffice is mandatory to use this feature.

|Archiving accounts limit |
It shows the number of accounts on which you can enable archiving and the count of accounts which already have archiving feature. The installation of the archiving feature is mandatory to use this feature.

|=======================================================================

== License Requirements

To try out {product-name}, you can obtain trial versions free of
charge. Once you set up the system in a production environment, you
need to purchase a subscription or a perpetual license.

[cols="25,75",options="header",grid="rows"]
|=======================================================================
|License Types |Purpose

|Trial |
Free of charge: Trial license from the Zimbra website (https://www.zimbra.com). The
trial license allows you to create up to 50 users. It expires in 60 days.

|Trial extended |
Free of charge: Allows you to create up to 50 users and is valid for an
extended time; obtainable from Zimbra Sales by contacting
sales@zimbra.com or calling 1-972-407-0688.

|Subscription |
Purchased: Applicable to a specific {product-name} system and encrypted
with the number of Zimbra accounts (seats) you have purchased, the
effective date, and expiration date of the subscription license

|Perpetual |
Purchased: This license is similar to a subscription license and is valid
for a specific {product-name} system, is encrypted with the number of
Zimbra accounts (seats) you have purchased, the effective date, and an expiration date of 2099-12-31. When you renew your support agreement, you do not receive a new perpetual license, but your Account records in the
systems updates with your new support end date.

|=======================================================================

== License Usage by Account Type

Below is a description of {product-name} accounts and if they
impact your license limit.

[cols="25,75",options="header",grid="rows"]
|=======================================================================
|License Account Type |Purpose

|System account |
System accounts are specific accounts used by {product-name}. They
include the spam filter accounts for junk mail (spam and ham), virus
quarantine account for email messages with viruses, and GALsync account if
you configure GAL for your domain. Do not delete these accounts! These
accounts do not count against your license.

|Administrator account |
Administrator and delegated administrator accounts count against your license

|User account |
User accounts count against your license account limit. When you delete an
account, the license account limit reflects the change.

|Alias account .3+^.^|Not applicable
|Distribution list
|Resource account

|=======================================================================

== License Activation

All network edition installations require license activation. New
installations have a 10 day grace period from the license issue date before
they require activation. You can activate your license in the Administration Console.

Admin Console: ::
*Home > Configure > Global Settings > License*, from the *Gear* icon select
*Activate License*

Upgraded {product-name} versions require an immediate activation to
maintain network feature functionality.

=== Automatic License Activation

Licenses are automatically activated if the {product-name} server has a
connection to the Internet and can communicate with the Zimbra License
server. If you are unable to activate your license automatically, see <<manual_license_activation,Manual License Activation>>.

[[manual_license_activation]]
=== Manual License Activation

For systems that do not have external access to the Zimbra License server,
you can use the https://support.zimbra.com/[Zimbra Support Portal] to activate your license manually. Go to the Zimbra website at www.zimbra.com
and click *Support* to display the Zimbra Technical Support page. Click the
*{product-name} Support* link to display the Zimbra Support Portal page.
Enter your email and password to log in.

If you have problems accessing the Zimbra Support Portal, contact Zimbra
Support at support@zimbra.com.

=== When Licenses are not Installed or Activated

If you fail to install or activate your {product-name} server license, the
following scenarios describe how your {product-name} server is
impacted.

[cols="25,75",options="header",grid="rows"]
|=======================================================================
|License Condition |Description/Impact

|Not installed |
{product-name} defaults to single user mode where all features limited by the license are limited to one user.

|Not valid |
{product-name} defaults to single user mode.

|Not activated |
A license activation grace period is 10 days. If for some reason the
license is never activated, {product-name} defaults to single user mode
after 10 days.

|For future date |
{product-name} defaults to single user mode

|In grace period |
The license ending date has passed and is within the 30 day grace
period. All features limited by the license are still enabled, but
administrators might see license renewal prompts.

| Expired |
The license ending date has passed, and the 30 day grace period has
expired. The {product-name} server defaults to the feature set of the Open
Source Edition.

|=======================================================================

== Obtain a License

On the Zimbra website, go to Downloads to obtain a trial license from the
Zimbra Downloads area. Contact Zimbra sales regarding a trial extended
the license, or to purchase a subscription license or perpetual license, by
emailing sales@zimbra.com.

You can install the subscription, and perpetual license only on the
{product-name} system you purchased. You require only one Zimbra license for your {product-name} environment. This license sets the number
of accounts you can create.

You can view the current license information, including the number of accounts purchased,
the number of accounts used, and the expiration date by navigating to 
*Home* > *Configure* > *Global Settings* > License* on the <<#_zimbra_administration_console, Admin Console>>.

== Managing Licenses

The *Update License* wizard from the Administration Console’s *Global
Settings* page is used to upload and install a new license. The *Activate
License* link on the toolbar activates the license.

Current license information, including the license ID, the issue date,
expiration date, number of accounts purchased, and the number of accounts
used can be viewed from
*Home > Configure > Global Settings > License*.

=== License Information

You must have a {product-name} license to create accounts. When you
purchase, renew, or change the Zimbra license, you must update the Zimbra
server with the new license information. The *Update License Wizard* from
the Administration Console’s Global Settings is used to upload and install
a new license. The *Activate License* link on the toolbar activates the
license.

Current license information, including the license ID, the issue date,
expiration date, number of accounts purchased, and the number of accounts
used can be viewed from
*Home > Configure > Global Settings > License*.


When the number of accounts created is equal to the number of accounts
purchased, you cannot create new accounts. You can purchase
additional accounts, or you can delete existing accounts. Contact Zimbra
sales to purchase additional accounts.

You must renew your license within 30 days of the expiration date.
Starting 30 days before the license expires, when you log on to the
Administration Console, a reminder notice is displayed.

=== License Expiration

When your {product-name} Network Edition License expires, a license
expiration warning appears in the administrative console and web interface for all users. From the date of the license expiration, there is a 30-day grace period during which you see the warning message, but no features
are disabled.

Upon the expiration of the grace period, the server reverts to the feature set of the Open Source Edition. The following is a list of some of the major
functions that are no longer available upon license expiration:

* Backup/Restore
* Zimbra Mobile (ActiveSync)
* Zimbra Touch Client
* Exchange Web Services (EWS) -- _a separately licensed add-on_
* High-Fidelity Document Preview
* Zimbra Connector for Outlook
* Zimbra Connector for Blackberry
* S/MIME

If you maximize your licensed user limit, you are no longer able to
create or delete accounts.

If you do not plan to renew your license, you can regain the ability to
create or delete accounts by upgrading to {product-name} free and open source software (FOSS). You should choose the same version of FOSS that you
are currently running on the {product-name} Network Edition for this
transition, after which you can upgrade to the latest version of
{product-name} FOSS.

=== Renewal

When the number of accounts created is equal to the number of accounts
purchased, you cannot create new accounts. You can purchase
additional accounts, or you can delete existing accounts. Contact Zimbra
sales to purchase additional accounts.

You must renew your license within 30 days of the expiration date.
Starting 30 days before the license expires, when you log on to the
Administration Console, a reminder notice is displayed.

== Updating Your License

When you renew or change the Zimbra license, you update {product-name}
mailbox servers with the new license information. You renew or change the Zimbra License from either the CLI or the Administration Console.

[source, bash]
----
zmlicense
----

Admin Console: ::
*Home > Configure > Global Settings > License*

Updating a license:

. Save the license on the computer you use to access the Administration
Console.

. Log on to the Administration Console, go to
*Home > Configure > Global Settings > License*, from the *Gear* icon select
*Update License*. The License Installation Wizard opens.

. Browse to select the license file and click *Next*. The license file is
now uploaded.

. Click *Install* to install the license file.

. Click *Activate License*. Upgraded {product-name} versions require
an immediate activation to maintain network feature functionality.

Your license information is updated automatically. Zimbra refreshes the cached account
license count on each mailbox server.
