= Licensing
:toc:

A {product-name} license is required in order to create accounts.
When you purchase, renew, or change the {product-name} license, you update the {product-short} server with the new license information.

== License Types

{product-name} licensing gives administrators visibility and control of the licensed features they plan to deploy.
You can monitor usages and manage the following license types.

[cols="25,75",options="header",grid="rows"]
|=======================================================================
| License limitations |To set maximum number of...

|Accounts limit |
Accounts you can create.

ifndef::z9[]
|Mobile accounts limit |
Accounts that can have the native mail mobile feature enabled.

|Touch Client accounts limit |
Accounts that can have the touch client mobile feature enabled.
endif::[]

|MAPI accounts limit |
Accounts that can use {product-short} Connector for Microsoft Outlook (ZCO).

|Exchange web services (EWS) accounts limit |
Accounts that can use EWS for connecting to an Exchange server.
EWS is a separately licensed add-on feature.

|High-fidelity document preview |
Accounts that can use the High-Fidelity document preview facility.
LibreOffice installation is required.

|Archiving accounts limit |
Allowed archive accounts.
The archive feature installation is required.

|=======================================================================

[[License_Requirements]]
== {product-short} License Requirements

A {product-short} license is required to create accounts in the {product-edition-commercial} of {product-name}.

ifdef::z9[]
[IMPORTANT]
A {product-short} license is required to use the {modern-client} in {product-name}'s {product-edition-commercial}.
endif::z9[]

To try out {product-name}, you can obtain trial versions free of charge.
Once you are ready to install a production environment, you need to purchase a subscription or a perpetual license.

[cols="25,75",options="header",grid="rows"]
|=======================================================================
|License Types |Description

|Trial |
You can obtain a free Trial license from the {product-provider} website, at https://www.zimbra.com.
The trial license allows you to create up to 50 users.
It expires in 60 days.

|Trial extended |
You can obtain a Trial Extended license from {product-provider} Sales by contacting sales@zimbra.com or calling 1-972-407-0688.
This license allows you to create up to 50 users and is valid for an extended period.

|Subscription |
A {product-short} Subscription license can only be obtained through purchase.
This license is valid for a specific {product-name} system, is encrypted with the number of {product-short} accounts (seats) you have purchased, the effective date, and the expiration date of the subscription license.

|Perpetual |
A {product-short} Perpetual license can only be obtained through purchase.
This license is similar to a subscription license.
It is valid for a specific {product-name} system, is encrypted with the number of {product-short} accounts (seats) you have purchased, the effective date, and an expiration date of 2099-12-31.
When you renew your support agreement, you receive no new perpetual license, but your Account record in the system gets updated with your new support end date.
|=======================================================================

== License Usage by Account Type

An account assigned to a person, including an account created for archiving, requires a mailbox license.
Distribution lists, aliases, locations, and resources do not count against the license.

Below is a description of types of {product-name} accounts and if they impact your license limit.

[cols="25,75",options="header",grid="rows"]
|=======================================================================
|License Account Type |Description

|System account |
System accounts are specific accounts used by {product-name}.
They include the spam filter accounts for junk mail (spam and ham), the virus quarantine account for email messages with viruses, and the GALsync account if you configure GAL for your domain.

*Do not delete these accounts!* These accounts do not count against your license.

|Administrator account |
Administrator and delegated administrator accounts count against your license.

|User account |
User accounts count against your license account limit.

When you delete an account, the license account limit reflects the change.

|Alias account .3+^.^|These types do not count against your license.
|Distribution list
|Resource account

|=======================================================================

== License Activation

All {product-edition-commercial} installations require license activation.
New installations have a 10 day grace period from the license issue date before requiring activation.
You can activate your license in the Administration Console.

Admin Console: ::
*Home -> Configure -> Global Settings -> License*, from the *Gear* icon select *Activate License*

You can also activate your license from the command line interface.

IMPORTANT: Upgraded {product-name} versions require an immediate activation to maintain network feature functionality.

=== Automatic License Activation

Licenses are automatically activated if the {product-name} server has a connection to the Internet and can communicate with the {product-short} License server.
If you are unable to activate your license this way, see the next section on <<Manual_License_Activation,Manual License Activation>>.

[[Manual_License_Activation]]
=== Manual License Activation

For systems that do not have external access to the {product-short} License server, you can use the {product-short} Support Portal to activate your license manually.

Go to the {product-provider} website at https://www.zimbra.com and click on *Support* to display the {product-short} Technical Support page.
Click on the *Support Portal Login* button to display the {product-short} Support Portal page.
Enter your email and password to log in.

If you have problems accessing the Support Portal, contact Zimbra Sales at sales@zimbra.com or by calling 1-972-407-0688.688.

=== When Licenses are not Installed or Activated

If you fail to install or activate your {product-name} server license, the following scenarios describe the impact on your {product-name} server.

[cols="25,75",options="header",grid="rows"]
|=======================================================================
|License Condition |Description/Impact

|Not installed |
With no installed license, the {product-name} server defaults to single user mode where all license-limited features are limited to one user.

|Not valid |
If the license file appears forged or fails validation for other reasons, the {product-name} server defaults to single-user mode.

|Not activated |
A license activation grace period is 10 days.
If this period passes without activation, the {product-name} server defaults to single-user mode.

|For future date |
If the license starting date is in the future, the {product-name} server defaults to single-user mode.

|In grace period |
If the license ending date has passed and is within the 30 day grace period, all license-limited features are still enabled, but administrators may see license renewal prompts.

| Expired |
If the license ending date has passed and the 30 day grace period expired, the {product-name} server defaults to the feature set of the {product-edition-foss}.

|=======================================================================

== Obtain a License

Go to the {product-provider} Website https://www.zimbra.com to obtain a trial license from the Network Downloads area.
Contact {product-provider} sales regarding a trial extended license, or to purchase a subscription license or perpetual license, by emailing sales@zimbra.com or calling 1-972-407-0688.

A subscription or perpetual license can only install on the {product-name} system identified during purchase.
Only one {product-short} license is required for your {product-name} environment.
This license sets the maximum number of accounts on the system.

View current license information, including the number of purchased accounts, the number of accounts used, and the expiration date, in the Admin Console.

Admin Console: ::
*Home -> Configure -> Global Settings -> License*.

== Managing Licenses

Use the *Update License* wizard on the Administration Console's *Global Settings* page to upload and install a new license.
The *Activate License* link on the toolbar activates the license.

View current license information, including the number of purchased accounts, the number of accounts used, and the expiration date, in the Admin Console.

Admin Console: ::
*Home -> Configure -> Global Settings -> License*.

=== License Information

You must have a {product-name} license to create accounts.
When you purchase, renew, or change the Zimbra license, you must update the Zimbra server with the new license information.
The *Update License Wizard* from the Administration Console's Global Settings is used to upload and install a new license.
The *Activate License* link on the toolbar activates the license.

View current license information, including the number of purchased accounts, the number of accounts used, and the expiration date, in the Admin Console.

Admin Console: ::
*Home -> Configure -> Global Settings -> License*.

=== License Expiration

When your {product-name} Network Edition License expires, a license expiration warning appears in the administrative console and web interface for all users.
From the date of the license expiration, there is a 30-day grace period during which the administrator sees the warning message, but no features are disabled.

Upon expiration of the grace period, the server reverts to the feature set of the Open Source Edition.
The following is a list of some of the major functions that are no longer available upon license expiration:

* Backup/Restore
* Exchange Web Services (EWS) -- _a separately licensed add-on_
* High-Fidelity Document Preview
* Zimbra Connector for Outlook
* S/MIME
ifdef::z9[]
* {modern-client}
endif::z9[]

ifndef::z9[]
If you do not plan to renew your license, you can regain the ability to create or delete accounts by downgrading to {product-name} free and open-source software (FOSS).
You should choose the same version of FOSS that you are currently running on the {product-name} Network Edition for this transition, after which you can upgrade to the latest version of {product-name} FOSS.
endif::z9[]

=== Renewal

If you exhaust your licensed user limit, you are no longer able to create accounts.
You can buy additional user licenses, or you can delete existing accounts.
Contact Zimbra sales to purchase additional licenses.

You must renew your license within 30 days of the expiration date.
Starting 30 days before the license expires, when you log on to the Administration Console, a reminder notice is displayed.

== Updating Your License

When you renew or change the Zimbra license, you update {product-name} mailbox servers with the new license information.
Perform this operation from either the CLI or the Administration Console.

[source, bash]
----
zmlicense
----

Admin Console: ::
*Home -> Configure -> Global Settings -> License*

Updating a license:

. Save the license on the computer you use to access the Administration Console.

. Log on to the Administration Console, go to *Home -> Configure -> Global Settings -> License*, from the *Gear* icon select *Update License*. The License Installation Wizard opens.

. Browse to select the license file and click *Next*. The license file is now uploaded.

. Click *Install* to install the license file.

. Click *Activate License*. Upgraded {product-name} versions require an immediate activation to maintain network feature functionality.

Your license information is updated automatically, and the cached account license count refreshes on each mailbox server.

== License Reconciliation and Data Collection Notice

IMPORTANT: By consenting to the End-User License Agreement, you grant Synacor Inc.
and certain of its licensees permission to collect licensing and non-personally-identifiable usage data from your {product-name} {product-edition-commercial} server.

During installation, upgrades, and periodically while in use, the {product-name} server transmits information for reconciliation of billing and license data.

Permission for this data collection is granted under sections 11.4 and 11.6 of the End User License Agreement for {product-edition-commercial}.
Copies of the license can be found at https://www.zimbra.com/legal/licensing/.

The data that is being collected consists of elements of the current license information and is governed by Synacor's Privacy Policy, which can be found at https://www.synacor.com/privacy-policy/.

This data is being furnished to Synacor's licensor, ZeXtras, for the purposes of license reconciliation and is therefore also governed by the ZeXtras Privacy Policy, which can be found at https://www.zextras.com/privacy-legal/.