[[voice_service]]
= Using the Voice Service
:toc:

Unified Communications (UC) is the integration of multiple modes of communication services, allowing users to receive communication from one service, such as voice mail, and respond using another service, such as Click-to-Call.

IMPORTANT: {only-in-classic}

Zimbra uses real-time communications services such as voice, telephony and presence to inter-operate with non-real-time services such as email and voice mail. The Zimbra Collaboration Voice Service feature includes Visual Voice Mail, Click-to-Call, and Presence (Cisco only). Zimbra Collaboration uses Cisco or Mitel servers, as a third-party voice server, or UC server, to bridge calls between Zimbra Collaboration and the {product-short} {web-client}.

*Note:* UC system administrators are responsible for configuring the UC server based on that UC server’s documentation.

You enable the voice service from the administration console. Users use the voice service feature from the Voice tab in the {web-client}.

When users sign into the voice service from their {product-short} account, they are actually logging into a UC server. After the initial user set-up, the voice service is seamless and requires no additional account configuration.

Voice service features include:

* *Visual Voice Mail:* From the Voice tab, users can easily view and listen to voice mails and view details such as caller name, time details, and length of message. Users can call back the person that left the message, forward or reply to the message by email, save or delete the message, and select how to be notified of a new voice message. Supported audio formats include WAV and MP3.
* *Click-to-Call:* The ability to make a phone call from a the {product-short} account. Users can highlight and click phone number in their email to dial, or select a contact’s phone number from their contact lists. The call is bridged from the registered physical or soft phone the user selects to use to call the recipient. Click-to-Call eliminates the use for a dial pad on a phone.
* *Click-to-Chat:* (Cisco clients only) The ability to chat with a contact using the Cisco Jabber client and {product-short}. Users must have the recipient’s IM address stored in their contact information. They can then access the recipient’s contact card and click the IM link to initiate a chat session.
* *Presence:* (Cisco clients only) The ability to display in real time the availability information about users or contacts. When using Cisco Jabber, users can manually set their presence status or it is automatically set for them. For example, when users are on a phone call their presence status is automatically set to “on a call”. Presence status is displayed as available, away, on a call, or do not disturb.

== Order of Configuration
To create voice service, follow the order of configuration as follows:

  . Access URLs, as described in Using a Third-Party Unified Communications Server.
  . Create the voice service, as described in Creating the Voice/Chat Service.
  . Enable the voice service and the voice feature, as described in Enabling the Voice/Chat Service. Enabling the voice feature allows the Voice tab to display in the {web-client}.
  . Enable the appropriate Zimlets for the vendor server you are using, as described in Enabling the Voice/Chat Zimlets.
  
== Voice Service Requirements
The following are required for {product-name} voice service:

* *Voice Service license:* A {product-name} license with the voice service feature is required. To obtain this license, see the Zimbra Collaboration Server License section for more information.
* *Unified Communications Server:* Third-Party Unified Communications server requirements for either Cisco or Mitel are listed below. URLs from the UC server are used in the configuration of the {product-name} voice service, as described in Using a Third-Party Unified Communications Server.
** *For Cisco:*
*** *Cisco Unity Connection (UC) 8.5 and above*. Cisco UC generates the Voice URL used in the voice service configuration.
*** *Cisco Unified Communications Manager (CUCM) 7.1(3):* Enable Web Dialer service for Click-to-Call functionality. Cisco CUCM generates the Call URL used in the voice service configuration.
*** *Cisco Unified Presence Server (CUPS) 8.0:* Cisco CUPS requires Presence Web Service to be enabled, and an application user must be created for viewing the presence. This is done in Cisco Communications Manager (CUCM) -> User Management. Cisco CUPS generates the Presence URL used in the voice service configuration.
*** *Cisco Jabber client provided to users for UC collaboration.*
** *For Mitel:*
*** *Mitel Unified Communicator Advanced (Mitel UCA) 5.0.23.0 release and above.* Mitel UCA generates the URLs used in the voice service configuration.
* *{product-name} Zimlets:* Voice Preferences Zimlet, Cisco Click2Call Zimlet or Mitel Click2Call Zimlet  
  
== Using a Third-Party Unified Communications Server
The {product-name} Voice Service uses a third-party Unified Communications (UC) server to bridge calls between {product-name} and the UC server. UC server domain information is added to the {product-name} administrator console as a Proxy Allowed Domain. This allows Zimlets that are used in the configuration of the voice service to send requests to the UC servers, such as for the Click-To-Call and/or Presence feature. The following URLs from the UC server are used to configure the voice service.

== Cisco URLs

* *Voice URL:* The Voice URL is the URL of the Cisco UC server. For example, `\https://xx.xx.xxx.xx`. This URL is used by the {product-name} server to fetch user’s voice mails from the Cisco UC server on behalf of users.
* *Call URL:* The Call URL is the URL of the Cisco CUCM server. For example, `\https://xx.xx.xxx.xx/webdialer/services/WebdialerSoapService70`. This URL is used by the {product-name} Cisco Click2Call Zimlet to send requests to the Cisco CUCM server to bridge calls.
* *Presence URL:* The Presence URL is the URL of the Cisco CUPS server and used to generate a session ID. For example, `\http://xx.xx.xxx.xx:8082/presence-service/users`. This URL is used by the {product-name} Email Zimlet to send fetch requests to the contact’s presence from the Cisco CUPS server.

*Note:* Provision an application user name and password using the Cisco Unified Presence Server (CUPS).

== Mitel URLs
* *Voice URL:* The Voice URL is the URL of the Mitel server. For example `\https://xx.xx.xxx.xx`. This URL is used by the {product-name} server to fetch user’s voice mails from the Mitel Voice server on behalf of users.
* *Call URL:* The Call URL is the URL of the Mitel server. For example, `\https://xx.xx.xxx.xx/webdialer/services/WebdialerSoapService70`. This URL is used by the {product-name} Mitel Click2Call Zimlet to send requests to the Mitel server to bridge calls.
* *User URL:* The User URL is the URL of the Mitel server. This URL is used by {product-name} for user identification/authentication.

== Creating the Voice/Chat Service
When creating the voice/chat service in {product-short}, you are enabling the bridge between {product-name} and a third-party UC server. You create a service for a domain, Class of Service (COS), or user.

  . In the {product-name} administrator console, go to the *Home>Configure>Voice/Chat Service* page.
  . From the gear icon menu, select *New*.
  . On the Choose Voice/Chat Vendor, select your vendor from the drop-down menu.
  . Click *OK*.
  . Add a *Display name* for the domain, COS, or user you are creating.
  . Add the URLs for the voice services you want to enable.
  . Click *OK*.

== Configure Presence (Cisco only)
If configuring Presence, you must generate a Presence Session ID.

  . Go to *Configure>Voice/Chat Service* page.
  . Select the voice service for which you want to generate a Presence Session ID.
  . Click the gear icon drop down menu and select *Generate Session ID* from the menu.
  . Enter the *Presence User Name* and *Presence Password*, which are the credentials for the presence server to authenticate the voice connection between {product-name} and the UC server. This allows {product-short} to retrieve presence information for users.
  . Click *OK*. A presence session ID is generated and displays as the *Presence Session ID*.
  
== Enabling the Voice/Chat Service
After you create the voice/chat service for a domain, COS, or user, you must enable the voice/chat service. For COS and User accounts, you also enable the voice feature which displays the Voice tab in the {web-client}.  

== Enable Voice/Chat Service on a Domain
For Voice/Chat service on a domain, enable the service on the Domains>General Information page.

  . Go to the *Configure>Domains* page.
  . Select the domain for which you want to enable voice service.
  . Click the gear icon menu and select *Edit*.
  . Scroll down to Voice and Chat section and from the *Voice/Chat Service* drop-down menu select the voice service to enable.
  . Click *Save*.

== Enable Voice/Chat Service on a COS
For Voice/Chat service on a COS, you must first enable the voice/chat service and then enable the voice feature.

  . Go to the *Configure>Class of Service* page.
  . Select the COS for which you want to enable the voice service.
  . Click the gear icon drop and select *Edit*.
  . On the General Information page, scroll down to *Voice and Chat* section and from the *Voice/Chat Service* drop-down menu select the voice service to enable.
  . In the Navigation pane, click *Features*.
  . On the Features page, scroll down to *Voice and Chat Features* section and click *Enable Voice Feature*. This displays the Voice tab in the {web-client}.
  . Click *Save*.

== Enable Voice/Chat Service on a User Account
For Voice/Chat service on a User Account, you must first enable the voice/chat service and then enable the voice feature.

  . Go to the *Home>Manage>Accounts* page.
  . Select the account for which you want to enable voice service.
  . Click the gear icon drop and select *Edit*.
  . On the General Information page, scroll down to *Voice and Chat* section.
  . From the *Voice/Chat Service* menu select the voice service to enable.
  . Enter a *Chat/Voice Username* for the user.
  This is the user account name in the third-party UC server.
  If you do not provide a name, the default name is used.
  For example for email account `\user1@domain.com`, the default voice username is “user1”.
  . From the *Voice/Chat Service* menu select the voice service to enable.
  . In the Navigation pane, click *Features*.
  . On the Features page, scroll down to *Voice and Chat Features* section and click *Enable Voice Feature*. This displays the Voice tab in the {web-client}.
  . Click *Save*.
  
== Enabling the Voice/Chat Zimlets
Zimlets are used in the configuration of the voice service to enable the service and send requests to the UC servers. The Voice Preferences Zimlet adds a voice page to the user interface, and the vendor specific Click2Call Zimlets provide the click to call capability.

  . Go to the *Home>Configure>Zimlets* page.
  . Enable the Voice Preferences Zimlet.
• Select the *Voice Preferences* Zimlet in the Content pane.
• Go to the gear icon menu and select *Deploy*.
  . Enable the vendor Zimlet for Click2Call.
• Select the Zimlet appropriate to the vender server you are using:
  . If you are using Cisco, select the *Cisco Click2Call* Zimlet.
  . If you are using Mitel, select the *Mitel Click2Call* Zimlet.
• Go to the gear icon menu and select *Deploy*.

If you want to undeploy a Zimlet, select the Zimlet and go to the gear icon drop down menu and select *Undeploy*, or you can toggle the Zimlet.

