[[introduction]]
Introduction
------------

Zimbra Drive is a client that interfaces Zimbra to third party products and services.

Currently supported products:

* Nextcloud
* ownCloud

WARNING: Zimbra Drive is a client that interfaces Zimbra to third party products and services. +
All data accessible from Zimbra Drive is not hosted on the Zimbra server or on any other Zimbra product, nor managed by Zimbra or any incorporated service.

[[about-this-document]]
About this document
~~~~~~~~~~~~~~~~~~~

This document targets system administrators, aiming to provide an
in-depth view of the product architecture and the knowledge necessary
for solid customizations.

Starting from Zimbra 8.8.0, Zimbra Drive is provided as an included
package of Zimbra Collaboration Suite; this means that the installation
process of Zimbra side components of Zimbra Drive can be performed
through Zimbra installation.

The `Installation` and `Configuration` chapters
cover the installation and the configuration of
the product in the supported enviroments respectively. +
The upgrade process is covered in the `Upgrade` chapter, also including all the
information about compatibility. +
The `Uninstallation` chapter contains the procedure to uninstall
Zimbra Drive. Advanced topics as how to build the software from the
sources are exposed in the `Advanced Topics` chapter.

WARNING: Backups, archiving, access security and user management is not done by or within Zimbra in any way. +
Malfunctionings, data and access security as well as storage management and data archiving on any third party product is not managed by Zimbra or through Zimbra software nor falls under any Zimbra Support contract as stated in section 2.4(a) of Zimbra's "Maintenance & Support Terms and Conditions".


[[overview]]
Overview
~~~~~~~~

[[general_architecture]]
General architecture
^^^^^^^^^^^^^^^^^^^^

The purpouse of Zimbra Drive is to connect the Zimbra end user to a
cloud service, external to Zimbra; any Zimbra domain can be paired to a
cloud service, then each Zimbra end user, belonging to this domain, will
benefit to the same cloud service platform.

Zimbra Drive is a three parts software (Zimbra Extension, Zimlet and
Cloud App), that integrate an external storage services in the Zimbra
Web Interface as well as authentication mechanism. Each Zimbra account
will be linked to the external storage service account allowing the user
back-and-forth.

[[components]]
Components
^^^^^^^^^^

Zimbra Drive components are the following:

1.  Zimbra Extension
2.  Zimlet
3.  Cloud App

Each component is mandatory and requires a careful configuration.
However any error in installation or configuration won’t affect Zimbra
usability.

[[extension]]
Extension
^^^^^^^^^

The Zimbra Drive extension is installed in the mailboxd component, it
acts in the middle between the Zimbra Drive zimlet and Cloud App
providing services like authentication and item actions to the zimlet.

[[zimlet]]
Zimlet
^^^^^^

The Zimbra Drive zimlet improves the user Zimbra interface adding a new
tab before Preferences tab, this tab is titled _Drive_. Furthermore the
zimlet let user perform search in linked cloud. +
The zimlet component is contained in package com_zextras_drive_open.zip
and the zimlet name is precisely _com_zextras_drive_open_.

[[supportedClouds]]
Cloud App
^^^^^^^^^

The external services of cloud storage need specific app with dedicated
API to communicate with Zimbra Drive Extension; Zimbra Drive provides an
app to each service supported.

[[nextcloudowncloud]]
Nextcloud/ownCloud
++++++++++++++++++

The Nextcloud/ownCloud App is a specific application for Nextcloud and
ownCloud, it provide transparent authentication in ownCloud and
Nextcloud using Zimbra credentials and a layer of compatibility which
abstracts the version of ownCloud and Nextcloud for the extension.

[[installation]]
Installation
------------

This chapter will guide the administrator through manual the
installation of the Zimbra Drive.

[[requirements]]
Requirements
~~~~~~~~~~~~

* Root-level access to the underlying operating system.
* Administrative access to an external cloud supported service (see
[==subsec:supportedClouds==]). +
Supported versions:
** Nextcloud 9, 10, 11
** ownCloud 9.0, 9.1, 10

[[zimbra-packages-installation]]
Zimbra packages installation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In this section is described how to install the Zimbra Drive Extension
and the Zimbra Drive Zimlet.

Both Extension and Zimlet are installed through the official Zimbra
installer, indeed Zimbra installation inquires for Zimbra Drive
installation. Zimbra Drive Extension and Zimbra Drive Zimlet will be
installed Answering ``Yes'' to the following questions in Zimbra
installation:

....
Use Zimbra's package repository [Y] Yes
...
Install zimbra-drive [Y] Yes
....

[[zimbra-already-installed]]
Zimbra already installed
^^^^^^^^^^^^^^^^^^^^^^^^

The Zimbra installation adds the Zimbra repositories to apt sources
list, so Zimbra Drive can be installed through the following command:

....
# As root, when apt-get is available
apt-get update
apt-get install zimbra-drive
# As root, when yum is available
yum update
yum install zimbra-drive
....

Hereafter Zimbra Drive Extension will be enable with the zimlet deploy
and a mailbox restart:

....
# As zimbra
zmzimletctl deploy /opt/zimbra/zimlets/com_zextras_drive_open.zip
zmmailboxd  restart
....

[[cloud-app-installation]]
Cloud app installation
~~~~~~~~~~~~~~~~~~~~~~

Here are provided the steps to install the Zimbra Drive Cloud App to the
specific supported cloud.

The cloud services currently supported are Nextcloud and ownCloud with
the archive `zimbradrive.tar.gz`.

[[==subsec:NextcloudownCloudInstallation==]]
Nextcloud/ownCloud
^^^^^^^^^^^^^^^^^^

Nextcloud and ownCloud requires the same following installation steps. +
The placeholder `PATHTOCLOUD` is the path of the Nextcloud/ownCloud
service in server:

1.  Copy `zimbradrive.tar.gz` in Nextcloud/ownCloud drive: +
`scp zimbradrive.tar.gz root@cloud:/tmp`
2.  In Nextcloud/ownCloud server, extract `zimbradrive.tar.gz` in
`PATHTOCLOUD/apps`: +
`tar -xvzf zimbradrive.tar.gz -C PATHTOCLOUD/apps`
3.  Change permissions of the extracted folder
`PATHTOCLOUD/apps/zimbradrive` with the user owner of Nextcloud/ownCloud
(E.g.: www-data): +
`chown -R www-data:www-data PATHTOCLOUD/apps/zimbradrive/`
4.  Enable Zimbra Drive App from Nextcloud/ownCloud Admin Interface or
with command:
`sudo -u www-data php PATHTOCLOUD/occ app:enable zimbradrive`

At this point the Nextcloud/ownCloud Zimbra Drive App is installed and
is required the configuration.

On Apache Web Server, Zimbra Drive doesn’t work if the server is not
correctly configured. The instructions about _Apache Web Server
Configuration_ in manual
https://docs.nextcloud.com/server/11/admin_manual/installation/source_installation.html#apache-web-server-configuration[Nextcloud
installation] or in manual
https://doc.owncloud.org/server/10.0/admin_manual/installation/source_installation.html#apache-web-server-configuration[ownCloud
installation] are required.

[[configuration]]
Configuration
-------------

Zimbra Drive configuration is splitted in Zimbra side and Cloud side.
Zimbra Drive Zimlet doesn’t need more than standard zimlet
configuration, therefore Zimbra side requires only Zimbra Drive
Extension configuration. About Cloud side, each supported cloud service
configuration will be shown later; they are indipendents and only the
configuration according to desired cloud service is required.

[[zimbra-extension-configuration]]
Zimbra Extension configuration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Zimbra Extension setup requires the url of the cloud service that will
be paired. This url has to be set in the domain attribute
zimbraDriveOwnCloudURL and it is common to all users belonging the same
domain. Different domains may have different cloud service urls. +
The command that set the cloud service url is the following:

....
# As zimbra
zmprov md domainExample.com zimbraDriveOwnCloudURL CLOUD_URL

....

The cloud service url (`CLOUD_URL`) has to be in the form:
`protocol://cloudHost/path`.

* `protocol`: can be `http` or `https`
* `cloudHost`: hostname of the server where the cloud service lies
* `path`: path in server of the targeted cloud service

Moreover each cloud service have its entry point. +
In Nextcloud/ownCloud, the url has to target at `index.php`
protocol://cloudHost/path/index.php

[[cloud-app-configuration]]
Cloud App configuration
~~~~~~~~~~~~~~~~~~~~~~~

[[NextcloudownCloudInstallation]]
Nextcloud/ownCloud
^^^^^^^^^^^^^^^^^^

When everything is correctly configured, the Zimbra end user creates a
private account in the cloud service that will be paired with the Zimbra
user account. This new cloud account inherit the Zimbra user credentials
and appears in users list of Nextcloud/ownCloud Admin Interface; however
this account is active until the Zimbra Drive app is enabled.

Nextcloud and ownCloud have the same following configuration entries. In
Nextcloud/ownCloud administration panel must appears a new ``Zimbra
Drive'' entry in the left sidebar that redirect to the configuration
view. There will be the following configurations:

* (CheckBox) *Enable Zimbra authentication back end* +
(Mandatory checked) On check, add a configuration in config.php that let
Nextcloud/ownCloud use Zimbra Drive App class. On uncheck remove this
configuration.
* (CheckBox) *Allow Zimbra’s users to log in* +
(Mandatory checked) Allows Zimbra users to use Nextcloud/ownCloud with
their Zimbra credentials.
* (InputField) *Zimbra Server* +
(Mandatory) Zimbra webmail host or ip.
* (InputField) *Zimbra Port* +
(Mandatory) Zimbra webmail port.
* (CheckBox) *Use SSL* +
Check if the Zimbra webmail port uses SSL certification.
* (CheckBox) *Enable certification verification* +
Disable only if Zimbra has an untrusted certificate.
* (InputField) *Domain Preauth Key* +
After Zimbra end user creates a private account with the first
successful access in Zimbra Drive, he can log in Nextcloud/ownCloud web
interface with their Zimbra credentials. In Nextcloud/ownCloud web
interface he will find a Zimbra icon in Apps menu that will open new a
Zimbra webmail tab without login step. +
This feature works only if the Zimbra Domain PreAuth Key is copied. In
zimbra run the following command in order to show the desired Zimbra
Domain PreAuth Key: +
`# As zimbra` +
`zmprov getDomain example.com zimbraPreAuthKey` +
`# If response is empty, generate with` +
`zmprov generateDomainPreAuthKey domainExample.com` +

[[upgrade]]
Upgrade
-------

This chapter will guide the administrator through the manual upgrade of
Zimbra Drive. It’s important to pay attention to the version of each
component: the compatibility is granted only if each component has the
same version. +
Unlike zimlet and extension that can be upgraded with Zimbra upgrade,
Zimbra Drive App must be kept manually updated.

[[zimbra-extension-and-zimlet-upgrade]]
Zimbra Extension and Zimlet upgrade
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When Zimbra is upgraded to a more recent version, Zimbra Drive can be
installed right from the installation. Anyway Zimbra Drive can be kept
upgraded in the same Zimbra major.minor versions with apt-get or yum:

....
# As root, when apt-get is available
apt-get update; apt-get install zimbra-drive
# As root, when yum is available
yum update; yum install zimbra-drive
....

[[cloud-app-upgrade]]
Cloud app upgrade
~~~~~~~~~~~~~~~~~

Unlike Zimlet and Extension, the Zimbra Drive Cloud app has to be
manually upgraded on every version change.

The upgrade of Zimbra Drive App in Nextcloud/ownCloud requires that
files are just replaced. Perform the steps as
installation([==subsec:NextcloudownCloudInstallation==]):

1.  Copy `zimbradrive.tar.gz` in Nextcloud/ownCloud drive +
`scp zimbradrive.tar.gz root@cloud:/tmp`
2.  In Nextcloud/ownCloud server, extract `zimbradrive.tar.gz` in
`PATHTOCLOUD/apps`: +
`tar -xvzf zimbradrive.tar.gz -C PATHTOCLOUD/apps/apps`
3.  Change permissions of the extracted folder
`PATHTOCLOUD/apps/zimbradrive` with the user owner of Nextcloud/ownCloud
(E.g.: www-data): +
`chown -R www-data:www-data PATHTOCLOUD/apps/zimbradrive/`

On ugrade from version 0.0.1 remove the table oc_zimbradrive_users that
is not more used. In mysql execute the following command: +
`DROP TABLE oc_zimbradrive_users;`

[[uninstallation]]
Uninstallation
--------------

This chapter will guide the administrator through the manual
uninstallation of Zimbra Drive and the cleanup of the system.

[[disablePackages]]
Disable Zimbra Drive packages
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Since Zimbra Drive Extension and Zimbra Drive Zimlet are installed as
Zimbra packages, their uninstallation is unexpected. The abeyance of the
Zimbra Drive feature can be reached disabling the Zimbra Drive Zimlet
from desired user, domain or class of service

[[remove-cloud-app]]
Remove Cloud App
~~~~~~~~~~~~~~~~

[[NextcloudownCloudUninstallation]]
Nextcloud/ownCloud
^^^^^^^^^^^^^^^^^^

The removal of Nextcloud/ownCloud App consists in the separate steps:
Clean up and App uninstall.

The Clean up step will delete all the Zimbra users data from
Nextcloud/ownCloud and is not reversible. It *requires* that the Zimbra
Drive is installed and enabled. +
Indeed, the Zimbra Drive App can be uninstalled without the removal of
Zimbra users storages (Clean up step can be skipped).

*Clean up*

Before starting the clean up, it’s recommended to disallow Zimbra users
access: the configuration *Allow Zimbra’s users to log in* should be
unchecked.

The following commands delete the users created by Zimbra Drive App and
clean the table containing references to Zimbra users (replace correctly
`mysql_pwd` and `occ_db`):

....
cd /var/www/cloud           # Go to the OCC path
mysql_pwd='password'        # database password
occ_db='cloud'              # database name for the Nextcloud / ownCloud

# In ownCloud
user_id_column='user_id'    # column name in table oc_accounts of ownCloud
# In Nextcloud
user_id_column='uid'        # column name in table oc_accounts of Nextcloud

mysql -u root --password="${mysql_pwd}" "${occ_db}" -N -s \
    -e 'SELECT uid FROM oc_group_user WHERE gid = "zimbra"' \
    | while read uid; do \
        sudo -u www-data php ./occ user:delete "${uid}"; \
        mysql -u root --password="${mysql_pwd}" "${occ_db}" \
            -e "DELETE FROM oc_accounts WHERE ${user_id_column} = '${uid}' LIMIT 1"; \
      done
....

*App uninstall*

In Nextcloud/ownCloud platform, the Zimbra Drive App can be removed from
the Nextcloud/ownCloud Admin Interface: the configuration should be
restored unchecking *Enable Zimbra authentication back end*, then Zimbra
Drive App must be disabled from the ``Enabled Apps'' tab and uninstalled
from the ``Disabled Apps''.

With the previous steps, the Zimbra Drive App folder
(`PATHTOCLOUD/apps/zimbradrive`) is deleted but all the users files
still remains in the cloud service drive: any configuration or file that
was not previously cleaned up, is retrieved on the reinstallation of
Zimbra Drive App.

[[advanced]]
Advanced Topics
---------------

[[build-from-sources]]
Build from sources
~~~~~~~~~~~~~~~~~~

This section exposes the steps to build the Zimbra Drive components. The
official Zimbra Drive source repository is hosted on
https://github.com/ZeXtras/ZimbraDrive[GitHub.com/ZeXtras/ZimbraDrive].

The build system uses relative path; the following example assumes that
the working path is /tmp/ but it can be changed at will.

....
# Clean the folder that will be used for the build
rm -rf /tmp/ZimbraDrive && cd /tmp/

# Clone the source repository
git clone --recursive git@github.com:ZeXtras/ZimbraDrive.git

# Jump into the source folder
cd ZimbraDrive

# Checkout the correct branch for the Zimbra release (assuming Zimbra 8.8.0 )
git checkout release/8.8.0

# Build the whole package setting the target Zimbra (can take some minutes)
make clean && make ZAL_ZIMBRA_VERSION=8.8.0
....

The final artifact `zimbra_drive.tgz` will be placed in folder
`/tmp/zimbradrive/dist`.

The `dist` folder:

The archive zimbra_drive.tgz contains all components of Zimbra Drive:

[[manual-installation]]
Manual installation
~~~~~~~~~~~~~~~~~~~

Manual installation is not supported.

The Zimbra Drive Zimlet and Extension are installed during the Zimbra
installation. Any modification to the installed zimbra packages may lead
to a fail during the Zimbra upgrade.

[[extension-1]]
Extension
^^^^^^^^^

The files zimbradrive-extension.jar and zal.jar must be copied in the
right place; then a mailbox restart is required to load the extension.

....
# As root
mkdir -p /opt/zimbra/lib/ext/zimbradrive
cp zimbradrive-extension.jar /opt/zimbra/lib/ext/zimbradrive/
cp zal.jar /opt/zimbra/lib/ext/zimbradrive/

# As zimbra
mailboxdctl restart

....

Everything is successfully done only if extension start correctly and
the following string should be logged in `ZIMBRA_HOME/log/mailbox.log`
at the moment of the last mailbox restart:

....
Initialized extension Zimbra Abstraction Layer for: zimbradrive

....

[[zimlet-1]]
Zimlet
^^^^^^

Deploy the zimlet with the following command:

....
# As zimbra
zmzimletctl deploy com_zextras_drive_open.zip

....

By default the zimlet is enabled for the ‘default‘ COS. The zimlet can
be enabled on the required COSes from the administration console.

[[manual-upgrade]]
Manual upgrade
~~~~~~~~~~~~~~

Manual upgrade is not supported.

The Zimbra Drive Zimlet and Extension are upgraded during the the Zimbra
upgrade. Any modification to the installed zimbra packages may lead to a
fail during the Zimbra upgrade.

[[extension-2]]
Extension
^^^^^^^^^

The Zimbra Drive Extension can be upgraded replacing the
zimbra-extension.jar and zal.jar files in
`/opt/zimbra/lib/ext/zimbradrive/` and performing a mailbox restart.

....
# As root
cp zimbradrive-extension.jar /opt/zimbra/lib/ext/zimbradrive/
cp zal.jar /opt/zimbra/lib/ext/zimbradrive/

# As zimbra
mailboxdctl restart
....

[[zimlet-2]]
Zimlet
^^^^^^

The Zimbra Drive Zimlet can be upgraded deploying the newest version and
flushing cache:

....
# As zimbra
zmzimletctl deploy com_zextras_drive_open.zip
zmprov fc zimlet
....

[[manual-uninstall]]
Manual uninstall
~~~~~~~~~~~~~~~~

Manual uninstallation is not supported.

Please consider to disable the Zimbra Drive (see:
[==sec:disablePackages==]) instead of uninstalling it. Any modification
to the installed zimbra packages may lead to a fail during the Zimbra
upgrade.

The manual uninstallation process of Zimbra Drive Zimlet and Zimbra
Drive Extension requires to undeploy zimlet and clean extension folder
from zimbra.

Remove Zimbra Drive zimlet:

....
# As zimbra
zmzimletctl undeploy com_zextras_drive_open
....

Remove Zimbra Drive Extension:

....
# As root
rm -rf /opt/zimbra/lib/ext/zimbradrive/

# As zimbra
zmmailboxdctl restart
....

The last but not necessary step is to clean the domain attribute with
the command +
`zmprov md domainExample.com zimbraDriveOwnCloudURL `

[[how_to_report_an_issue]]
How to report an issue
~~~~~~~~~~~~~~~~~~~~~~~~

In case an issue is found, the support team requires the following
informations:

* A detailed description of the issue: What you are expecting and what
is really happening.
* A detailed description of the steps to reproduce the issue.
* A detailed description of the installation and the environment: (see )
** Cloud information:
** Server information: Cpu, Ram, Number of the servers and for each
server:
*** Zimbra Version (see )
*** Zimbra Drive Version
*** List of the installed zimlets (see )
** Client information:
*** Browser name and version
*** Connectivity used between the servers and the client
*** Client Skin (theme)
*** Client Language
*** List of the Zimlets enabled on the user (see )
* Any log envolved by the issue:
** `mailbox.log`

Any personal information can be removed to protect the privacy.

[[gatheringinfo]]
Gathering System information
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This section will help the administrator to collect useful system
information required to correctly escalate an issue to the support team
ad described in the .

[[gatheringinfo-zversion]]
Zimbra version
^^^^^^^^^^^^^^

To see the version of the Zimbra type this command:

....
# As zimbra
zmcontrol -v

....

[[gatheringinfo-listzimlets]]
List of the deployed zimlets
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To see the list of the deployed zimlets type this command:

....
# As zimbra
zmzimletctl listZimlets

....

[[gatheringinfo-userzimlets]]
List of the zimlets enabled on the user
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To see the list of the Zimlets enabled for a user type this command:

....
# As zimbra
zmprov getAccount user@domain.tld zimbraZimletAvailableZimlets

....

[[gatheringinfo-userzimlets-pref]]
List of the zimlet user preferences
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To see the list of the preferences of the Zimlets enabled for a user
type this command:

....
# As zimbra
zmprov getAccount user@domain.tld zimbraZimletUserProperties

....

[[gatheringinfo-extension]]
Extension and Zimlet version
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To see the version of the Extension and the Zimlet

....
# As zimbra
java -cp /opt/zimbra/lib/ext/zimbradrive/zimbradrive-extension.jar \
    com.zextras.lib.ZimbraDrive

....
