= アーカイブとディスカバリ
:toc:

Zimbraアーカイブとディスカバリーはオプションの機能で、 {product-name} 送受信したメッセージをアーカイブし、メールボックスをまたいで検索することができます。

アーカイブ機能のインストールにより、 {product-abbrev} のディスカバリーツール (クロスメールボックス検索とも呼ばれます) もインストールされます。Zimbra MTA上でアーカイブを有効にするための属性値が設定されます。

アーカイブはアカウント単位で設定します。各アカウントのアーカイブを有効にするには、アカウント単位のZimbraのアーカイブライセンスが必要となります。アカウントのアーカイブを有効にした場合、そのアカウントについてMTAで受信と送信したメッセージのコピーが転送され、事前設定されたアーカイブメールボックスへ配信されます。アーカイブのプロセスはアカウントユーザーへ影響することはありません。

ディスカバリーの機能では、ライブとアーカイブメールボックスを横断したメッセージ検索と、指定したメールボックスに検索結果のメッセージをコピーすることができます。

== アーカイブのやり方について

ユーザーがメッセージを送受信した際、メッセージは、常にPostfixのMTAを経由してルーティングされます。PostfixのMTAでは配信中のメッセージに対し特定のアクションを実行するソフトウェアの使用を許可しています。アーカイブがメッセージの送信者、または受信者に対して有効な場合、ZimbraアーカイブがMTA hookとAmavisd-newの機能を用いてメッセージのコピーを生成します。

*受信者か送信者にアーカイブが有効であるかどうか* のチェックはSMTPのスタンダードエンベロープ上で実行され、FromやTo/CCのヘッダーでは実行されません。エンベロープ上でチェックが行なわれるため、BCCのコピーや配布リストへ送信したメッセージも取得されます。

.アーカイブが有効であるメッセージの送信
====
例えば、ユーザーAがユーザーBへメッセージを送信し、このときユーザーBのアーカイブが有効な場合、MTAは2つのメッセージを配信します。1つはユーザーBのメールボックス、そしてもう1つはユーザーBのアーカイブメールボックスです。ユーザーBのメールボックスで受信したメッセージは以下のように普通の見え方で受信されます。

----
Received: from localhost (localhost.localdomain [127.0.0.1])…
From: userA@example.com
To:userB@example.com
Subject: New License Key
Message-ID: <015f01c717fe$70f042d1$b1d6f61d@thom>
Date: Mon, 04 Nov 2008 23:48:18 -0000

Hi B,

Can you send me the license key for the software again?

Thanks, A
----

ユーザーBのアーカイブメールボックスで受信したメッセージには追加の
*X-Envelope-From* と *X-Envelope-To* のヘッダーが追加されます。これらのヘッダーは、メッセージが送信した実際のメールアドレス、そして受信したメールアドレスを示しています。

----
Received: from localhost (localhost.localdomain [127.0.0.1])…
From: userA@example.com
To:userB@example.com
Subject: New License Key
Message-ID: <015f01c717fe$70f042d1$b1d6f61d@thom>
X-Envelope-From: userA@example.com
X-Envelope-To: userB@example.com
Date: Mon, 04 Nov 2008 23:48:18 -0000

Hi B,

Can you send me the license key for the software again?

Thanks, A
----
====

Zimbraアーカイブでは、 {product-name} 内部で管理されるアーカイブアカウントを作成したり、サードパーティのアーカイブシステムへのメッセージ送信するためのSMTP転送を利用して、サードバーティアーカイブシステムと共に動作するように設定したりすることもできます。サードパーティのアーカイブの場合、 {product-name} は転送エージェントとして動作するように設定されます。

== ディスカバリー方法

アーカイブとディスカバリーのディスカバリー機能を使用して、ライブ^*^ とアーカイブのメールボックス内でメッセージと添付ファイルを検索します。ディスカバリーのツールを管理コンソールから実行して、指定したメールボックスへ検索結果をコピーすることができます。

^*^ ライブ のメールボックスはシステム上にある、アーカイブアカウントとシステムアカウント以外のアカウントです。

送信や受信したメッセージを日付、送信先、宛先、Cc、件名、キーワードおよび添付ファイルで検索できます。また、名前、日付と時間の期間範囲、配布リストおよびエイリアスで検索するクエリを作成することも可能です。

検索結果はターゲットメールボックスへ保存されます。様々なメールボックスを作成したり、検索のターゲットメールボックス内に個々のフォルダを作成したりして、検索結果の構成を管理することができます。ターゲットメールボックスへコピーされたメッセージには、 *X-zimbra-Source*
のヘッダー情報が各メッセージヘッダーへ追加されています。このヘッダーラベルにはアカウントID、アカウント名およびアカウントが存在しているサーバー名が含まれます。

検索結果はターゲットメールボックスへログインすることで確認できます。

== アーカイブパッケージのインストール

アーカイブのパッケージは、既存のシングルサーバー環境、またはマルチサーバー環境へインストールできます。

メールボックスサーバーとMTAサーバーが同一ノードに存在する場合、アーカイブ機能を一つのプロセスとして設定し、有効化します。メールボックスとMTAサーバーが別々のノードに存在する場合、zimbra-archiveのパッケージをまず最低一つのメールボックスサーバーにインストールし、環境内の各MTAにてアーカイブコンポーネントを有効化します。

=== シングルサーバー環境へアーカイブをインストールする

以下のシナリオではLDAP、MTA、メールストアおよびアーカイブのサーバーが同一のノードに存在しています。

.  {product-name} Single Server Installationガイドを参照し、SSHで {product-name} サーバーへ接続します。サーバーに  *root* としてログインし、アップグレードを `./install.sh` のコマンドで開始します。

. ライセンス同意確認を承認して、 *Yes* を入力し、アップグレードを開始します。

. インストール対象パッケージが表示される際、zimbra-archivingに対して *Yes* を入力します。

アップグレード処理が開始し、アーカイブのパッケージがインストールされます。ディスカバリー機能もインストールされ、使用可能となります。

アーカイブを有効化する場合、 *zimbra* ユーザーへ切り替えし、MTAサーバーでアーカイブ機能を有効化します。
[source,bash]
----
zmprov ms <Zimbraホスト名> +zimbraServiceEnabled archiving
----

サーバーを再起動します。
[source,bash]
----
zmcontrol restart
----

=== マルチサーバー環境にアーカイブをインストールする

以下のアップグレードシナリオでは {product-name}環境に新しいアーカイブ専用のサーバーを追加します。

インストールを開始する前に、以下の情報を記録します。アーカイブサーバーをインストールする際に以下の情報が必要です。
`zmlocalconfig -s` のコマンドより以下の情報を確認できます。

----
LDAP 管理者パスワード _____________________
LDAP ホスト名       _____________________
LDAP ポート           _____________________
----

マルチサーバーのパッケージのインストールガイドの詳細については、  {product-name}
Multi-Server Installation guideを参照してください。

. アーカイブを設定するメールボックスサーバーをSSHで接続します。サーバーに *root* としてログインし、Zimbraのソフトウェアを展開します。アップグレードを `./install.sh` のコマンドで開始します。

. *y* を入力し、 *Enter* キーを押すと、以下のパッケージがインストールされます。
+
* `zimbra-store`
* `zimbra-archiving`
+
パッケージ `zimbra-core` はデフォルトでインストールされます。

.  *y* を入力し、 *Enter* キーを押すと、 システムの修正が開始します。

. メインメニューでインストールするZimbraコンポーネントのデフォルト内容が表示されます。メニューを展開するには *x* を入力し、 *Enter* キーを押します。

.  *Common Configuration* メニューを選択し、LDAPのホスト名、パスワードおよびポートを設定します。

.  *zimbra-store* のメニューを選択し、管理者パスワードとライセンスファイルの場所を設定します。

Multi-server InstallationガイドのInstalling Zimbra Mailbox Server手順に従って、インストールを完了します。

この時点で、ディスカバリー機能はインストールされており、使用可能です。

== 管理コンソールからアーカイブを管理する

アーカイブ機能をインストール後、管理コンソールでアーカイブの設定と管理が可能です。

=== アーカイブを有効化する

管理コンソール: ::
*ホーム > 設定 > グローバル設 > MTA* へ遷移し、
*アーカイビング設定* から、 *アーカイブを有効にする* のオプションをチェックします。

コマンドラインで {product-abbrev} を再起動します。
[source,bash]
----
zmcontrol restart
----

=== 専用のアーカイブ提供サービスを作成する

提供サービスの属性値を設定することで、メールボックス機能、割り当て容量、パスワードの設定や、迷惑メールとウイルス検査の有効・無効化、GALからアーカイブアカウントを隠すなどができます。

管理コンソール: ::
*ホーム > 設定 > 提供サービス* へ遷移し、  *ギア* アイコンから *新規* をクリックします。

. アーカイブ用の提供サービスとして *機能* や *プリファレンス* を設定します。

. 専用のアーカイブサーバーをご利用の場合、サーバープールのページでアーカイブサーバーをリストから選択解除します。専用アーカイブサーバーのあるマルチサーバー環境にて、そのアーカイブサーバーがランダムに新規アカウントに割り当てられないように、COSサーバープールからこのサーバーを外す必要があります。
+
[NOTE]
サーバーをサーバープールから外す上記ステップは、シングルサーバー構成の場合、行いません。アーカイブのメールボックスを同様の設定で簡単に作成できるため、専用のアーカイブ提供サービスを作成することを推奨しています。

. 必要に応じて、*詳細設定* のオプションを設定します。

.  *アーカイビング* のページで *アーカイビングを有効にする* にチェックを入れて、提供サービスをアーカイブの提供サービスとして設定します。

. アーカイブアカウントの命名規則の形式を変更したい場合、 2箇所のテンプレートフィールドを変更します。詳細について、以下の
<<setting_up_an_archive_account_name,アーカイブアカウントの名前を設定する>>
を参照してください。

. *終了* のボタンをクリックします。

[[setting_up_an_archive_account_name]]
=== アーカイブアカウントの名前を設定する

属性値でアーカイブアカウントの命名規則を作成・管理することができます。管理する属性値は提供サービス、または各アカウントで設定します。管理コンソールの提供サービス、または各アカウントのアーカイブページに属性値の変更が可能です。

* *アカウントの日時テンプレート* ：命名規則のテンプレートに使用する日時フォーマットを設定します。デフォルトは `yyyyMMdd` です。アカウント名に日時を追加することで、システムからバックアップに古いデータを移動するのが容易になります。

* *アカウント名のテンプレート* ：アーカイブメールボックス名が作成される方法を設定する。デフォルトの値は `${USER} ${DATE}@${DOMAIN}.archive` です。

そのため、アーカイブのアカウントは、以下の例のようになります。

`user-20070510@example.com.archive`

デフォルトの値を変更する場合、有効なメールアドレスを作成するための文字列の形式を守る必要があります。アーカイブのスプーフィングを発生させないための対策として、すべてのアーカイブアカウントにドメインの後に `.archive` を追加することを推奨しています。

属性 `zimbraArchiveAccountDateTemplate` をベースとしたテンプレートが設定されると `zmconfigarchive` が実行される際に `amavisArchiveQuarantineAccount` が新しいテンプレート名へと更新されます。

==== アーカイブサーバーを管理する

サーバープロセス `amavisd-new` はアカウントのアーカイブおよびウイルスと迷惑メールの対策プロセスを管理します。 コマンド `zmarchivectl` でアカウントアーカイブ機能が管理しているamavisd-newのサーバープロセスの起動、停止、再起動、またはステータスを確認できます。アーカイブ、ウイルス対策、迷惑メール対策は同一のサーバープロセスを共有しているため、アーカイブ機能の開始や停止を行なう際は注意が必要です。共有しているプロセスへのアクションを起こす場合、環境内で有効な他の機能への影響が出る可能性があります。

ウイルスと迷惑メール対策を有効のままでアーカイブのみを無効にする場合、CLIや管理コンソールから個々のサービスを無効化します。

=== ユーザーのメールボックスにアーカイブを設定する

アカウントのアーカイブ機能には4つの属性が関連しています。2つはメールボックスを設定し、残りの2つはテンプレート属性でアーカイブアカウント名の作成に使用します。

メールボックスにアーカイブを設定する場合、ユーザーのメールボックスに2つの属性を設定します。1つの属性はアーカイブを有効化し、もう1つはメッセージがアーカイブされる場所を指定します。

* *現在のアーカイブ* -- 現在のアーカイブアドレス。アーカイブは単一のアカウントに対するものです。設定していない場合、アーカイブは無効です。

* *アーカイブしているアカウント* -- このメールボックスがアーカイブされていた全ての過去と現在のアーカイブアドレス。指定されたアカウントに対してアーカイブされていた全てのアカウントが含まれます。

== メールボックスをアーカイブする

アーカイブのメールボックスを特定の提供サービスに紐付けることができます。アーカイブされたメールをサードパーティに転送することも可能です。

[NOTE]
アーカイブを有効にしているアカウントはZimbraライセンスのアーカイブアカウント数にカウントされます。アーカイブメールボックスはユーザーアカウントと共に管理コンソールで一覧表示されます。ライセンス情報を確認するには、 管理コンソールの以下のページを参照してください。 +
*ホーム > 設定 > グローバル設定 > ライセンス*

=== アーカイブのメールボックスを作成し、提供サービスを適用する

アーカイブアカウントはZimbraのアーカイブ命名テンプレートをベースにして作成されます。

* アーカイブアカウントに属性 -- `zimbraIsSystemResource` -- が追加され、TRUEへ設定されます。

* アーカイブアカウントが管理コンソールに表示されます。

* アーカイブを有効にしているメールボックスへメッセージを受信した場合、メッセージのコピーがアーカイブのメールボックスへ送信されます。

ユーザー `zimbra` としてサーバーへログオンし、 以下のように `zmarchiveconfig` コマンドを実行します。
[source,bash]
----
zmarchiveconfig enable <account@example.com> archive-cos <archive>
----

=== 提供サービスとパスワードが設定されていないアーカイブのメールボックスを作成する

アーカイブアカウントに提供サービスを設定していない場合、以下の設定がデフォルトで設定されます。

* メールボックスの割り当て容量が0、つまり無制限に設定されます。

* ウイルスと迷惑メールの検査が無効化されます。

* アーカイブアカウントがGALに表示されないように "GALに隠す"が有効化されます。

ユーザー `zimbra` としてサーバーへログオンし、 以下のように `zmarchiveconfig` コマンドを実行します。
[source,bash]
----
zmarchiveconfig enable <user@example.com>
----

=== サードパーティのアーカイブサーバーへアーカイブを転送する

アーカイブアカウントが {product-name} で管理されていない場合、パスワード、提供サービス、その他の属性を設定する必要はありません。

ユーザー `zimbra` としてサーバーへログオンし、 以下のように `zmarchiveconfig` コマンドを実行します。
[source,bash]
----
zmarchiveconfig enable <account@example.com> \
 archive-address account-archive@offsite.com \
 archive-create false
----

== 複数のメールボックスを検索する

アーカイブとディスカバリー機能がインストールされている場合、管理コンソールやコマンドラインで、メールボックスをまたいで検索することが可能です。

[NOTE]
複数メールボックス検索をするためにアーカイブのメールボックスを設定する必要はありませんが、アーカイブのパッケージをインストールする必要はあります。

管理権限の委任をすることで、権限を委任された管理者は管理コンソールからメールボックスの検索を実行することができます。

=== 管理コンソールから複数のメールボックスを検索する

アーカイブのパッケージが追加されたら、ディスカバリーツールの *メール検索* が、ナビゲーションペインの *ツールおよび移行* のメニューへ追加されます。クロスメールボックスの検索を設定する場合、以下の情報を設定します。

管理コンソール: ::
*ホーム > ツールおよび移行 > メール検索* へ遷移し、 *ギア* アイコンから *新規* を選択。

* *サーバー名* ：検索するサーバー名。

* *ターゲットメールボックスとフォルダ*  ：ターゲットメールボックスとフォルダが自動的に作成されます。このメールボックスはすべての検索結果に使用できます。また、各検索に新しいフォルダを作成したり、各検索に新しいターゲットメールボックスを作成することができます。
+
ターゲットメールボックスは他のメールボックスと変わらず、提供サービスやアカウントごとに、機能とプリファレンスを指定できます。ターゲットメールボックスは管理コンソールのアカウントリストで確認できます。ターゲットメールボックスのアカウントに名前をつけて、クロスメールボックス検索用ターゲットメールボックスを識別したい場合、アクセスを管理するために特定の提供サービスを設定することを推奨しています。

* *検索結果で返答するメッセージ数を制限する* ：デフォルトは500件の検索結果です。

* 検索が完了したときにメール通知を送信することが可能です。メール通知の件名には検索のタスクIDとステータスが含まれ、また、ヒットしたメッセージ数、検索結果からのアドレスや使用した検索クエリなど、メッセージ本文に含む情報を指定できます。

* 検索するメールボックスを選択します。 *検索するアカウントを選択する*
をチェックした場合、検索するアカウントのアドレスを選択します。

* *検索クエリを作成する* ： アウトバウンドとインバウンドのメールを日時、送信者、宛先、Cc、件名、キーワードおよび添付ファイルにて検索できます。詳細検索では名前、日時の期間、配布リストおよびエイリアスによるクエリも作成できます。
+
アーカイブメッセージを検索する際、 *envfrom* と *envto* のクエリでエンベロープアドレスを検索します。

検索の実行時、メールボックス検索内容のペインに検索結果のリストやステータスが表示されます。*更新* をクリックするとページの情報を更新できます。

検索タスクはサーバーのメモリを使用するため、検索完了後は削除することを推奨しています。サーバーが再起動されると過去の検索が自動的に削除されます。

管理コンソールでディスカバリー機能を使用すると、このツールが管理者によって作成されたターゲットメールボックスにメッセージをコピーします。メッセージがサーバー容量を使用しますので、サーバーのサイズが増加します。そのため、検索結果でコピーされたメッセージの必要性がなくなったら、削除することを推奨しています。
