[[backup_and_restore]]
= バックアップと復元 (*)
:toc:

[NOTE]
*Zimbra 8.8 より、本機能は2つの異なるバージョンを提供しています。

Zimbra 8.8 ではスタンダード版と新世代（NG）版を提供しています。Zimbra 8.7 またはそれ以前のバージョンでは、スタンダード版のみを提供しています。以下にスタンダード版の詳細を記載しています。Zimbra 8.8 で本機能の NG版を利用する方法につきましては、本ガイドの NG版専用チャプターをご参照ください。

[WARNING]
スタンダード版のバックアップ（クラシックバックアップ）のサポートが終了しており、Zimbra 8.8.12 以降のリリースから削除する予定です。
新しいネットワーク版の NG モジュール、または ZSP へ移管していない環境はお早めに移管いただくよう、推奨しております。

{product-name} には、各
{product-name} サーバーに設定可能なバックアップマネージャーが備わっており、バックアップと復元の両方を実施できます。バックアップ処理の実行のために {product-name} サーバーを停止する必要はありません。

本章では、データのバックアップと復元方法、そして、 {product-name} メールボックスサーバーのバックアップと復元のために使用するCLIツールについて説明します。加え、障害復旧に関する情報と一般ガイドも記載します。

== メールボックスサーバーのバックアップ

{product-name} には、各
{product-name} サーバーに設定可能なバックアップマネージャーが備わっており、バックアップと復元の両方を実施できます。バックアップ処理の実行のために {product-name} サーバーを停止する必要はありません。シングルユーザーのメールボックス破損時、バックアップマネージャーを使用すれば、全システムの復元を行なわずにそのユーザーのみ復元することができます。完全・増分バックアップは `/opt/zimbra/backup` に保存されます。

=== Redoログ

各Zimbraメールボックスサーバーは、redoログを作成します。このログに、最終増分バックアップ時以降メッセージストアサーバーで処理された現在およびアーカイブのトランザクションを格納します。

サーバー復元時、バックアップファイルが完全に復元されてから、すべてのアーカイブにあるredoログと現在のRedoログが再実行されて、システムの不具合が発生する直前まで戻されます。

使用中のredoログファイルが100MBに達すると、そのRedoログはアーカイブディレクトリに移ります。そしてサーバーは新しいredoログを使用し始めます。前回のredoログのコミットされなかったトランザクションはすべて維持されています。クラッシュ時、サーバーを再起動すると、現在のRedoログ が読み込みこまれ、コミットされなかったトランザクションが再適用されます。

増分バックアップ実行時、redoログはアーカイブからバックアップディレクトリに移されます。

== バックアップ方法

バックアップ方法には2種類あります。

* *標準バックアップ* は、平日以外に完全バックアップを実行するエンタープライズ企業の環境に適しています。

* *オートグループバックアップ* は、一度の全アカウントの完全バックアップ完了までの時間が非常にかかるような大規模な {product-name}
環境の場合に推奨します。

=== 標準バックアップ

標準バックアップ方法は、完全バックアップを毎週、増分バックアップを毎日実行します。完全バックアップ処理は、メールボックスの復元に必要な全情報をバックアップします。これには、LDAPディレクトリサーバー情報、データベース、インデックスディレクトリ、各メールボックスのメッセージディレクトリも含まれます。

共有メッセージのバックアップ時、すでにバックアップ内にそのメッセージ用ファイルが存在する場合、そのことがこのアイテムにフラグ付けされるため再度内容がコピーされることはありません。

増分バックアップは、前回の増分バックアップ以降更新されたLDAPデータをバックアップし、全Redoログを収集します。あるメールボックスに完全バックアップがないと分かると増分バックアップ処理がそのメールボックスの完全バックアップを行ないます。

増分バックアップは、Redoログをバックアップのディレクトリに移します。Redoログとは、実行されたアクションごとの記録です。これには、配信された全メッセージの完全コピーや、タグ、連絡先、スレッドなどのメタデータの完全コピーが入ります。

これらのバックアップファイルを使用して、メールボックスサーバーを丸ごと復元、あるいはメールボックスを個別に復元してアカウントとメッセージデータを完全に復元することができます。

LDAPディレクトリは、完全バックアップや増分バックアップの処理の一環としてバックアップされます。アカウント、ドメイン、サーバー、提供サービス、その他のデータなどすべてがバックアップされます。

各メールボックスサーバーは、処理した全トランザクションが記録されるRedoログを作成します。予期せぬシャットダウンが発生すると、以下のようにRedoログを使用します。

* コミットされないままのトランザクションを確実に残さないように、スタートアップで最新のRedoログを読み込み、コミットされなかったトランザクションを全て再実行し完了させます。
* サーバー不具合時、直近の完全バックアップ後の書き込みデータを復旧します。

サーバー復元時、バックアップファイルが完全に復元されてから、すべてのアーカイブにあるredoログと現在のRedoログが再実行されて、システムの不具合が発生する直前まで戻されます。

Zimbra MTAのデータはサーバーに短時間しか残らないため、バックアップされません。

また、mailboxdの `jetty/etc/*.xml` などのカスタム設定もバックアップされません。

==== バックアップ通知

完全・増分バックアップの実行時、バックアップレポートが管理者アカウントに送信されます。レポートには、バックアップの成功・失敗、バックアップの開始時間・終了時間、バックアップしたアカウント数、Redoログのシーケンス範囲が記されます。

バックアップが失敗すると、エラー情報も追記されます。

=== オートグループバックアップ

オートグループバックアップ方法は、異なるメールボックスグループの完全バックアップをスケジューリングして個々にバックアップします。オートグループ方法は、全アカウントのバックアップが完了するまでに時間のかかる大規模な {product-name} 環境を対象にして設計しています。オートグループバックアップは、完全・増分バックアップを機能的に組み合わせているため、増分バックアップの実行は不要です。各オートグループのセッションが該当のメールボックスグループに完全バックアップを行ないます。オートグループバックアップはCLIでスケジュールして自動実行されるため、マニュアル操作でのオートグループバックアップ実行は推奨しません。

== バックアップファイルのディレクトリ構成

バックアップ先は、バックアップターゲットとして知られます。バックアップシステムの場合、メールサーバーのファイルシステムにあるパスがこれにあたります。Zimbraのデフォルトのバックアップディレクトリは `/opt/zimbra/backup` です。

標準バックアッププロセスで作成されるバックアップのディレクトリ構成の詳細は
<<standard_backup_directory_structure,標準バックアップのディレクトリ構成>>に記載されています。同一のターゲットエリアに定期的にスケジュールしたバックアップ先を設定・実行しても、以前のバックアップセッションは上書きされません。

ファイル *accounts.xml* に全バックアップの組み合わせで全アカウントがリストアップされています。アカウントごとにアカウントID、メールアドレス、そのアカウントの直近の完全バックアップ用ラベルがあります。バックアップのセッションを他の場所へ保存する場合、最新のaccounts.xmlもそこに保存する必要があります。アカウントの復元中、accounts.xmlを使用して、そのアカウントの直近の完全バックアップを参照します。accounts.xmlがないなら、復元する元となるバックアップのラベルを指定する必要があります。

Redoログのディレクトリは `/opt/zimbra/redolog/redo.log` です。現在のRedoログのファイルサイズが100MBに達すると、その現在のログファイルはアーカイブディレクトリ `/opt/zimbra/redolog/archive` に移ります。そしてサーバーは新しいredoログを使用し始めます。前回のredoログのコミットされなかったトランザクションはすべて維持されます。クラッシュ時、サーバーを再起動すると、現在のRedoログ が読み込みこまれ、コミットされなかったトランザクションが再適用されます。

Redoの操作は短時間で行なう必要があるため、コピー・削除ではなくディレクトリ移動が実施されます。ソースとターゲットのパスが同じファイルシステムのボリュームに存在するときのみ、ディレクトリを移動できます。つまり、RedoログとRedoログのアーカイブは同じファイルシステムのボリュームになければなりません。アーカイブファイルはRedoログのファイルシステムのサブディレクトリだからです。

増分とオートグループの全バックアップセッションはRedoログと同一のディレクトリに保存します。全Redoログが同一バックアップターゲットで見つかる必要があります。通常の完全バックアップセッションは、別のターゲットディレクトリを使用できます。

[[standard_backup_directory_structure]]
.基準バックアップのディレクトリ構成
[cols="1,3",options=""]
|=======================================================================
|`/opt/zimbra/backup` |
バックアップのデフォルトルートディレクトリです。

|`accounts.xml/` |
すべてのアカウント、そのアカウントのメールアドレスファイル・Zimbra ID・直近の完全バックアップラベルがリストアップされています。accounts.xmlは、メールアドレス、そのメールアドレスと現在のZimbra IDとのマッピング、各アカウントの直近のバックアップ情報を管理しています。

|`sessions/` |
バックアップセッションのルートディレクトリ。

|`full-<timestamp>/` |
完全バックアップのディレクトリ。セッションのタイムスタンプは、ミリ秒を含めたバックアップの開始時間 (GMT) 。サマータイムに対応するためにローカル時間ではなくGMTを使用しています。

|`session.xml` |
完全・増分バックアップセッションのバックアップラベルについてのメタデータ、例えば開始時間、完了時間等。

|`shared_blobs/` |
バックアップデータ内のアカウント間で共有しているメッセージファイルが入ります。

|`sys/` |
グローバルのデータベーステーブルとlocalconfig。

|`db_schema.xml` |
グローバルテーブルのデータベーススキーマ情報。各テーブルのダンプファイルは.csv形式のフォーマットです。

|`localconfig.xml` |
バックアップ時の `/opt/zimbra/conf/localconfig.xml` コピー。

|`<table name>.dat` |
データベーステーブルのデータダンプ。

|`LDAP/ldap.bak` |
LDAPのダンプ。

|`accounts/` |
各アカウントのデータはこのサブディレクトリに保存されます。

|`<.../zimbraId>/` |
各アカウントのルートディレクトリ。

|`meta.xml` |
アカウントのバックアップに関するメタデータ。

|`ldap.xml` |
アカウントのLDAP情報、エイリアス、アイデンティティ、データソース、配布リストなどを含みます。

|`ldap_latest.xml` |
このファイルが存在する場合、直近の増分バックアップのldap.xmlへリンクします。

|`db/` |
アカウント固有のデータベースのテーブルダンプ。

|`db_schema.xml` |
このアカウントのテーブル用のデータベーススキーマ情報。

|`<table name>.dat` |
データベーステーブルのデータダンプ。

|`blobs/` |
ブロブファイルが入ります。

|`index/` |
Luceneのインデックスファイルが入ります。

|`incr-<timestamp>` |
増分バックアップのディレクトリ。完全バックアップディレクトリのスキーマと類似していて、これらのメタファイルが含まれます。

|`session.xml` |

|`sys/db_schema.xml` |

|`accounts/.../<zimbraID>/ldap.xml` |
`incr-<timestamp>` に
`accounts/.../<zimbraId>/db/db_schema.xml` は入りません。
増分バックアップの場合、アカウントのテーブルをダンプしないからです。
|=======================================================================

[NOTE]
オートグループバックアップの場合、ディレクトリ構成により、完全バックアップセッションへのRedoログファイルが保存されます。増分バックアップのセッションはありません。

== 管理コンソールでのバックアップと復元

管理コンソールから直接実行できるバックアップと復元の操作が多数あります。左側のナビゲーションペインから *監視 > バックアップ*
を選択すると全サーバーがリストアップされます。

=== 管理コンソールでバックアップを設定する

バックアップは、管理コンソールからグローバル設定は特定のサーバーの設定として、設定できます。サーバー設定はグローバル設定にオーバーライドします。

グローバル設定の場合、バックアップ結果を受信するメールアドレスが設定できます。デフォルトではその管理者のアカウントに通知を送信します。

オートグループの場合、バックアップの分割グループの数を設定します。

標準バックアップがデフォルトで、自動スケジュールされます。他の変更を付け足す必要はありませんが、オートグループバックアップの実行時はマニュアル操作でのバックアップスケジュール設定が必要です。これにはCLIにアクセスし、
<<scheule_auto_group_backups,オートグループバックアップをスケジュールする>>
にある手順に従って `zmschedulebackup -D` を実行し、オートグループバックアップのデフォルトスケジュールを設定します。

*オートグループバックアップのスロットルオプション*
: オートグループバックアップ方法は、一度もバックアップが実行されていないメールボックスを次回予定されたバックアップで自動バックアップします。これは、大規模メールボックス移行・メジャーアップグレードの直後など、全メールボックスの完全バックアップが必要なときは最善ではありません。*Throttle automatic backups* を有効にすると日次バックアップでのメールボックス数がT/Nに制限されます。N日以内に全メールボックスをバックアップするという制約は守れない一方で、オフ時間帯にバックアップを完了できます。

一度でも全メールボックスがバックアップされたら、スロットルを無効化します。
[source, bash]
----
zmprov mcf zimbraBackupAutoGroupedThrottled TRUE
----

== CLIからのバックアップと復元

Zimbraのバックアップと復元プロセスはCLIコマンドから実行できます。

以下のユティリティを使用して、バックアップのスケジュール作成、完全・増分バックアップ実行、メールサーバーの復元、またはLDAPの復元ができます。

* `zmschedulebackup` -- このコマンドで完全・増分バックアップのスケジュールや、古いバックアップファイルの削除ができます。
* `zmbackup` -- このコマンドで{product-name} メールボックスサーバーの完全・増分バックアップを実行します。このコマンドは、ライブのサーバー上でmailboxdプロセスやメールボックスサーバーの起動中に実行します。このコマンドは、不要となった古いバックアップをマニュアルで削除できるオプションがあります。
* `zmbackupabort` --  実行中の完全バックアップを強制的に停止するコマンド。
* `zmbackupabort -r` -- 実行中の復元を強制的に停止するコマンド。
* `zmbackupquery` -- 実行中や完了しているバックアップ情報を、ラベルや実行日時を含めて返します。
* `zmrestore` -- {product-name} メールサーバーの完全・増分の復元を実行します。
* `zmrestoreoffline` -- mailboxdのプロセスが停止している状態で {product-name} メールサーバーを復元します。
* `zmrestoreldap` -- アカウント、ドメイン、サーバー、提供サービスなどのデータを含む、LDAPのディレクトリサーバーを完全に復元します。

こうしたコマンドごとの使用方法や詳細はZimbra CLIコマンド <<command_line_utilities,コマンドラインのユティリティ>>
を参照してください。

== 標準の方法でバックアップする

バックアップ開始時、バックアップするサーバー上でコマンドを実行することも、ターゲットサーバーを指定しリモートから実行することも、または管理コンソールでバックアップを実行することもできます。

=== 標準バックアップをスケジュールする

{product-name} がインストールされたときに自動で、完全・増分バックアップの標準の方法でのバックアップスケジュールがCrontabに追加されています。デフォルトスケジュールは、完全バックアップが毎週土曜の午前1時に実行されます。増分バックアップは日曜から金曜の午前1時に実行されます。

デフォルトで、1か月より前のバックアップが深夜0時に削除されます。

バックアップスケジュールを `zmschedulebackup` コマンドを使用して変更できます。

下記のとおり項目を指定します。項目はスペースで区切ります。

* 分 -- 0 から 59
* 時間 -- 0 から 23
* 月の日 -- 1 から 31
* 月 -- 1 から 12
* 曜日 -- 0 から 7 (または英語名。0と7は日曜日を意味します。)

使用しない値には、アスタリスクを入力します。


.`zmschedulebackup` オプションの例
========
* 既存の完全・増分バックアップ、バックアップの削除スケジュールをすべて変更します。 `-R` を使用すると、バックアップのスケジュールがすべて変更されます。スケジューリングするバックアップのセッションを自動削除したいなら、このコマンドの使用時にその削除スケジュールも忘れずにセットしてください。以下は、既存のスケジュールを次のように変更する例です。 +
日曜午前1時に完全バックアップを実行、月曜から土曜の午前1時に増分バックアップを実行、毎日正午に古いバックアップを削除。
+
[source, bash]
----
zmschedulebackup -R f "0 1 * * 7" i "0 1 * * 1-6" d 1m "0 0 * * *"
----

* 現在のスケジュールに完全バックアップを追加します。以下は、木曜の朝1時の完全バックアップを追加する例です。
+
[source, bash]
----
zmschedulebackup -A f "0 1 * * 4"
----
* バックアップスケジュールを確認します。スケジュールが返されます。
+
[source, bash]
----
zmschedulebackup -q
----
* スケジュールのコマンドをテキストファイルに保存します。再インストールやアップグレード後、同じスケジュールを簡単に再作成できます。
+
[source, bash]
----
zmschedulebackup -s
----

[NOTE]
デフォルトスケジュールに戻すには、以下のコマンドを実行します。 `zmschedulebackup -D`
========

==== デフォルトの標準バックアップのスケジュール

デフォルトのバックアップスケジュールが以下のように表示されます。

.デフォルトのバックアップスケジュール
======================================================
[source,bash]
0 1 * * 6 /opt/zimbra/bin/zmbackup -f - all
0 1* * 0-5 /opt/zimbra/bin/zmbackup -i
0 0 * * * /opt/zimbra/bin/zmbackup -del 1m
======================================================

読みかた

.完全バックアップを毎週土曜の午前1時に実行します。
[source,bash]
----
0 1 * * * 6 /opt/zimbra/bin/zmbackup -f - all
----


.増分バックアップを日曜から金曜の午前1時に実行します。
[source,bash]
----
0 1* * 0-5 /opt/zimbra/bin/zmbackup -i
----

.作成から1ヶ月経過したバックアップセッションを深夜に自動削除します。
[source,bash]
----
0 0 * * * /opt/zimbra/bin/zmbackup -del 1m
----


.crontableの読みかた
****
各crontabエントリには、下記6項目がこの順番で入ります。

[cols="1,1,1,1,1,5",options="header",]
|=======================================================================
6+|項目
|*1* |*2* |*3* |*4* |*5* |*6*
|*0* |*1* |* |* |*6* |`/opt/zimbra/bin/zmbackup -f -all`
|=======================================================================

. 分 (0-59)
. 時間 (0-23)
. 月の日 (1-31)
. 月 (1-12 または英語名)
. 曜日 (0-7 または英語名。0と7は日曜日を意味します。)
. 実行する文字列

[NOTE]
アスタリスクはワイルドカードとして機能し、項目の全ての候補値に該当します。
****

管理コンソール: ::
*ホーム > 設定 > グローバル設定 > バックアップ/復元*

管理コンソールから、メール通知の受信者の追加や受信者のアドレス変更ができます。

=== 完全バックアップのプロセス

完全バックアップのプロセスは以下の順でメールボックス、データベース、インデックス、LDAPディレクトリをバックアップします。

. システムテーブルや
`localconfig.xml` のファイルを含む、グローバルなシステムデータをバックアップします。
. バックアップターゲットとなるアカウントごとに、そのLDAPエントリのバックアップを繰り返します。
. アカウントのメールボックスをメンテナンスモードへ設定し、一時的にメール配信とユーザーからのアクセスを停止します。
. メールボックスをバックアップします。
.. そのメールボックスの関わる全データのMariaDBダンプを作成します。
.. そのメールボックスのメッセージディレクトリをバックアップします。
.. そのメールボックスのインデックスディレクトリをバックアップします。
. アカウントのメールボックスをアクティブモードへ戻し、次のアカウントに進みます。
. LDAPディレクトリをバックアップします。

完全バックアップは通常、非同期で実行されます。完全バックアップの開始時、実行中のバックアップのプロセスラベルが直ちに表示されます。バックアップはバックグラウンドで継続します。バックアップの実行ステータスは、 `zmbackupquery` のコマンドでいつでも確認できます。

バックアップファイルは圧縮なしのzipファイルとして保存されます。デフォルトのZipオプションの変更は <<command_line_utilities,コマンドラインのユティリティ>>
のzmbackupを参照してください。

=== 増分バックアップのプロセス

増分バックアップはCLIコマンドの *zmbackup* で実行します。増分バックアップのプロセスを以下に説明します。

. システムテーブルや
`localconfig.xml` のファイルを含む、グローバルなシステムデータをバックアップします。

. バックアップターゲットとなるアカウントごとに、そのLDAPエントリのバックアップを繰り返します。

. 直近のバックアップ以降に作成されたアーカイブRedoログをディレクトリ `<バックアップターゲット>/redologs` に移します。
+
増分バックアップ実行で１時間未満のアーカイブログはバックアップへコピーされ、削除されません。こうしたRedologは、バックアップ後1時間経過したら削除されます。この間隔はlocalconfigキー  `backup_archived_redolog_keep_time` で指定します。デフォルトは3600秒です。
+
アカウントに完全バックアップがないとき、バックアッププロセスは増分バックアップの実行が指定されていてもこのアカウントの完全バックアップを行ないます。

.  LDAPディレクトリをバックアップします。

==== マニュアル操作でバックアップを実行する

コマンドzmbackupを使用して、次のバックアップ操作を実行します。

* *server1* の全メールボックスをマニュアルでバックアップします。
[source,bash]
----
zmbackup -f -s server1.domain.com -a all
----
* 直近の完全バックアップ以降の *server1* の全メールボックスをマニュアルで増分バックアップします。
[source,bash]
----
zmbackup -i -s server1.domain.com -a all
----
* *server1* の *user1* のメールボックスのみマニュアルで完全バックアップします。
[source,bash]
----
zmbackup -f -s server1.domain.com -a user1@domain.com
----

==== バックアップのセッションを削除する

バックアップセッションは、ラベルまたは日時によって削除できます。

* ラベルによる削除は、指定したセッションとそれ以前のセッションをすべて削除します。
* 日時による削除は、指定した日時より前のバックアップセッションをすべて削除します。

例えば `zmbackup -del 7d` は今日より7日以前のバックアップをすべて削除します。日(d)、月(m)、または年(y)を指定できます。

=== 特定のバックアップを検索する

個々の完全・増分バックアップがバックアップセッションです。

各バックアップセッションは日時でラベル付けされます。例えば、full20070712.155951.123のラベルは、このバックアップが2007年7月12日の3:59:51.123に作成されたことを表します。

[NOTE]
セッションのラベルにはローカル時間ではなくGMTの時間を使用しています。サマータイムを導入している環境でのバックアップ実行時間を正常にするためです。

`zmbackupquery` コマンドで完全バックアップセッションを検索できます。

* 特定の完全バックアップセッションを確認します。
[source,bash]
----
zmbackupquery -lb full-20070712.155951.123
----
* 指定日以降の完全バックアップセッションを確認します。
[source,bash]
----
zmbackupquery --type full --from "2007/01/01 12:45:45"
----
* バックアップディレクトリにあるすべての完全バックアップセッションを確認します。
[source,bash]
----
zmbackupquery --type full
----
* 特定の時間の範囲でアカウント復元に適した時を確認します。
[source,bash]
----
zmbackupquery -a user1@example.com --type full --from "2007/07/05 12:01:15" --to "2007/07/12 17:01:45"
----

[NOTE]
バックアップ中にサーバークラッシュ (アボートではない)が原因でバックアップのセッションが遮断されると、中断されたバックアップセッションが一時セッションとして保存されます。一時セッションは `<バックアップターゲット>/sessions_tmp` のディレクトリに保存されます。rmコマンドを使用し、ディレクトリを削除できます。

== 完全バックアップを実行中に停止する

. バックアップをアボートするためにはバックアップのセッションラベルが必要です。 `zmbackup` を最初に起動した際にラベルが表示されます。完全バックアップのラベルが不明な場合、 `zmbackupquery` を使用してラベルを確認します。

. 実行中のバックアップを `zmbackupabort` のCLIコマンドで強制的に終了することができます。バックアップは直ちに停止し、部分的に成功したバックアップとなります。

* ラベル名を把握している場合、バックアップを停止します。
[source,bash]
----
zmbackupabort -lb full-20070712.155951.123 -s server1
----
* ラベル名が不明の場合、バックアップを停止します。
[source,bash]
----
zmbackupquery
zmbackupabort -s server1 -lb full-20070712.155951.123
----

== オートグループ方法でバックアップする

オートグループバックアップ方法は、管理コンソールまたはCLIから設定します。

管理コンソール: ::
*ホーム > 設定 > グローバル設定 > バックアップ/復元* または +
*ホーム > 設定 > サーバー -> _サーバー名_ -> バックアップ/復元*

=== CLIからオートグループバックアップを設定する

特定のサーバーにだけオートグループ方法を使用したくない場合、グローバル設定でバックアップ方法を設定してから、この設定をオーバーライドするサーバー設定で個別に設定します。

オートグループバックアップを設定するにはzmprovを使用し、LDAPの属性を編集します。
[source, bash]
----
zmprov mcf <ldap_attribute> <引数>
----
`zmprov ms` を使用して、サーバーレベルで属性を設定できます。

以下のLDAP属性を編集します。

* `zimbraBackupMode` --  *Auto-Grouped* に設定します。デフォルトはStandardです。
* `zimbraBackupAutoGroupedInterval` -- グループにバックアップセッションを実行する日数または週数を指定します。デフォルトは1日 (1d) です。バックアップ期間は1日以上です。xd (例えば、1d、など) やxw (例えば、1w、など) で入力できます。
* `zimbraBackupAutoGroupedNumGroups` -- メールボックス全体をグループ分割するグループ数です。デフォルトは7グループです。

[[scheule_auto_group_backups]]
=== オートグループバックアップをスケジュールする

オートグループバックアップスケジュールを設定する必要があります。

`zimbraBackupAutoGroupedInterval` の設定をベースとした、オートグループバックアップ用のデフォルトスケジュールを設定するには、 `zmschedulebackup -D` を実行します。

各インターバルで1つのグループがバックアップされます。オートグループバックアップは、サーバーのメールボックス数の変更に合わせて調整します。各バックアップセッションが以下をバックアップします。

* 一度もバックアップされたことのないメールボックスをすべてバックアップします。新たにプロビジョンされた メールボックスがこれに該当します。
* スケジュールされたバックアップ期間内にバックアップされなかったメールボックスをすべてバックアップします。例えば、6日後にバックアップするようにスケジュールされていれば、過去5日以内のバックアップされていないメールボックスがバックアップされます。
* メールボックスが比較的多いとき古いものから順にバックアップします。日次オートグループバックアップの負荷分散のためです。
+
例えば、オートグループの期間を日次 (1d) 、グループ数を7に設定すると、初回オートグループバックアップの実行で、全アカウントがバックアップされます。初回バックアップの後、オートグループが再度次の日に実行されます。今回は、新たにプロビジョンされたアカウントと、全アカウントの1/7相当のアカウントがバックアップされます。バックアップ日付が最古のアカウントからバックアップされます。このバックアップは、新たにプロビジョンされたアカウントと、バックアップ中の全アカウントの1/7相当のアカウントが7日間かけてバックアップされます。

共有メッセージのバックアップ時、すでにバックアップ内にそのメッセージ用ファイルが存在する場合、そのことがこのアイテムにフラグ付けされるため再度内容がコピーされることはありません。

バックアップファイルは圧縮なしのzipファイルとして保存されます。デフォルトのZipオプションの変更は <<command_line_utilities,コマンドラインのユティリティ>>
のzmbackupを参照してください。

これらのバックアップファイルを使用して {product-name}
システム全体、または個々のメールボックスのみを復元し、アカウントとメッセージデータの完全な復元ができます。アーカイブRedoログは完全バックアップの一部としてバックアップのセッションに移されます。サーバーがオートグループバックアップから復元されているなら、Redoログが再実行されて、システムの不具合が発生する直前まで戻されます。

== バックアップのオプション

バックアッププロセスの設定で、バックアップ内容の選択やMariaDBデータベースのバックアップが可能です。

=== バックアップに含まれる内容のオプション

以下のバックアップオプションで、完全バックアップのセッション中に検索のインデックス、ブロブ、HSMブロブをバックアップしないように設定できます。

* `zimbraBackupSkipSearchIndex` -- デフォルトは *FALSE* です。*TRUE* のとき、検索インデックスはバックアップされません。検索インデックスのないバックアップからのメールボックス復元後は、メールボックスを再インデックスする必要があります。
* `zimbraBackupSkipBlobs` -- デフォルトは *FALSE* です。
*TRUE* のとき、ブロブはバックアップされません。ブロブがフォールトトレランス対応のストレージにあるときにデータベースデータだけを早急にバックアップするのに役立ちます。この設定は、プライマリーとセカンダリ (HSM) ボリュームにある全ブロブに適用します。
* `zimbraBackupSkipHsmBlobs` -- デフォルトは *FALSE* です。
*TRUE* のとき、HSMボリュームにあるブロブはバックアップされません。
`zimbraBackupSkipBlobs` が *FALSE* で、HSMボリュームにあるブロブをスキップしたい場合は、これを有効にします。

=== MariaDBデータベースをバックアップする

{product-name} のバックアップ設定で、mysqldumpを実行してバックアップのセッション中にMariaDBデータベースをバックアップできます。これが有効なとき、完全バックアップ、増分バックアップ、オートグループバックアップごとにmysqldump が実行されます。

mysqldumpとは、MariaDBデータベースのある時点のバックアップです。ダンプファイル作成後のデータ変更がバイナリログに記録されます。ある地点に復元するには、バイナリロギングが有効化されていなければなりません。詳細は以下のZimbraのWiki記事、MariaDB Backup and Restore を参照してください。
https://wiki.zimbra.com/wiki/MySQL_Backup_and_Restore

MariaDBのダンプファイルはgzipされ、バックアップのターゲットディレクトリに移されます。ディレクトリを指定していない場合は `/opt/zimbra/backup` に移されます。

これらのファイルは非常に大きくなる可能性があります。そのため、MariaDBデータベースバックアップファイルごとに、そのMariaDBデータベースの実容量の3倍以上のディスク容量を用意する必要があります。


* バックアップ時にmysqldump を自動実行させるには、以下を入力します。
[source, bash]
----
zmlocalconfig edit mysql_backup_retention=<N>
----
*N* の値は保管するMariaDBのデータベースバックアップの数です。

[NOTE]
 MariaDBデータベースを復元する方法については、Zimbraサポートへご相談ください。

== バックアップ用のディスク容量を管理する

ターゲットのディスクに十分な空の容量が存在しないと、バックアップセッションは失敗します。このセッション中にバックアップされたデータはすべて破棄・削除されます。

バックアップの完了に十分な容量がない可能性があるとき、通知を受け取るように設定できます。

属性 `zimbraBackupMinFreeSpace` を設定すると、通知によってバックアップセッションの実行が管理しやすくなります。

バックアップセッションの実行前、`zimbraBackupMinFreeSpace` 属性の値に、バックアップターゲットディスクに必要な空き容量を設定します。属性に設定された値よりもディスクの空き容量が小さいとき、バックアップセッションは実行されません。それを通知するメッセージが管理者に送信されます。

[NOTE]
MariaDBデータベースもバックアップする場合、myslqdump のファイルサイズの格納に確実に足る値を設定する必要があります。

この属性の値は、ディスク全体のパーセント (25%など) またはバイト数 (300MB, 50GBなど) で設定できます。デフォルト値は0です。これは、チェックが無効かつバックアップが常に開始可能ということでます。

この属性はグローバルに、またはサーバーごとに設定できます。

* グローバル設定
[source, bash]
----
zmprov mcf zimbraBackupMinFreeSpace <value>
----
* サーバー設定
[source, bash]
----
zmprov ms <zmhostname> zimbraBackupMinFreeSpace <value>
----

設定した値の空容量さえあれば、バックアップのセッションは実行します。その値より実際のバックアップファイル大きいと、バックアップのセッションは失敗します。バックアップファイルのサイズを監視して、設定した値よりもバックアップ容量が必要な場合は修正する必要があります。

== データの復元

以下の3つの復元方法を実行できます。

* {product-name} メールボックスサーバーが起動中にメールボックスを復元する場合、`zmrestore` コマンドを使用します。

* `zmrestoreoffline` -- メールサーバーがオフラインの際にメールサーバーを復元する場合、zmrestoreoffline コマンドを使用します。このコマンドはディザスタリカバリに使用します。
* `zmrestoreldap` -- LDAPディレクトリサーバーの内容を復元する場合、zmrestoreldap を使用します。

復元プロセスではすべてのアカウント、または特定のアカウントを指定することができます。

=== 復元のプロセス

プロセス *zmrestore* が以下の手順でメールボックス、データベース、インデックス、そしてLDAPのディレクトリを復元します。

.  リストア対象として指定されたアカウント、または *all* を指定した場合にバックアップされているすべてのアカウントを取得します。
.  各メールボックスに以下の手順を実行します。
..  既存データをクリアするため、サーバーに存在するメールボックスを削除します。
..  直近の完全バックアップから、対象のメールボックス分にあたるMariaDBデータ、インデックスデータおよびメッセージディレクトリを復元します。
..  すべての増分バックアップにあるRedoログを直近の完全バックアップから復元したデータに適用します。
..  メールボックスサーバーのRedoログのアーカイブから、対象のメールボックス分にあたるRedoログを適用します。
..  現在のRedoログを適用します。

[NOTE]
アカウントの割り当て容量を超えても、アカウントは復元されます。ユーザーが割り当て容量に関するアクションを次回実行した際に、そのユーザーは割り当て容量を超えている旨の警告を受信します。

[IMPORTANT]
Microsoft OutlookのZimbraコネクターを利用しているユーザーについて、Zimbraサーバーが復元されたらOutlookクライアントで初回の同期を実行する必要があります。

*例*

.server1 にあるすべてのアカウントを完全に復元する。
====
直近の完全バックアップとその後に実行された増分バックアップを含みます。
[source, bash]
----
zmrestore -a all
----
====

.server1にある特定のアカウントの復元を実行する。
====
[source, bash]
----
zmrestore -a account@company.com
----
====

.特定の時間内に復元する (PIT)。
====
以下のオプションはRedoログの適用状況に影響します。これらのオプションを１つも指定しない場合、完全バックアップ以降のすべてのRedoログが適用されます。

[IMPORTANT]
下記にある、特定の時間内での復元オプションを実行した場合、復元したアカウントの完全バックアップを即座に取得し、アカウントに今後起こりうる問題を防ぐことを推奨します。

以下のオプションを含めた復元は特定の時間内での復元となります。

* `-restoreToTime` *<引数>* - 指定した時間までRedoログを適用する。
* `-restoreToIncrLabel` *<引数>* - 指定した増分バックアップを含む、指定した増分バックアップまでのRedoを適用する。
* `-restoreToRedoSeq` *<引数>* - 指定したRedoログシーケンスを含む、指定したシーケンスまでのRedoログを適用する。
* `-br` - バックアップに存在するRedoログのみを適用し、システムのアーカイブRedoログや現在のRedoログを適用しない。
* `-rf` - 完全バックアップのみを復元する。増分バックアップは含まれません。
====

.復元するまでの特定の時間、増分バックアップのラベル、またはRedoログシーケンスを指定する。
====
複数の時間を指定した場合、一番早い時間で復元を終了します。
[source, bash]
----
zmrestore -a account@company.com-restoreToTime <引数>
----
<timearg> を指定する形式は以下のどちらかを使用します。

* `"YYYY/MM/DD hh:mm:ss"`
* `YYYYMMDD.hhmmss`
====

.すべてのアカウントに直近の完全バックアップまでの増分復元を実行し、その後の増分バックアップを除外する。
====
[source,bash]
----
zmrestore -rf --a all
----
====

.特定のアカウントにメールボックスとLDAPデータを復元する。
====
[source,bash]
----
zmrestore -ra -a account@company.com
----
====

.新しいターゲットアカウントへ復元する。
====
プレフィックスが元のアカウント名に追加されます。
[source,bash]
----
zmrestore -ca -a account@company.com -pre restore
----
上記の実例の結果として、restoreaccount@company.comへデータが復元されます。
====

.データベース (db) と `localconfig.xml` のシステムテーブルを復元する。
====
[source,bash]
----
zmrestore -sys
----
====

.エラーが発生した場合に復元のプロセスが継続して実行されるように `--contineOnError` (`-c`)をコマンドに追加します。
====
[source,bash]
----
zmrestore -a all -c
----
`-c` を指定した場合、復元のプロセスが完了後、復元できなかったアカウントが表示されます。
====

.特定のアカウントを復元する。
====
削除されたアカウントを復元するためにも使用できます。
[source,bash]
----
zmrestore -a account@company.com
----
====

.削除されたアカウントを復元しないために以下のオプションを追加します。
====
[source,bash]
----
zmrestore -a account@company.com -skipDeletedAccounts
----
====

.メールボックスを復元するものの、Redoログ再実行で行なわれたすべての削除操作を除外する。
====

メールボックスが復元されると、削除済みのメッセージが格納されることになります。POPを使用するユーザーがサーバーからメッセージを削除する場合、このオプションが役に立ちます。
[source,bash]
----
zmrestore -a account@company.com --skipDeletes
----
[NOTE]
最新の時間をリクエストする場合、バックアップのラベル
(`-lb`)を指定しない。ラベルを指定しない場合、リクエストした時間より前の、直近の完全バックアップが自動的に開始時点として使用されます。
====

=== 復元のプロセスを停止する

コマンド `zmbackupabort -r` で実行中の復元プロセスを強制的に停止できます。復元のプロセスで復元中のアカウントの復元が完了した後に停止します。コマンドには、復元できなかったアカウントが表示されます。

復元を強制的に停止するには以下のコマンドを実行します。
[source,bash]
----
zmbackupabort -r
----

=== メールサーバーがダウン中にメールボックスを復元する

mailboxdのサーバーが起動していない状態でのみオフラインの復元プロセスを実行できます。基本的にオフラインの復元は以下の条件で実行します。

* Zimbraサーバーの特定の機能が破損し、サーバーが起動できない状態である。例えば、LDAPやデータベースのデータが破損している。
* ディザスタにより、サーバーにZimbraのソフトウェアを再インストールする必要がある。

Redoログのシーケンス順番を守るため、 {product-name} のメールボックスストアを起動する前にオフラインの復元を実行する必要があります。

ディザスタリカバリでZimbraのソフトウェアが再インストールされた場合、バックアップファイルから復元する前にmailboxdを起動すると、メールサーバーがメッセージの送受信などのアクティビティを開始し、処理中のRedoログに次々にログが出力されます。ディザスタ前のデータがサーバーに復元されていないため、Redoログのシーケンスが不正になります。一度mailboxdを起動してしまうと、障害前のデータを正常に復元することができなくなります。

オフラインの復元プロセスは以下の手順でデータを復元します。

. 指定した復元対象のアカウントを取得します。CLIから特定のメールボックスアドレスを指定していない場合、指定のメールホストのすべてのメールボックスをZimbra LDAPのディレクトリサーバーから取得します。
. メールボックスごとに以下の手順を繰り返します。
.. 既存のデータをクリアするため、サーバーにメールボックスを削除する。
.. メールボックスの直近の完全バックアップからMariaDBデータ、インデックスのディレクトリおよびメッセージディレクトリを復元する。
.. 直近の完全バックアップ以降のすべての増分バックアップにあるRedoログを復元したデータに適用します。
.. メールボックスサーバーのRedoログのアーカイブエリアから、そのメールボックスの対象となるRedoログを全て適用します。
.. 現在のRedoログを適用します。

==== すべてのアカウントを復元する

. mailboxdを停止した状態でserver1にあるすべてのアカウントを復元します。
+
[source,bash]
----
zmrestoreoffline -a all
----
. オフラインの復元が完了したら、mailboxdを起動します。
+
[source,bash]
----
zmcontrol startup
----

=== 起動中のシステムに特定のアカウントを復元する

コマンド *zmrestore* で1つか複数の特定アカウントを復元できます。ユーザーのメールボックスが破損している場合、直近の完全・増分バックアップからユーザーを復元したい場合があります。

. 復元対象の各アカウントをメンテナンスモードへ切り替えます。
+
[source,bash]
----
zmprov ma <アカウント名> zimbraAccountStatus maintenance
----
+
メンテナンスモードへ切り替えると復元中のメールの送受信が一時的に拒否されます。送受信を一時的に拒否しないと復元のプロセスでメッセージが上書きされることになります。

. アカウントに `zmrestore` のコマンドを実行します。
+
[source,bash]
----
zmrestore -a account@abc.com
----

.  復元が完了したアカウントをアクティブモードへ戻します。
+
[source,bash]
----
zmprov ma <アカウント名> zimbraAccountStatus active
----

[IMPORTANT]
復元したユーザーアカウントに対して、復元後に適用された提供サービスが存在しない場合、自動的にデフォルトの提供サービスがそのアカウントに適用されます。

=== 復元からアイテムを無視する

完全バックアップから復元する場合、検索インデックスとブロブを除外することが可能です。

* *検索インデックス* -- 検索インデックスのデータを復元しない場合、復元後にメールボックスを再インデックスする必要があります。
+
[source,bash]
----
zmrestore -a <all|account> --exclude-search-index
----

* *Blobs* -- 復元するメールボックスのブロブが既に存在する場合に役立ちます。
+
[source,bash]
----
zmrestore <all or account>|--exclude-blobs
----

* *HSM-blobs* -- 復元するアカウントのHSMブロブが既に存在する場合に役立ちます。
+
[source,bash]
----
zmrestore <all or account> --exclude-hsm-blobs
----

=== LDAPサーバーを復元する

ディザスタリカバリによりシステム全体を復元する必要がある場合、LDAPのディレクトリサーバーを最初に復元する必要があります。

コマンド zmrestoreldap を使用すると提供サービス (COS) 、配布リスト、などを含めたグローバルのLDAPデータを復元します。すべてのスキーマを再作成するLDAPサーバーを完全に復元することも、特定のアカウントのみを復元することも可能です。復元するセッションを指定します。復元するLDAPサーバー上で復元のコマンドを実行する必要があります。

*例*

.LDAPのセッションラベルを確認する
====
[source,bash]
----
zmrestoreldap -lbs
----
====

.LDAPのディレクトリサーバーを完全に復元する
====
[source,bash]
----
zmrestoreldap -lb full20061130135236
----
====

.特定のアカウントのLDAPデータを復元する
====
[source,bash]
----
zmrestoreldap -lb full20061130135236 -a tac@abc.com jane@abc.com
----
====

== 一般的な障害復旧の手順

複数マシンを利用する環境における、一般的なディザスタのシナリオとして、メールボックスのストアサーバーを以下のように復旧します。

=== 準備

.  メールボックスのストアサーバーを触る前にLDAPのディレクトリサーバーを直近の安定した状態へ復元します。
.  メールボックスを復元中はユーザーのログインやメール配信を停止する必要があるため、すべてのメールボックスをメンテナンスモードへ切り替えます。
.  メールボックスのストアサーバーが起動中であれば、停止します。

=== 復元

.  必要であれば、メールボックスサーバーに {product-name} のソフトウェアを再インストールします。
.  メールボックスを復元します。
.   {product-name} サーバーを起動します。
.  すべての {product-name} メールボックスをアクティブモードへ戻します。
.  サーバーの完全バックアップを実行します。

=== クラッシュ復帰のサーバー起動

システムが予定せずに停止し、スタートアップで再起動されると、サーバーはRedoログを確認して、コミットされなかったトランザクションを見つけると自動的に再実行します。Redoログの再実行により、システムが安定した状態になります。

===  {product-name}サーバーを復元する

完全な機械故障が発生した場合、以下の手順で新しいサーバーへ復元します。

[IMPORTANT]
新しいサーバーにインストールする {product-name} のバージョンは古いサーバーのバージョンと *完全に一致する必要があります* 。サーバーは別のOSを利用することが可能です。

新しいサーバーのハードウェアは {product-name} のシングルサーバーインストールガイドに記載されている条件を満たす必要があります。なお、新しいOSをインストールする際に必要なOSの設定変更はインストールガイドに詳細に記載されています。

新しいサーバーへ復元するには以下の操作を実行します。

.  新しいサーバーを準備する。
.  古いサーバーのIPアドレスへのクライアントアクセスをファイアウォールのルールで拒否する。
.  古いサーバーに使用されたボリュームをマウントする。
.  ZCSの初期設定で作成されるMariaDBデータを削除する。
.  バックアップファイルを新しいサーバーへコピーする。
.  `zmrestoreldap` でグローバルLDAPデータを復元する。
.  `zmrestoreoffine` でアカウントデータをバックアップセッションから復元する。
.  新しいバックアップの設定を行い、実行する。

==== 古いサーバーの状況

ディザスタリカバリにおける2つシナリオの１つは、サーバーが機械故障により
{product-name} のファイルへアクセスすることが不可能なこと、もう１つは {product-name}
は正常に起動しているもののサーバーのハードウェアを取り替える必要があることです。

*サーバーが起動していない場合*

.  サーバーのIPアドレスへのクライアントアクセスをファイアウォールのルールで拒否する。
.  使用可能な最終 {product-name} バックアップセッションを用意する。

*サーバーが起動している場合、新しいサーバーへ移動するための準備*

.  サーバーのIPアドレスへのクライアントアクセスをファイアウォールのルールで拒否する。
.  古いサーバーの完全バックアップを実行する、またはバックアップが最新である場合、直近のデータを取得するために増分バックアップを実行する。
.  `zmcontrol stop` を実行し、{product-name}を停止します。最終状態へ復元するためには、増分バックアップが完了後に新しいメールを受信してはなりません。
.  古いサーバーのホスト名とIPアドレスを別のものに変更する。
サーバーをオフラインにしない。

===  {product-abbrev} を新しいサーバーへインストールする

実行する前に新しいサーバーに正しいIPアドレスとホスト名が設定されていること、そして、{product-name}がインストール済みで、ドメイン、ホスト名、パスワード、などが前回のサーバーと一致していることを確認します。サーバーの準備に関する詳細は{product-name}インストールガイドを参照してください。{product-name}をインストールする前に古いサーバーから、管理者の名前とパスワード、LDAP、Amavis、Postfixのパスワード、迷惑メールと非迷惑メールのトレーニングのユーザーアカウント名、ドメイン名、グローバルドキュメントのアカウント名、などの必要な情報を確認することを推奨します。

[NOTE]
新しいサーバーのマシン時間も古いサーバーと一致する必要があります。古いホスト名とMX DNSレコードが新しいサーバーへ解決されることを確認します。

.  {product-name} のファイルを新しいサーバーへコピーします。新しいサーバーにライセンスが存在しない場合、{product-name}のインストールを正常に完了できません。
.  `./install.sh` を実行し、インストールガイドの手順にしたがって{product-name}をインストールします。古いサーバーのドメイン名、ホスト名およびパスワードを一致するように設定します。{product-name}のインストール中に以下の設定を元サーバーの設定に一致させる必要があります。
..  *Zimbra LDAP Server* --  *Domain to create* 、 古いサーバーのデフォルトドメインと同じものを設定します。
..  *Zimbra Mailbox Server* -- 管理者のアカウントが自動的に作成されます。
*  *Admin user to create* が、元サーバーの管理者ユーザーと一致することを確認します。
* 管理者のパスワードには、古いサーバーと同じものを設定します。
* LDAPのパスワードには、古いサーバーと同じものを設定します。
* PostfixとAmavisのユーザーパスワードには、古いサーバーと同じものを設定します。
*  *Spam training user* と *Non-spam (HAM) training*
*user* のアカウント名は、古いサーバーの迷惑メールトレーニングアカウント名と一致させます。
* *Global Document Account* -- このアカウント名は自動的に作成され、デフォルトの名前は通常wikiです。変更した場合、Global Document Accountの名前を古いサーバーに使用した名前と一致させます。
..  新しいサーバーの他の設定を元サーバーの設定と一致させます。
..  メインメニューにて、デフォルトのバックアップスケジュールを設定し、「設定完了後にサーバーを自動的に起動する」を *NO* に設定します。

==== 新しいサーバーへバックアップを復元する

.  新しいサーバーを停止します。
+
[source,bash]
----
zmcontrol stop
----

.  古いサーバーに追加のストレージボリュームを設定した場合、その追加ボリュームをマウントします。

.  MariaDBのデータを削除し、空のデータディレクトリを初期化する。これを実行しないとzmrestoreoffline実行時にエラーが発生します。zimbraのユーザーで以下のコマンドを実行します。
+
[source,bash]
----
rm -rf /opt/zimbra/db/data/* /opt/zimbra/libexec/zmmyinit
----
MariaDBのサービスが立ち上がりました。

.  古いサーバーの `/backup` ディレクトリ、またはアーカイブの場所からすべてのバックアップファイルを `/opt/zimbra/backup` へコピーします。

.  LDAPを復元します。
+
[source,bash]
----
zmrestoreldap -lb <latest_label>
----
+
大量のアカウントを復元する場合、復元が完了する前にセッションが切れないようにするため、nohupなどのUNIXコマンドを使用することを推奨します。
+
[NOTE]
復元するLDAPセッションのラベルを検索するには `zmrestoreldap -lbs` を実行します。

.  `zmrestoreoffline`を実行する前に、以下のサービスが起動していることを確認します。
  - mysqld (MariaDB)
  - slapd (OpenLDAP)
+
[source,bash]
----
zmcontrol start
----

.  `zmrestoreoffline`を実行する前に、以下のサービスが停止していることを確認します。
  - mailboxd
+
[source,bash]
----
zmmailboxdctl stop
----

.  現時点でいくつかの {product-name} サービスが起動しているため、 `zmconvertctl start` を実行します。 `zmrestoreoffline` を実行する前に実行する必要があります。

.  バックアップディレクトリのLDAPのパスワードを新しいサーバーのLDAP設定へ同期させます。
+
[source,bash]
----
zmlocalconfig -f -e zimbra_ldap_password=<password>
----

.  mailboxd を停止した後、オフラインの復元を開始します。
+
[source,bash]
----
zmmailboxdctl stop
zmrestoreoffline -sys -a all -c -br
----
+
この時点でもnohupのようなコマンド実行が考えられます。状況を監視するため、以下で確認できます。

  tail /opt/zimbra/log/mailbox.log
+
[NOTE]
コマンドラインに `-c` を使用することで、オフラインの復元中に多少のアカウントにエラーが発生してもアカウントの復元が継続的に実行されます。

.  現時点でいくつかの{product-name}サービスが実行中であるため、`zmcontrol stop` ですべてのサービスを停止します。

.  古いバックアップのセッションが無効となりますので、削除します。
+
[source,bash]
----
rm -rf /opt/zimbra/redolog/* /opt/zimbra/backup/*
----

.  {product-name}を起動します。
+
[source,bash]
----
zmcontrol start
----

.  完全バックアップを実行します。
+
[source,bash]
----
zmbackup -f -a all
----

. ファイアウォールのルールを解除し、新しいサーバーへのクライアントアクセスを許可します。

=== 異なる障害からの復元シナリオ

復元手順はほとんどのサーバー障害で、ほぼ同じです。障害が発生した場合、ディザスタリカバリの項を確認して処理を理解し、その後、それぞれの障害について以下の手順に従います。

==== LDAPが破損した場合の復元

.  LDAPサーバーを再インストールする。 {product-name} インストールガイドを参照してください。
.  復元するLDAPセッションのラベルを確認する。LDAPサーバーにすべてのアカウント、ドメイン、サーバー、COS、などを復元するために `zmrestoreldap - lb <ラベル名>` をオプションなしで実行します。
.  すべてのアカウントがアクティブモードであることを確認する。アクティブではない場合、以下のコマンドを実行します。

 zmprov ma zimbraAccountStatus active

==== 破損されたパーティションの交換後の復元

.  パーティションが壊れた場合、壊れているディスクを交換します。
.  直近の完全バックアップファイルと増分バックアップファイルを復元するには以下を実行します。
+
[source,bash]
----
zmrestore -a all
----
+
プロセス *zmrestore* では、指定したメールボックスのホストにある、バックアップ日以降のすべてのメールボックスを取得し、各メールボックスを直近の安定した状態へ復元します。

==== 破損、または読み込み不可のRedoログからの復元

Redoログが読み込み不可となった場合、mailboxdのサービスは停止され、再起動できなくなります。この現象が発生した場合、処理を続ける前にハードウェアとソフトウェアを検査し、問題の原因を特定する必要があります。

最新のRedoログがない場合、Zimbraのメールボックスサーバーを最新の状態へ戻すことはできません。Zimbraのメールボックスのデータを、最後にアーカイブしたRedoログの状態へ復元することができます。Zimbraのメールボックスサーバーが復元されたら、今後のトランザクションを記録する新しいRedoログが生成されます。

[IMPORTANT]
開始する前に、mailboxdのサービスは停止され、すべてのアカウントがメンテナンスモードへ切り替えられている状態でなければなりません。

.  すべてのアカウントをメンテナンスモードへ切り替えます。
+
[source,bash]
----
zmprov md <domain> zimbraDomainStatus maintenance
----

.  mailboxdのサービスが停止している状態で、以下のコマンドを実行します。
+
[source,bash]
----
zmrestoreoffline
----
+
オフラインの復元プロセスが始まり、バックアップから、指定したメールホストにあるすべてのメールボックスのリストを取得します。
+
次にオフラインの復元が各メールボックスに以下を実行します。
+
--
* サーバーからメールボックスを削除します。
* バックアップのデータから直近の完全バックアップを復元します。
* 直近の完全バックアップより保存した増分バックアップをメールボックスに古い順番に復元します。バックアップデータのRedoログの再適用を含みます。
* アーカイブにあるすべてのRedoログを適用します。
--
+
現在のトランザクション用のRedoログが使用不可であるため、メールボックスサーバーは、最後にアーカイブされたRedoログの状態へと復元されます。

.  オフラインの復元が完了したら、 {product-abbrev} を起動します。
+
[source,bash]
----
zmcontrol startup
----

.  Zimbraのメールボックスサーバーが起動したら、Zimbraサーバーの完全バックアップを実行します。最新のRedoログが使用不可であるため、最新のデータをバックアップするために完全バックアップを直ちに実行する必要があります。

=== Zimbraの復元後、ローカル設定ファイルを変更する

`/opt/zimbra/conf` にある `localconfig.xml` には、Zimbraの重要なパスやパスワードを含む、コアなZimbraサーバー設定が保存されています。このファイルは、完全・増分バックアップにバックアップされます。完全や増分の復元を実行した後、バックアップされた `localconfig.xml`
ファイル名が `localconfig.xml.restore` へ変更され、 `/opt/zimbra/conf`
へコピーされます。

直近のバックアップ以降に変更を行なった場合、localconfig.xmlを復元したファイルにて上書きする必要がある場合があります。これらのファイルを比べて、`localconfig.xml *.restore*` のファイルに最新の設定情報が含まれている場合、`localconfig.xml` を削除し、`localconfig.xml.restore` ファイル名を `localconfig.xml` へ変更します。

== スナップショットでのバックアップと復元

Zimbraのバックアップと復元機能を使用せずに、ストレージのレイヤで提供しているスナップショット機能を使ってサーバーをバックアップ、復元することができます。スナップショットを使用することで、スタンドバイのサイトを用意し、プライマリのサイトに障害が発生した場合にユーザーをスタンドバイのサイトへ転送することができます。

スナップショットはすべてのデータボリューム分を取得し、スタンドバイのサイトへ定期的に通信されます。スナップショットでバックアップされるデータのボリュームにはMariaDB、ブロブ、LuceneのインデックスおよびRedoログが含まれます。

プライマリのサイトがダウンした場合、zmplayredoのコマンドを使用して、スナップショットに整合性を持たせ、データの変更を再度適用します。これによりボリューム間でのデータ損失を最小限にします。

以下の4つのデータボリュームがあります。

* MariaDB
* Blob
* Luceneのインデックス
* Redoログ

スナップショットのセットは毎時取得され、リモートのスタンドバイサイトへ通信されます。ただし、すべてのスナップショットは同時に取得されないため、各スナップショットに1秒から1分間の差が発生する可能性があります。また、Redoログのスナップショットはより高い頻度で取得することも可能です。一般的な取得シーケンスは以下のようになります。

----
8:00:00 - mysqlのスナップショット実行
8:00:01 - ブロブのスナップショット実行
8:00:02 - インデックスのスナップショット実行
8:00:03 - redoログのスナップショット実行
8:05:00 - リモートサイトへスナップショットのセット通信完了
...
8:15:00 - redoログのスナップショット実行
8:15:05 - リモートサイトへredoログのスナップショット通信完了
...
8:30:00 - redoログのスナップショット実行
8:30:05 - リモートサイトへredoログのスナップショット通信完了
...
8:35:00 - プライマリサイトでの障害発生
----

リモートサイトでは8:00からいくつかのデータのスナップショットがあり、その後Redoログのスナップショットが続きます。ユーザーをスタンドバイのサイトへ転送したら、最新の情報がすべてそこで確認できるように、全情報を統合させる必要があります。

コマンド `zmplayredo` を実行し、8:00:00以降の変更を適用できます。

[source,bash]
----
zmplayredo --fromTime "2008/10/17 08:00:00:000"
----

すべてのデータが現在の時間まで復元され、スタンドバイのサイトが起動できる状態となります。8:30:00から8:35:00のデータが損失されますが、復元のプロセスが実行されているときの想定範囲内です。


== エフェメラルデータについての留意点

ZCS8.8時点では、エフェメラルデータがバックアッププロセスの一環としてバックアップされることはありません。認証トークンがエフェメラル属性であり、つまり、削除後復元されたアカウントに対してアクセスするクライアントは、再認証が必要になります。バックアップの前に作成された認証トークンは使用できなくなります。

=== SSDBバックエンドを使用したバックアップ

==== SSDB内でのエフェメラルデータのバックアップについて

SSDBがエフェメラルバックエンドとして使用される場合、エフェメラル属性は一切、バックアップに含まれません。

注意：本セクションでは、SSDBサーバのインストールや管理に関する詳細を案内しておりません。SSDBサーバの運用詳細につきましては <<ssdb-configuration-options.adoc#ssdb_configuration_options,SSDB インストールと設定>>をご参照ください。

SSDBを利用している場合、保管したデータを以下の方法でバックアップします。

[source,bash]
----
ssdb-dump -h localhost -p 8888 -o /tmp/ephemeral-backup-<日時>
----

注意：マスター/スレーブの設定で運用している場合、`ssdb-dump`は *マスター* で実行する必要があります。

===== バックアップの事例
[source,bash]
----
ssdb-dump - SSDB backup command
Copyright (c) 2012-2015 ssdb.io

recv begin...
received 1 entry(s)
received 10 entry(s)
received 100 entry(s)
received 1000 entry(s)
received 10000 entry(s)
received 100000 entry(s)
received 200000 entry(s)
received 300000 entry(s)
received 400000 entry(s)
received 400021 entry(s)
recv end

total dumped 400021 entry(s)
                               Compactions
Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
--------------------------------------------------
  2        1        7         0        0         7

compacting data...
                               Compactions
Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
--------------------------------------------------
  2        2       10         0        0        10

backup has been made to folder: /tmp/ephemeral-backup-<date>
----

==== SSDB へエフェメラルデータをリストアする方法

SSDBサーバのバックアップからのみ、エフェメラルデータをSSDBへリストアする事が可能です。

なお、リストア方法は以下のいずれかとなります。

 - 運用中のサーバへインポートする
 - 既存データを上書きする

===== 運用中のサーバへインポートする場合

SSDBソフトウェアで提供している`leveldb-import`コマンドを使用することで、
運用中のSSDBサーバへ`ssdb-dump`で作成したバックアップデータをインポートできます。

[source,bash]
----
leveldb-import localhost 8888 /tmp/ephemeral-backup-<日時>/data
----

==== 既存データを上書きする場合

SSDBサーバを停止します。
`ssdb-dump`コマンドでバックアップしたディレクトリを新しいディレクトリへコピーします。
`ssdb.conf`の設定ファイルを更新し、`work_dir`をコピーした新しいディレクトリに設定します。
SSDBサーバを起動し、以前のログインが正常に行えるか確認します。

=== LDAPバックエンドを使用したバックアップ

エフェメラルバックエンドがLDAPの場合、認証トークンもCSRFトークンもバックアップに含まれません。ただし、最後にログインしたタイムスタンプは含まれます。アカウントの復元で、管理コンソールの "最終ログイン"値には適切な値が復元されます。
