[[color_and_logo_management]]
= テーマ色やロゴ管理
:toc:

個々の {product-name} テーマをカスタマイズしなくても、Zimbraウェブクライアントのベーステーマで使うベース色とロゴを変更することができます。これはCLI、または管理コンソールで実行できます。

== Zimbraウェブクライアントのテーマ色とロゴを変更する方法

テーマのベース色とカスタムロゴはグローバル、またはドメインごとに設定することができます。

* グローバル設定を変更した場合、変更がすべてのサーバーにあるすべてのテーマに適用されます。

* ドメインの設定を変更した場合、ドメインにあるテーマのベース色とロゴが変更されます。

テーマのベース色やロゴがグローバル設定とドメイン設定で異なる場合、ドメインに設定した内容が優先的に適用されます。

[IMPORTANT]
マルチドメインの {product-name}
環境でロゴとベース色をカスタマイズする場合、仮想ホストをベース色として設定しなければなりません。ブラウザから送信されるホストヘッダーに基づき、ロゴの属性が表示されます。

[NOTE]
{product-name}には複数のZimbraテーマが含まれています。Lemongrass, Hot Rod, Waves などのいくつかのテーマでは、ベース色を修正しても画像や色コードが変更されないように設計されているものもあります。こうしたテーマをユーザーのテーマプリファレンスから無効化することもできます。

=== ベースのテーマ色のカスタマイズ

ZWCのテーマの以下のベース色を変更できます。

* クライアントのプライマリ背景色。
+
この色はページの背景色となります。様々な色がボタンや内容の背景、ペイン、タブ、選択のハイライトに使用されます。以下の画像では背景色がロゴとともに表示され、様々な背景色がログインエリアに表示されています。
* セカンダリー色はツールバーに使用する色です。
* 選択色は選択したアイテムの色です。例えばメッセージやオーバービューペインにあるアイテムです。
* 前景色は表示するテキストの色です。デフォルトの色は黒です。テキストの色は通常、変更する必要のないものです。

=== ZWCロゴを交換する場合

Zimbraのロゴを会社のロゴにグローバル、またはドメインごとに変更できます。

[NOTE]
*_ロゴ変更のライセンスポリシーについて_* +
_Zimbraの公式ライセンスではZimbraウェブクライアント内のZimbraロゴの削除を認めていません。ネットワークエディションのお客様のみがZimbraウェブクライアントのロゴを交換することができます。このため、ネットワークエディションのお客様のみ以下の手順を参照してください。ライセンスの詳細については以下のページを参照してください。 https://www.zimbra.com/license/_

==== 交換する画像

以下のZimbraロゴファイルを変更できます。カスタムのロゴ画像ファイルを正常に表示するため、以下に指定している解像度にする必要があります。画像のファイルは別のサーバーまたは {product-name} がアップグレードした際にも上書きされないようなディレクトリに保存することができます。

* ZWCと {product-name} の管理コンソールでログインとスプラッシュ画面に表示するロゴ。この画像の解像度は300×30にする必要があります。
* ZWCアプリケーションと管理コンソールの左上に表示するロゴ。この画像の解像度は170×5にする必要があります。
* 会社のロゴをクリックした際にリンクする会社のURLアドレス。

==== 交換できない画像

詳細検索のツールバーに表示されるZimbraアイコンおよびURLのブラウザアドレスバーに表示されるfavicon.icoは、現時点では変更することができません。

=== 管理コンソールによるテーマ色とロゴ画像の変更について

管理コンソールのグローバル設定とドメイン設定にあるテーマページは、色のスキーマをカスタマイズしたり、会社のロゴとロゴURLを追加するなどの設定が可能です。Zimbraウェブクライアントと管理コンソールページに使用する会社ロゴをサーバーにアップロードしてください。

==== ベースのテーマ色を変更する

事前設定された色のテーブルのポップアップから選択するか、６桁の16進カラーコードを入力して、次のカテゴリのテーマ色に合う色を設定できます。

* テーマの前景色：テキストの色です。
* テーマの背景色：クライアントのプライマリ背景色です。
* テーマの補色：ツールバーやメニューペインの選択ヘッダーの色です。
* テーマの選択色：選択したアイテムの色、例えばメッセージ、右クリック、またはドロップダウンのメニュー選択肢です。

[NOTE]
テーマ設定の変更にはサーバーのテーマキャッシュのフラッシュが必要です。 *ホーム > 設定 > サーバー* へ遷移し、サーバーリストを表示してください。対象のサーバーを右クリックして表示されるメニューから *キャッシュのフラッシュ* を選択します。

テーマに合う色の設定には、*テーマのロゴをカスタマイズ* コンテナを利用します。

管理コンソール: ::
*ホーム > 設定 > グローバル設定 > テーマ* または +
*ホーム > 設定 > ドメイン -> _ドメイン名_ -> テーマ*

1.  修正するテーマカテゴリの項目をクリックし、ポップアップ表示された色のテーブルを使用して希望の色を決定します。
+
色を直接クリックし、選択しても、入力項目に16進カラーコードを入力してもかまいません。いずれにしても選んだ色が項目に表示されます。
+
色の指定をやめたい場合、*テーマのすべての色をリセット* ボタンをクリックし、選択した内容を消去します。

2.  このページを離れると、設定を保存するかどうかが質問されます。
+
*はい* (保存) または *いいえ* (選択した内容を消去)をクリックします。

==== ロゴを追加する

グローバルに、またはドメイン単位で、該当のテーマページから {product-name}ロゴを会社ロゴに変更することができます。ロゴは *交換する画像* セクションに記載されているサイズと同じでないと、正常に表示されません。画像のファイルは別のサーバーまたは{product-name} がアップグレードした際にも上書きされないようなディレクトリに保存します。

[NOTE]
 *グローバル設定 >テーマ* の *テーマのロゴをカスタマイズ* セクションから設定を行なう場合、画像が正常に表示されるためにはこのセクションの前項目を入力しなければなりません。

なお、詳細検索のツールバーに表示されるZimletアイコンおよびURLのブラウザアドレスに表示されるfavicon.icoは変更することができません。

テーマに合うロゴの設定には、*テーマのロゴをカスタマイズ* コンテナを利用します。

管理コンソール: ::
*ホーム > 設定 > グローバル設定 > テーマ* または +
*ホーム > 設定 > ドメイン -> _ドメイン_ -> テーマ*

.ロゴの設定

[cols=",",options="header",]
|====================================================================
|オプション | 説明

| テーマのロゴURL |
ロゴからリンクされる会社のウェブアドレス

| テーマのアプリケーションロゴバナーURL |
ZWCと管理コンソールのログインとスプラッシュ画面で表示される会社ロゴ。解像度は正確に450×100でなければなりません。

| アプリケーションロゴバナーのプレビュー(200×35) |
ZWCアプリと管理コンソールの左上の会社ロゴ。解像度は正確に200×35でなければなりません。

| テーマのログインロゴバナーURL |

| ログインロゴバナーのプレビュー(440×60) |

|====================================================================

=== テーマ色とロゴの変更にCLIを使用する

ZWCテーマのベース色とロゴ変更にはzmprovコマンドを使用します。次の属性はグローバル設定あるいはドメイン設定のいずれかで設定します。カラーコードは十六進法の6数字で入力します。

.色の属性
[cols="m,",options="header",]
|====================================================================
|属性 |説明

|zimbraSkinBackgroundColor |
クライアントで表示するプライマリ背景色の16進カラーコード。

|zimbraSkinSecondaryColor |
ツールバーと選択されたタブ色の16進カラーコード。

|zimbraSkinSelectionColor |
選択したアイテムの16進カラーコード。

|zimbraSkinForegroundColor |
テキスト色の16進カラーコード。デフォルトが黒のため、この属性は通常、変更する必要はありません。

|====================================================================

*テーマのベース色を変更する方法*

始める前に変更する属性に設定する16進カラーコードを用意します。変更するコマンドは以下となります。

.グローバル設定を変更する場合
[source,bash]
----
zmprov modifyConfig <属性名> [“#6進カラーコード”]
----

.ドメインの設定を変更する場合
[source,bash]
----
zmprov modifyDomain <ドメイン名> <属性名> [“#6進カラーコード”]
----

*ドメインの編集*

以下の例ではベースの色を変更します。

* 背景色 = サンゴ色, #FF7F50
* セカンダリー色 = 空色, #ADEAEA
* 選択色 = 黄色, #FFFF00

1. スキンカラーを指定します。`zimbra` ユーザーでログインし、ドメイン修正のために `zmprov` を使用します。
+
[source,bash]
----
zmprov modifyDomain example.com \
 zimbraSkinBackgroundColor "#FF7F50" \
 zimbraSkinSecondaryColor "#ADEAEA" \
 zimbraSkinSelectionColor "#FFFF00"
----
+
`#` の記号を使うには、クォーテーションマーク `""` が必要です。
+
2.  変更した内容を適用するため、zmmailboxdctlコマンドを使用し、メールボックスを再起動します。
+
  zmmailboxdctl restart
+
ウェブクライアントをリロードすると、指定したドメインの {product-name} テーマ は上記で変更した色で表示されます。

*ロゴの追加方法*

会社のロゴURL情報や画像は以下の属性で管理しています。

.ロゴの設定
[cols="m,",options="header",]
|=======================================================================
|属性 |説明

|zimbraSkinLogoURL |
zimbraSkinLogoURL ― ロゴ画像クリックで遷移させたい会社のウェブアドレス。

|zimbraSkinLogoLoginBanner |
ZWCと {product-name} 管理コンソールのログインとスプラッシュ画面に使用するロゴの画像ファイル名。

|zimbraSkinLogoAppBanner |
ZWCと管理コンソール画面の左上に表示するロゴの画像ファイル名。

|=======================================================================

*ドメインにロゴを追加する方法について*

ロゴファイルを {product-name} サーバーに保存する場合、 `/opt/zimbra/jetty/webapps/zimbra` のサブディレクトリに格納する必要があります。

ロゴが他のマシンにある場合、ロゴを特定する正確なURLを入力してください。

本項のステップで、ドメインに表示されるロゴを更新します。

1.  URLを変更します。
+
 zmprov modifyDomain zimbraSkinLogoURL https://url.example.com/
+
2.  ロゴ表示を修正します。
+
ロゴ画面とスプラッシュ画面に表示されるロゴを変更します。
+
 zmprov modifyDomain zimbraSkinLogoLoginBanner /zimbra/loginlogo.png
+
ZWCのメインページに表示されるロゴを変更します。
+
 zmprov modifyDomain zimbraSkinLogoAppBanner /zimbra/applogo.png
+
3.  メールボックスを停止・起動します。
+
 zmcontrol restart

[NOTE]
ZWCのロゴ修正は、_現在サポート対象外_ です。
