[[delegated_administration]]
= 管理権限の委任 (*)
:toc:

[NOTE]
*Zimbra 8.8 より、本機能は2つの異なるバージョンを提供しています。Zimbra 8.8 ではスタンダード版と新世代（NG）版を提供しています。Zimbra 8.7 またはそれ以前のバージョンでは、スタンダード版のみを提供しています。以下にスタンダード版の詳細を記載しています。Zimbra 8.8 で本機能の NG版を利用する方法につきましては、本ガイドの NG版専用チャプターをご参照ください。

グローバル管理者(システム管理者)は、様々な「委任された管理者」の役割を作成できます。

「委任された管理者」の役割には、配布リストの管理や、ユーザーが忘れたパスワードのリセットのように単純なものから、ドメインに対するドメイン管理者まで、様々な権限があります。

よく使用される２つの管理の役割である、ドメイン管理者と配布リスト管理者は既に定義されています。これら既存の役割の場合、管理者を追加するために必要な設定は他にありません。


== 管理者権限を付与するターゲット種類

管理権限の委任には、ターゲット上でのアクセス制御を制限するための定義を行なうことと、管理者がターゲットでタスクを実行するための権限を付与することがあります。

「ターゲット」とは、権限付与の対象とされる {product-name} のオブジェクトです。各ターゲットは「ターゲット種類」に紐づきます。「ターゲット種類」は、ターゲット上でのアクセス制御エントリのタイプを識別します。

ターゲットに「ターゲット種類」を選択するときは、以下を参考にしてください。

* ターゲットについて。どの特定のターゲットに権限を付与しますか？　例えば、ターゲット種類に「ドメイン」を選択した場合、どのドメインを指していますか？特定のドメイン名を指定してください(ターゲット名=example.com)。そのターゲットにアクセス制御エントリ(ACE)が付与されます。ACEは、そのターゲットエントリのLDAPデータに保存されます。

* 付与したい権限は、選択したターゲット種類に適していますか？権限は、関連するターゲット種類にしか適用できません。例えば、アカウント作成は、ターゲット種類「ドメイン」にしか適用できませんし、パスワード設定は、ターゲット種類「アカウント」「カレンダーリソース」にしか適用できません。ターゲットに適用できない権限がターゲット上に付与されると、その権限は無視されます。

* 権限を定義するときは、付与される権限が機能するターゲットスコープを考慮する必要があります。例えば、パスワード設定は、ターゲット種類「アカウント」「カレンダーリソース」にしか適用できませんが、この権限がターゲット種類「ドメイン」の権限リストに含まれると、ドメイン内のすべてのアカウントとカレンダーリソースで機能することになります。

.権限のターゲット
[cols="1,3",options="header",]
|=======================================================================
|ターゲット種類 |ターゲットスコープの説明

|アカウント |
アカウントエントリ(特定のユーザー)

|カレンダーリソース |
カレンダーリソースエントリ

|COS |
提供サービスエントリ

|配布リスト |
配布リストとその配布リスト配下の全配布リスト。

アカウントとカレンダーリソースに適用できる権限の場合は、この配布リストの直接のメンバーまたは間接のメンバーである、すべてのアカウントとカレンダーリソースもスコープ内。

|ドメイン |
特定のドメインが該当します。サブドメインは対象外。

サブドメインの場合、ターゲットとして明確にタグ付けされている必要があります。

ドメインがターゲットのとき、権限は、ドメイン内のすべてのアカウント、カレンダーリソース、配布リストについて付与されます。

|設定 |
グローバル設定専用の権限

|グローバルACL |
ターゲット種類内の全エントリについての管理者権限。例えば、ドメインでのアカウント作成権限であるグローバルACLに、ACEを追加できます。

この権限が付与されている「委任された管理者」のアカウントは、システム内の全ドメインでアカウント作成ができます。

|サーバー |
サーバーエントリ

|Zimlet |
Zimletエントリ

|=======================================================================

== 権限

権限とは、「委任された管理者」が、名づけられているターゲット上で実施可能・不可能な機能のことです。権限には、システム定義権限と属性権限があります。

=== システム定義権限

システム定義権限の種類

* Presetの権限 (*初期設定の権限*)。例えば、 `createAccount` はアカウントの作成で、
`renameDomain` はドメインのリネームです。
+
Presetの権限は固定のターゲット種類に紐づきます。例えば、`createAccount` はドメイン上のみの権限、`renameAccount` はアカウント上での権限、`getServer` はサーバー上での権限です。

+
管理者がターゲット上でアクションを実行するのに必要な設定は他にありません。
+
Presetの権限には、複数ターゲットへのアクセスを伴うものもあります。被譲与者は、関連する全てのターゲット上で、適当な権限が必要です。例えば、アカウントのエイリアス作成には、アカウントにエイリアスを追加する権限と、ドメインにエイリアスを作成する権限がなければなりません。

=== 属性権限

属性権限の付与により、「委任された管理者」/管理グループは、ターゲット上での特定の属性を編集・閲覧が可能（または不可能）になります。

属性権限の種類

* Attribute (`setAttrs`) の権限で、ドメイン管理者は、属性値の閲覧・編集ができます。例えば、 `modifyAccount` の権限で、ドメイン管理者はそのアカウントのすべての属性を編集できます。

* Get attribute rights (`getAttrs`) の権限で、ドメイン管理者は属性値の閲覧ができます。例えば、`getAccount` の権限は、ユーザーアカウントのすべての属性値を表示します。

権限が付与されている属性の場合、ターゲット上に設定されています。また、読み込み(get)や書き込み(set)という権限の種類も特定されています。

属性権限は、権限の許可と拒否が設定されている、複数の属性の組み合わせで付与されている場合があります。これにより、許可の属性を拒否にすることができます。

==== Comboの権限

どんなターゲット種類でもComboの権限に指定でき、presetの権限と属性権限の両方をComboの権限に入れることができます。Comboの権限を利用して、即座に複数の属性をターゲット上で付与できます。

==== 拒否の権限

権限には、許可と拒否があります。拒否の権限とは、被譲与者への付与が否定されている権限です。

* 管理グループに拒否の権限が設定されると、そのグループ内のすべての管理者は、その権限が設定されているターゲットとサブターゲット上でのその権限が否定されます。

* ある管理者が管理グループに属していてもいなくても、その管理者に拒否の権限が設定されると、その管理者は、その権限が設定されているターゲットとサブターゲット上でのその権限が否定されます。

ある管理グループに、Domain1上でのアカウント作成権限も含む、ドメイン管理者権限が付与されています。この管理グループに属するAdminAに、アカウント作成権限を除いたドメイン管理者の全権限を持たせたいとします。その場合、ターゲットDomain1上での 拒否の `createAccount` 権限をAdminAに付与します。

同じレベルでの付与では、拒否の権限が常に優先されます。例えば、あるドメイン上でのアカウント閲覧権限が許可されているAdminGroup1。対して、同じドメイン上でのアカウント閲覧権限が拒否されているAdminGroup2。AdminAは両方のグループのメンバーです。このとき、AdminAはこのドメイン内のどのアカウントも閲覧できません。拒否の権限が優先されるからです。

異なるレベルでの付与では、最も細かい権限が優先されます。例えば、User1もメンバーであるGroupDistributionList1内のアカウント閲覧の拒否の権限が、AdminAに付与されています。また、直接User1のアカウント上で、アカウント閲覧の許可の権限が、AdminAに付与されています。このとき、AdminAはUser1のアカウントを閲覧できます。「ターゲット」アカウント上での付与は、配布リスト上での付与に比べて細かいからです。

=== 権限リストの使用

システム権限とその説明は、管理コンソールの権限フォルダの概要ペインにリストアップされています。この権限フォルダを利用すれば、どのシステム定義権限を「委任された管理者」に付与するかを定義できます。このフォルダには、権限名、紐づくターゲット種類、権限の種類、簡易説明が表示されます。

ページ上の権限を選択・クリックすると、別ページに詳細が表示されます。

* Comboの権限では、Comboの権限に紐づく権限がリストアップされます。

* 他の種類の権限では、権限に紐づく属性がリストアップされます。

`zmprov` のコマンドを使用してcomboの権限を確認できます。

* Comboの権限の直接のサブ権限を確認します。
+
[source,bash]
----
zmprov gr adminConsoleDLRights
----

* Comboの第２レベルのサブ権限を確認します。
+
[source,bash]
----
zmprov gr adminConsoleDLRights -e
----

*システム定義権限のリストを閲覧する*

`zmprov` コマンドを使用して特定のトピック用のシステム定義権限を確認できます:

.zmprovを使用してコンボの権限を表示
[cols="a,a",options="header",]
|=======================================================================
|表示対象 | 使用する `zmprov` コマンド

|アカウント |
zmprov gar -t account

|カレンダーリソース |
zmprov gar -t calresource

|提供サービス(COS) |
zmprov gar -t cos

|配布リスト footnote:[アカウントやカレンダーリソース向けの権限はすべて、「ターゲット」配布リスト上でも付与できます。配布リスト上でこうした権限が付与されると、そのACEは、その配布リストの直接のメンバーまたは間接のメンバーである、全アカウントと全カレンダーリソースに、その権限を適用します。] |
zmprov gar -t dl

|ドメイン |
zmprov gar -t domain

|グローバル設定 footnote:[アカウントやカレンダーリソース、そして配布リスト向けの権限はすべて、「ターゲット」ドメイン上でも付与できます。ドメイン上で権限が付与されると、そのACEは、そのドメイン内の直接のメンバーまたは間接のメンバーである、全アカウントと全カレンダーリソース、全配布リストに、その権限を適用します。] |
zmprov gar -t config

|グローバル付与 footnote:[グローバルを除く全ターゲット向けの全権限を「ターゲット」グローバルで付与できます。グローバル付与エントリ上で権限が付与されると、そのACEはシステム上の全エントリにその権限を適用します。例えば(ドメイン向けの権限である)createAccountをグローバル付与エントリ上でAdminAに付与すると、AdminAはそのシステム上の全ドメインでアカウント作成ができます。] |
zmprov gar -t global

|サーバー |
zmprov gar -t server

|Zimlet |
zmprov gar -t zimlet

|=======================================================================

== 管理権限の委任を実行する

「委任された管理者」アカウントの作成と権限の付与は、その管理者の役割と、その管理者が管理することになるターゲットに指定する権限を定義してから実施します。

「委任された管理者」を更に効果的に管理するには、管理グループを作成して、そのグループに個々の管理者アカウントを追加します。管理グループにより、アクセス制御を役割ベースで作成できます。同じまたはほぼ同じ役割のある管理者たちを１つの管理グループにまとめられます。

管理権限は、下記のいずれの方法からでも委任できます。

* 管理ウィザードを使用して、管理者または管理グループを作成し、そのアカウントに権限を付与します。

* 既存の管理者アカウントに権限を付与します。既存の「委任された管理者」アカウントまたは管理グループのアカウントに、新規・既存の権限を追加・修正します。

* ターゲットのACLページから直接、権限を追加・編集・削除します。

=== 管理者と管理グループ

管理者と管理グループのアカウントは管理コンソールで作成します。

管理ウィザードの使用目的

.  管理グループあるいは管理者アカウントを作成します。

.. *管理グループ* は、管理グループを有効化した配布リスト(DL)です。この有効化が「委任された管理者」のDLであるというフラグです。管理グループの管理者を作成して、権限と管理ビューを設定した後に、その管理者のユーザーアカウントを管理グループに追加します。

.. *管理者アカウント* は、アカウント上の管理者を有効化したユーザーアカウントです。

. アカウントの管理ビューを設定します。ビューは「直接割り当てられた管理ビュー」一覧から選択します。管理ビューとは、「委任された管理者」の管理コンソールへのログイン時に表示される項目のことです。
+
「直接割り当てられた管理ビュー」とは、管理者アカウント上に設定されているビューです。「継承した管理ビュー」とは、アカウントが所属する管理グループ上に設定されているビューです。

. *許可を設定します。* 「デフォルトの許可を設定」画面の権限一覧は、「直接割り当てられた管理ビュー」カラムで選択した項目の表示に必要です。これら権限を承認して新しい権限を追加するなら「次へ」、権限を設定したくないならページを「スキップ」、権限を承認してウィザードを閉じるなら *完了* を選びます。

=== 管理者アカウントや管理グループへ権限を付与する

システム管理者は、管理者や管理グループに付与されている権限を、アカウントのツールバーにある「許可を設定」のリンクから管理できます。管理にあるアカウントのアドレスのツールバーで *許可を設定* をクリックすると、直接許可のリストと継承許可のリストが内容ペインに表示されます。既存の管理者アカウント上で、権限の追加・編集・削除ができます。

=== ターゲットにACLを付与する

特定の被譲与者や特定の権限をターゲット上で追加したいとき、直接、ターゲットを編集できます。ターゲットごとにACLページという、許可されたACL一覧のページがあります。ターゲットの権限の追加・編集・削除ができます。管理者アカウント(被譲与者)は、この変更の反映のため、更新されます。

== 権限の取り消し

グローバル管理者(システム管理者)は、管理者に付与された権限を取り消せます。

管理コンソール: ::
*ホーム > 管理 > アカウント*

対象としたい管理者のアカウント開き、ギアアイコンの *許可を設定* をクリックします。

. 取消対象の _権限_ をクリックし、*削除* をクリックします。
. 確認画面で *はい* をクリックします。

「委任された管理者」が権限を取り消しできるのは、その権限がオプション *他の管理者に権限を与えることが可能* を有効にして作成された場合です。

=== 付与された管理権限を一時的に取り消す

「委任された管理者」アカウントの権限を一時的に取り消す場合、対象の管理者のアカウントで、全般情報にある「管理者」のチェックを外す編集をします。ACLはアカウントから削除されません。

== 管理者へ付与された権限を閲覧する

管理者アカウントや管理グループのアカウントからギアアイコンの「権限を表示」を選択すると、付与されている権限、特定のターゲットに紐づく読み込み可の属性とその書き込み可の属性が表示されます。様々なターゲット向けの権限を確認するには、各タブをクリックします。

== 定義済みの委任管理の役割

以下の定義済み「委任された管理グループ」は自動で作成されます。これらグループに管理者アカウントを割り当てることができます。

=== ドメインの管理グループ

`zimbradomainadmins` という「委任された管理」グループは、アカウント、エイリアス、配布リスト、リソースについて、{product-name} のドメインの管理のサポートに必要な全ての権限を付与します。

「委任された管理グループ」`zimbradomainadmins` に入っている管理者は、アカウントの作成と、アカウント容量・エイリアス・配布リスト・リソースアカウントの設定を含めたアカウント管理ができます。

ドメイン管理者が管理コンソールにログインすると、彼らによる管理が認められている機能しかナビゲーションペインに表示されません。

==== Zimbraウェブクライアントから管理コンソールへのリンクを作成する

ドメイン管理者の場合、すべてのタスクは管理コンソール上で行われます。ログインを容易にするため、「委任された管理者」アカウントの作成時に、彼らのZWCアカウントに管理コンソールへのリンクを設置できます。

管理コンソールへのリンクは `zmprov` のコマンドで作成します。
[source,bash]
----
zmprov md {server.example.com} zimbraWebClientAdminReference {https://server.example.com:7071/}
----

=== 配布リストの管理グループ

`zimbradladmin` という「委任された管理グループ」は、管理コンソールへのログインと配布リストの管理に必要となる全ての権限を 付与します。

この管理グループに入っている管理者が実施できること

* アカウントリストの閲覧
* 配布リストの新規作成、配布リストの削除
* 配布リスト内メンバーの追加・編集・削除

== 「委任された管理者」の役割を作成する

=== 複数ドメインの管理

一人のドメイン管理者に複数のドメインを管理させるには、個々のドメインを管理する権限を管理者アカウントあるいは管理グループに付与します。

例えば、 ドメイン domainexample1.com と ドメイン domainexample2.com を domanadministrator1@example.com に管理させるには、管理されるドメインの１つに新たな管理者アカウントを作成します。

. 管理するドメインの１つに(domainexample1.com)管理者アカウントを作成します。

. ドメイン管理者がドメインの管理に必要となるビューを選択します。ビューが選択されているとき、こうしたビューに紐づく権限が自動的に「デフォルトの許可を設定」画面に表示されます。

. 選択したビューに紐づく許可とは違う許可が必要であれば、このドメインの「追加の許可を設定」します。

. 管理されるもう一つのドメイン(domainexample2.com)に以下を追加します。
+
* 「追加の許可を設定」画面にて、 *追加* をクリックします。
* ターゲット種類に、 *domain* を選択します。
* ターゲット名に、対象ドメイン名(domainexample2.com)を入力します。
* 権限の種類に、システム定義権限を選択します。
* 権限名に、adminConsoleAccountRightsを入力します。 *肯定的権限ですか(許可)*
のオプションが選択していることを確認します。
* *追加/その他* をクリックします。
* 権限名が空白の *ACEを追加* 画面が再表示されます。*adminConsoleDLRights* を入力し、 *追加/その他* をクリックします。
* 上記の手順を次の権限名について繰り返します。
** *adminConsoleAliasRights*
** *adminConsoleResourceRights*
** *adminConsoleSavedSearchRights*
** *adminConsoleDomainRights*
* 上記の権限をすべて追加したら、 *追加/完了* をクリックします。 *追加の許可を設定* 画面に、「ターゲット」ドメインに紐づくこれらの権限が表示されます。管理されるドメインを他にも追加するなら、 *追加/その他* をクリックし、手順4から繰り返します。それ以外の場合、 *完了* をクリックします。

=== 配布リストの管理

配布リストを管理するユーザーを割り当てるには、配布リストの作成とその管理グループの有効化、ビューの選択、配布リストの権限付与、そのリストへのユーザー追加、そのユーザーの管理者設定、が必要です。

. 新規に配布リストを作成します。
+
*  *管理グループ* のオプションにチェックを入れます。
* 配布リストを管理するユーザーをメンバーとして追加します。
* 管理者の *管理ビュー* ページへ遷移し、 管理者が配布リストを閲覧できるように *配布リストビュー* にチェックを入れます。
* 右上の *保存* をクリックします。

. 管理者の *許可を設定* ページを開き、以下の権限を追加します。
+
.権限
[cols="1m,1,1,1",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類
4+|以下の権限名を持つ役割で、管理者は配布リストを管理できます。

|listDistributionList |dl |DLのメールアドレス |SD Right

|addDistributionListAlias |dl |DLのメールアドレス |SD Right

|addDistributionListMember |dl |DLのメールアドレス |SD Right

|modifyDistributionList |dl |DLのメールアドレス |SD Right

|getDistributionListMembership |dl |DLのメールアドレス |SD Right

|removeDistributionListMember |dl |DLのメールアドレス |SD Right

4+|このドメイン権限で、ユーザーのアカウントリストが表示されます。管理者が配布リストに追加するアカウントは、このアカウントリストから選択できます。

|listAccount |domain |配布リストのメールアドレス |SD Right

|=======================================================================


=== パスワードを変更する

パスワード変更のみの「委任された管理者」を作成するには、管理者あるいは管理グループを作成し、管理ビューを選択し、Combo権限「setAccountPassword」を付与します。

. 以下のビューを選択します。
* *アカウントリストビュー* パスワードを変更するアカウントの選択ができます。
* *エイリアスリストビュー* アカウント名の代わりにエイリアスを使用しているユーザーを検索できます。

. 「許可の設定」ページには、選択してある管理ビュー向けの権限が推奨で表示されます。パスワード変更権限の場合、これら権限は設定しません。 *スキップ* を選択します。 *追加* をクリックして下記権限を追加します。
+
[cols="1m,1,1,1",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|setAccountPassword |domain |ドメイン名 |SD Right

|=======================================================================

=== “メールを表示”へのアクセス権限

“メールを表示”へのアクセス権限は、アカウント、ドメイン、配布リスト上で付与できます。

[cols="1m,1,1,1a",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|adminLoginAs |
account, domain, dl|
アカウント名、ドメイン名、または配布リストのメールアドレス|
SD Right footnote:[ターゲット上での“メールを表示”権限を否定するには、 *否定的権限(拒否)* を選択します。]

|=======================================================================

管理者からドメインや配布リストにいるアカウントを閲覧できないようにするには、そのアカウントに *否定的権限(拒否)* を設定します。


=== ユーザーに割り当てられている提供サービスの管理

ユーザーに割り当てられている提供サービス(COS)の閲覧と変更ができるように、ドメイン管理者の役割を拡大できます。ドメインのCOSを管理する権限を登録するには、以下の権限をドメイン管理者アカウントあるいはドメイン管理グループに追加します。

システム定義権限をドメインにある各COSに追加します。

.提供サービスのシステム定義権限
[cols="1m,1,1,1",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|listCos |cos |COS name |SD Right

|getCos |cos |COS name |SD Right

|assignCos |cos |COS name |SD Right

4+|このドメイン権限で、ユーザーアカウントの全般情報に提供サービス情報が表示されます。

|zimbraCOSId |domain |ドメイン名 |
Attribute Right +
Verb: *Write* +
AR Target: *account*

|=======================================================================

=== メールボックスのクロス検索の管理

以下の権限名を持つ役割で、アカウントの現在およびアーカイブ内のメール検索を実行する「委任された管理者」の役割を作成します。管理者はメールボックスのクロス検索リクエストの作成・中止・削除・パージ・ステータス確認もできます。

[NOTE]
この機能を使用するには、アーカイブとディスカバリ機能がインストールされていなければなりません。

[cols="1m,1,1,1",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|adminConsoleCrossMailboxSearchRights |
(combo) |
メールボックスのクロス検索が実行されるサーバー名
 |
SD Right

|=======================================================================

全機能の利用のため、この役割にはアカウント作成機能も含まれています。管理者が検索結果を受け取るターゲットメールボックスを作成できるようにするためです。この役割にアカウント作成機能を持たせたくない場合は、以下の否定的権限も付与します。

[cols="1m,1,1,1a",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|CreateAccount |
domain |
ドメイン名 |
SD Right footnote:[ターゲット上でのアカウント作成権限を否定するには、 *否定的権限(拒否)* を選択します。]

|=======================================================================

メールボックスのクロス検索結果の入ったターゲットメールボックスを管理者に閲覧させたい場合、そのメールボックスだけを閲覧できる権限を付与します。

[cols="1m,1,1,1a",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|adminLoginAs |
account |
メールボックスのクロス検索のターゲットアカウント名 |
SD Right footnote:[ターゲット上での“メールを表示”権限を否定するには、 *否定的権限(拒否)* を選択します。]

|=======================================================================

=== Zimletを管理する

以下の権限名を持つ役割で、Zimletの作成・配備・閲覧ができる「委任された管理者」の役割を作成できます。

[cols="1m,1,1,1",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|adminConsoleZimletRights |
server, domain |
サーバ名またはドメイン名 |
SD Right

|adminConsoleAccountsZimletsTabRights |
server, domain |
サーバ名またはドメイン名 |
SD Right

|=======================================================================

=== リソースを管理する

以下の権限名を持つ役割で「委任された管理者」はリソース作成・管理ができます。

[cols="1m,1,1,1",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|adminConsoleResourceRights |
combo |
サーバ名、またはドメイン名 |
SD Right

|=======================================================================

=== 保存された検索へのアクセス

以下の権限名を持つ役割で「委任された管理者」は管理コンソールのナビゲーションペインにある検索セクションに保存された全ての検索クエリにアクセスできます。

[cols="1m,1,1,1",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|adminConsoleSavedSearchRights |
combo |
サーバ名、またはドメイン名 |
SD Right

|=======================================================================

=== サーバーのステータスページへのアクセス

以下の権限名を持つ役割で「委任された管理者」はサーバーのステータスページを閲覧できます。この権限の付与だけでなく、管理ビューの *グローバルサーバーステータスビュー* も選択する必要があります。

[cols="1m,1,1,1",options="header",]
|=======================================================================
|権限名 |ターゲット種類 |ターゲット |権限の種類

|adminConsoleServerStatusRights |
global ||
SD Right

|=======================================================================

[NOTE]
グローバル管理者アカウントとして設定されているアカウントにはACLを付与できません。グローバル管理者アカウントは、自動的にZCS上の全権限を保持しています。グローバル管理者アカウントにACLが追加されたとしても、無視されます。「委任された管理者」アカウントがグローバル管理者アカウントへと変更されたら、そのアカウントに紐付いているACLはすべて無視されることになります。
