[glossary]
= 用語集

この用語集には、本書で使用している用語と略語をリストトアップしています。また、業界用語と本アプリケーションの用語の両方を対象としています。一般的な業界のプラクティスやコンセプトが本製品に固有の方法で実装されている場合は、そのことも記載します。

[glossary]
A レコード::
    A (アドレス) レコードは、ホスト名を数字のIPアドレスにマッピングします。Zimbraの場合、AレコードはZimbraサーバーのIPアドレスになります。

ABQ::
    NG モジュールで提供してる Allow/Block/Quarantine 機能では、システムの管理者が ActiveSync 経由で同期することが許可しているデバイスを管理できます。

アカウントのポリシー::
    Zimbra管理コンソール内で「提供サービス」として利用されています。

AD::
    Microsoft アクティブ・ディレクトリ・サーバー(Active Directory Server)の省略です。{product-name}でOpenLDAPに加えて、ユーザー認証とGALのオプションとして使用することが可能です。

エイリアス::
    "`別名`" のメールアドレスであり、異なるメールアドレスを使うユーザーへ転送されます。

属性::
    ディレクトリサーバーエントリ用のオブジェクト関連データが含まれています。属性にはサーバーのホスト名やメールの転送先アドレスなどが保存されています。

認証::
    システムへアクセスするユーザーの権限を検証するために使う、ユーザーの入力したログイン情報を処理する方法です。

ブラックリスト::
    迷惑メール対策の用語で、既知の悪質なIPアドレスを示します。迷惑メール送信者が乗っ取ったIPアドレスである可能性もあります。または合法であるけれども維持管理が乏しいために認証されていないユーザーからのメッセージもリレーできるようなIPアドレスである可能性もあります。

BLOB::
    バイナリ・ラージ(大きい)・オブジェクト(Binary Large OBject)の省略です。

提供サービス (COS)::
    アカウントのメールボックス割り当て容量などの設定が含まれる{product-name}  LDAPスキーマにあるオブジェクトです。各{product-name} アカウントにはCOSが１つ適用され、そのアカウントは、適用されているCOSからすべての設定を継承します。

CLI::
    コマンド・ライン・インターフェース(Command-Line Interface)の省略です。zmprovなどの{product-name}のコマンド・ラインツールの集合体について言及する際に使用されます。

クラスタ::
    複数のサーバー(ノード)を使用している、可用性の高いネットワーク構成の一種です。サーバー１つが停止あるいはネットワークから外れた場合に、代替サーバーが引き継ぎます。

連絡先::
    {product-name}上では、連絡先とはユーザーインターフェースの１機能で、ユーザーの個人的な住所や連絡先情報を集めて一覧にしたものです。

スレッド::
    {product-name}上では、スレッドとはユーザーインターフェースの１機能で、メールのスレッド(同じ件名を使用しているメッセージ)を１つのスレッドリストとして表したものです。ユーザーは、スレッドを展開することで、それに含まれるメッセージをすべて閲覧することができます。

DHTML::
    ダイナミックHTML(Dynamic HTML)の省略です。Zimbraウェブクライアントで使用されている技術の一つです。

DNS::
    ドメイン・ネーム・システム(Domain Name System)とは、インターネットのディレクトリサービスです。DNSとは、ドメイン名がIPアドレスへ変換する方法であり、メール配信の制御も行ないます。Postfixがリモートの宛先へ正常にメッセージを送信するには、正しく設定されたDNSが必要です。

エッジMTA::
    受信メールのトラフィックを最前線で防御するメール配信エージェント(MTA)を指す一般用語です。エッジMTAに備わっている機能に、迷惑メールのフィルターリングなどがあります。

エントリ::
    ディレクトリサーバーにあるアイテム、例えばアカウントやメールホストです。

エフェメラルデータ::
    短命、あるいは即座に変化する性質のデータ。ログインのタイムスタンプや認証トークンなど。

フェールオーバー::
    メインサーバーが利用できないことを代替サーバーが検知して、メインサーバーに変わって代替サーバーが処理を行なう一連の引き継ぎ処理のこと。

FQDN::
    完全修飾ドメイン名を意味する「Fully Qualified Domain Name」の省略です。ホスト名とホストへのパスです。例えば、www.zimbra.comは完全修飾ドメイン名です。wwwはホスト、zimbraはセカンダリレベルのドメイン、そしてcomがトップレベルのドメインとなります。

GAL::
    グローバル・アドレス・リスト(Global Address List)の省略です。会社ディレクトリのOutlook版です。組織内の全従業員分のメールアドレスを含む連絡先のリストです。

グローバル設定::
    サーバーと提供サービスのデフォルト設定を保存している{product-name} のオブジェクトです。

高可用性::
    HAと省略されます。高可用性とは、システム内のコンポーネントの障害の後でもそのコンピュータシステム内で使用できるリソースを示しています。

HTTP::
    ハイパーテキスト・トランスファー・プロトコル(HyperText Transfer Protocol)の省略です。UIの統合のため、SOAPと共に利用されます。

IMAP::
    インターネット・メッセージ・アクセス・プロトコル(Internet Message Access Protocol)の省略です。ユーザーがローカルでの作業のように、リモートのメッセージストアのメールにアクセスできる方法です。

ストア::

    {product-name}内にある、特定のメールボックスサーバーのメールメッセージの全インデックス情報を保存するディレクトリです。

インデックス化::
    検索キーワードについて受信メールメッセージを解析するプロセスです。

Java::
    Javaは業界で使用されているオブジェクトベースのプログラミング言語です。Javaはコアの{product-name}アプリケーションサーバーに使用されています。

JavaScript::
    主にNetscapeで開発された、HTMLのソースコードと共に使用できるスクリプトです。この技術はZimbraウェブクライアントに使用されています。

LDAP::
    ライトウェイト・ディレクトリ・アクセス・プロトコル(Lightweight Directory Access Protocol)の省略です。業界標準で認証に使用されているプロトコルです。

Zimbra管理コンソール::
    {product-name} の管理者インターフェースです。

Zimbraウェブクライアント::
    {product-name} のエンドユーザーインターフェースです。

LMTP::
    ローカル・メール・トランスファー・プロトコル(Local Mail Transfer Protocol)の省略です。 最後の配信で、Postfix MTAから {product-name} サーバーへメッセージを送信する際に使用します。

メールボックスサーバー::
    {product-name} サーバーの代替名

MAPI::
    メッセージング・アプリケーション・プログラミング・インターフェース(Messaging Application Programming Interface)の省略です。異なる電子メールアプリケーションと共に実行できるようにMicrosoft Windowsへ組み込んだシステムです。

メッセージストア::
    {product-name}内にある、特定のメールボックスサーバーのメールメッセージを保存するディレクトリエリアです。

MDA::
    メール・デリバリー・エージェント(Mail Delivery Agent)の省略で、「メールホスト」とも呼ばれます。{product-name}サーバーはMDAとして機能します。

メタデータ::
    データの実際の内容を説明せずにそのデータを説明するためのデータです。{product-name}内ではメタデータには、ユーザーのフォルダ、スレッド、メッセージ件名やタグ、ポインターが含まれています。

MIME::
    マルティパーパス・インターネット・メール・エクステンション(Multipurpose Internet Mail Extensions)の省略で、イメージファイル、などの非ASCIIのインターネットメッセージ内容をフォーマット化する技術仕様です。 メッセージストアにメッセージを保存するフォーマットです。

MTA::
    メッセージ・トランスファー・エージェント(Message Transfer Agent)の省略です。MTAは、マシン間でメールを送り届けるプログラムです。 {product-name}のシステムでは、PostfixのMTAとエッジMTAの両方を想定しています。

MXレコード::
    メール・エクスチェンジ(Mail eXchange)の省略です。MXレコードはドメイン名データベースのエントリです。このエントリにより、該当のドメイン名のメールの処理を行なう担当のメールサーバーが識別できます。メールシステムは、ドメイン間でのメッセージ送信を行なうのに、DNSのMXレコードに依存しています。メールを処理する際、受信先アドレスのAレコードを確認する前にMXレコードが確認されます。

OOTO::

    「不在にしています」(Out Of The Office)のよくある省略です。不在メッセージ送信時に使用されます。

オープンソース::

    非営利的な配信を目的としたユーザーグループが作成したソフトウェアです。ソースコードは所有されずに公開されています。

OS::
    オペレーティング・システム(Operating System)の省略です。Linux, UNIX, Microsoft Windows、などはOSの一例です

POP::
    ポスト・オフィス・プロトコル(Post Office Protocol)の省略です。電子メールをTCP/IPでリモートのサーバーから取得し、ローカルのコンピュータへ保存します。

プロビジョニング::
    バッチやその他の自動化された方法によって、アカウントやその他のデータを作成する処理です。

RBH::
    リアル・タイム・ブラックホール(Real-time Black Hole)の省略です。公開サービスとして、良くない送信元IPアドレスのリストを提供しているウェブサイトです。これらIPアドレスは、迷惑メールの送信者として知られているサーバーか、安全でないまたは迷惑メール送信者に悪用されているサーバーであるため、ここからのメールは拒否するべきアドレスとしてリストアップされています。

Redoログ::
    再実行とレプリケーションに使用する {product-name} serverの詳細なトランザクションログです。

SAN::
    ストレージ・アレー・ネットワーク(Storage Array Network)の省略です。高可用性のデータストレージエリアです。

スキーマ::
    特定の管理サイトのディレクトリサービスで使用中のデータ構造を指します。

SMTP::
    シンプル・メール・トランスファー・プロトコル(Simple Mail Transfer Protocol)の省略です。 {product-name}
    のシステムではエッジMTAとPostfix MTAの間で使用されます。

SNMP::
    シンプル・ネットワーク・モニタリング・プロトコル(Simple Network Monitoring Protocol)の省略です。システムログから重要なエラーを取り出すために監視ソフトウェアで使用しています。

SOAP::
    シンプル・オブジェクト・アクセス・プロトコル(Simple Object Access Protocol)の省略で、ウェブサービスのリクエストの送信に使用する、XMLベースのメッセージングプロトコルです。 {product-name}サーバーではリクエスト送受信にSOAPを使用しています。このリクエストは {product-name}のコマンドラインツールまたは {product-name}のユーザーインターフェースから送られます。

迷惑メール(スパム)::

    求められていない商用メールです。迷惑メール送信者はこれを "`一括送信のビジネスメール`" と呼んでいます。

SQL::
    ストラクチャー・クエリー・ランゲージ(Structured Query Language)の省略です。メッセージストア内のメッセージを検索するために使用します。

SSL::
    セキュア・ソケット・レイヤー(Secure Sockets Layer)の省略です。


タグ::
    Zimbraウェブクライアントの機能です。ユーザーはタグを作成してメールメッセージに検索用に適用することができます。

TCO::
    総保有コストを意味する「トータル・コスト・オブ・オーナーシープ」(Total Cost of Ownership)の省略です。{product-name}は必要なサーバーのハードウェア、OSのライセンス手数料、サポートのアプリケーション手数料、必要なディスク容量および社員(IT、ヘルプデスク、コンサルティング、など)を減らすことで、総保有コスト(TCO)を削減します。


TLS::
    トランスポート・レイヤー・セキュリティ(Transport Layer Security)の省略です。

UCE::
    求められていない商用メールを意味する「アンソリシテット・コマーシャル・メール」(Unsolicited commercial email)の省略で、迷惑メールやスパムとも呼ばれます。

仮想エイリアス::
    Postfix MTA内で認識されるメールエイリアスの一つです。

ホワイトリスト::
    信頼できるメールやIPアドレスのための、迷惑メール対策の専門用語です。信頼できるアドレスから受信したメールは "自動的に信頼"できる場合が多いです。

XML::
    エクステンデッド・マークアップ・ランゲージ(eXtended Markup Language)の省略です。
