[[introduction]]
= はじめに

{product-name} は電子メール、アドレス帳、カレンダー、タスクおよびウェブドキュメント編集の機能をすべて兼ね備えた、メッセージングとコラボレーションのソリューションです。

== 対象読者

本ガイドは、{product-name}のサーバー環境のインストール、保守、サポートを担当するシステム管理者向けに作成しています。

本ガイドの適切な利用には、次の知識やスキルが必要です。

* Linuxオペレーティングシテム関連の技術、オープンソースのコンセプトに関する知識
* メールシステム管理に関する運用知識

== サードパーティ製のコンポーネントについて

バックアップ管理、ユーザー認証、オペレーティングシステムおよびデータベース管理に関し、{product-name}は標準規格やオープンソースの推進を可能な範囲において遵守します。ただし、「製品の概略」章で紹介している、正規のテストで証明された使用方法に限り、サポートします。本ガイドに参考程度に記載している箇所はありますが、{product-name}では、他のサードパーティ製のツールのサポートや認証はいたしません。

== サポートと連絡情報

https://www.zimbra.com[*www.zimbra.com*] から、オープンソースメッセージングのベストソリューションのコミュニティーに参加できます。皆様からのフィードバックや製品への要望をお待ちしております。

* {product-name} の購入に関しては、sales@zimbra.comまでご連絡ください。
* ネットワーク版をご利用のお客様に対するサポートに関しては、support@zimbra.comまでご連絡ください。
* https://forums.zimbra.org/[Zimbra のフォーラム] から、インストールや設定についての問題解決に関する情報を確認できます。
* https://forums.zimbra.org/[Zimbra のフォーラム]に参加すると、 {product-name} に関する情報を他のユーザーと共有できます。

製品関連の詳細については、以下からご覧ください。

* https://wiki.zimbra.com[Zimbra Wiki]
* https://wiki.zimbra.com/wiki/Security_Center[Security Center]

製品に対する疑問やご希望される機能追加については、Zimbraのフォーラムに投稿し、お知らせください。
