= ライセンス
:toc:

アカウントの作成にはZimbraライセンスが必要です。Zimbraのライセンスの購入、更新、変更時は、その最新のライセンス情報にてZimbraサーバーを更新します。

== ライセンスの種類

{product-name} のライセンス機能により管理者は、配備予定のライセンスを見た目に分かりやすく制御できます。なお、以下のライセンスされた機能の監視や管理は可能となっています。

[cols="25,75",options="header",grid="rows"]
|=======================================================================
| ライセンス上限 |以下の上限を設定

|アカウント上限 |
作成可能アカウント数と作成済みアカウント数が表示されます。

|MAPIアカウント上限 |
Microsoft Outlook(ZCO)用Zimbraコネクタを使用できるアカウント数。

|Exchange ウェブサービス(EWS) のアカウント上限 |
Exchangeサーバーへの接続にEWSを使用できるアカウント数。EWSはライセンス対象のアドオン機能です。

|ハイファイなドキュメントプレビュー |
ハイファイなドキュメントプレビューを使用できるアカウント数。LibreOfficeをインストールする必要があります。

|アーカイブ用アカウント上限 |
作成可能アーカイブ用アカウント数。アーカイブ機能をインストールする必要があります。

|=======================================================================

== 提供しているライセンスの種類

{product-name}の試用版を無料で入手できます。本番環境にインストール後は、サブスクリプションまたはパーペチャルの購入が必要なります。

[cols="25,75",options="header",grid="rows"]
|=======================================================================
|ライセンスの種類 |目的

|試用版 |
無料。Zimbraのウェブサイト(https://www.zimbra.com) から入手できる試用版。最大50ユーザーの作成が可能。最大60日間有効。

|試用延長版 |
無料。最大50ユーザーの作成が可能。期間延長可。Zimbra営業部より入手できます。sales@zimbra.com または1-972-407-0688までご連絡ください。

|サブスクリプション |
有料。特定の{product-name} システムに適用可。購入したZimbraアカウント数、使用開始日および有効期限がライセンスファイル内に暗号化されています。

|パーペチャル |
有料。サブスクリプションと同様、特定のZCSシステムシステムに適用可。購入したZimbraアカウント数、使用開始日および有効期限2099年12月31日がライセンスファイル内に暗号化されています。サポート契約を更新する場合、新しいパーペチャルライセンスは発行されませんが、システムにあるお客様のアカウントレコードはサポート終了日にて新たに更新されます。

|=======================================================================

== アカウント種類でのライセンス影響

以下に{product-name} のアカウント種類とライセンスへの影響を説明します。

[cols="25,75",options="header",grid="rows"]
|=======================================================================
|ライセンスのアカウント種類 |目的

|システムアカウント |
システムアカウントは{product-name}で使用する特別なアカウントです。迷惑メール(スパムとハム)フィルターリング用アカウント、ウイルス付きメール隔離用アカウント、ドメインにGALを設定するGALsync用アカウントなどがあります。削除しないようにご注意ください！システムアカウントはライセンスのアカウント数には含まれません。

|管理者アカウント |
管理者アカウントと管理権限委譲アカウント。ライセンスのアカウントとしてカウントされます。

|ユーザーアカウント |
ユーザーアカウントはライセンスのアカウント上限数にカウントされます。アカウントを削除すると、この変更がライセンスのアカウント上限数に反映されます。

|エイリアスアカウント .3+^.^|非該当
|配布リスト
|リソースアカウント

|=======================================================================

== ライセンスのアクティベーション

ネットワーク版の環境はすべて、ライセンスをアクティベーションする必要があります。新しい環境の場合はライセンス発行日から10日間のアクティベーション猶予期間があります。管理コンソールから実施可能です。

管理コンソール: ::
*ホーム > 設定 > グローバル設定 > ライセンス* にアクセスし、画面の右上 *ギア* アイコンの
*ライセンスのアクティベーション* を選択します。

{product-name}のアップグレード時は、ネットワーク版の機能を継続するためにただちにアクティベーションする必要があります。

=== ライセンスのアクティベーションについて

{product-name} サーバーが外部インターネットへの接続があり、かつ、Zimbraライセンスサーバーに繋がる場合、ライセンスは自動でアクティベーションされます。ライセンスが自動でアクティベーションされない場合は、
<<manual_license_activation,手動でのライセンスのアクティベーションについて>>を参照してください。

[[manual_license_activation]]
=== 手動でのライセンスのアクティベーションについて

Zimbraライセンスサーバーへ外部接続ができないシステムの場合、 https://support.zimbra.com/[Zimbraのサポートポータル]を利用すると、マニュアル操作でライセンスをアクティベーションすることができます。Zimbraのホームページ(www.zimbra.com)へアクセスし、*Support* をクリックすると、Zimbraのテクニカルサポートページが表示されます。*{product-name} Suport* をクリックすると、サポートポータルページが表示されます。メールアドレスとパスワードを入力してログインします。

サポートポータルにアクセスできない場合は、sales@zimbra.com までお問い合わせください。

=== ライセンスがインストールまたはアクティベートされていない場合

{product-name} サーバーライセンスのインストールまたはアクティベーションに失敗した場合の{product-name}サーバーへの影響は次のとおりです。

[cols="25,75",options="header",grid="rows"]
|=======================================================================
|ライセンス状態 |説明・影響

|インストールされていない |
{product-name} はシングルユーザーモードに切り替わり、全機能が１ユーザーの利用に制限されます。

|無効|
{product-name} はシングルユーザーモードへと切り替わります。

|アクティベートしていない |
ライセンスのアクティベーション猶予期間は10日間です。何かしらの理由によりライセンスがアクティベーションされない場合、 猶予期間後、{product-name} はシングルユーザーモードへと切り替わります。

|開始が未来日|
{product-name} はシングルユーザーモードです。

|猶予期間中 |
ライセンス満了日が過ぎ、30日の更新猶予期間中です。ライセンス契約していた機能はまだすべて有効ですが、ライセンスの更新警告メッセージを管理者が確認する可能性があります。

| 満了 |
ライセンス満了日が過ぎ、30日の更新猶予期間も経過しています。 {product-name} サーバーはオープンソース版の機能へと切り替わります。

|=======================================================================

== ライセンスを入手する

ZimbraのホームページにあるDownloadsから無料の試用版ライセンスを入手できます。試用延長版ライセンスやサブスクリプション、パーペチャルの入手については、Zimbraの営業部 sales@zimbra.com までお問い合わせください。

購入した{product-name} システムにのみサブスクリプションやパーペチャルのインストールが可能です。お客様の{product-name} 環境にに必要なZimbraライセンスは１つです。このライセンスには作成可能なアカウント数の上限を設定します。

購入したアカウント数、使用中アカウント数、満了日などの現ライセンス情報は
*ホーム > 設定 > グローバル設定 > ライセンス* から確認できます。

== ライセンスを管理する

管理コンソールの *グローバル設定* ページにある *ライセンスを更新* ウィザードを使用して、新しいライセンスのアップロードとインストールができます。*ライセンスのアクティベーション* を使用すると、インストールされているライセンスがアクティベーションされます。

*ホーム > 設定 > グローバル設定 > ライセンス* から、現ライセンス情報を確認できます。ライセンスID、利用開始日、満了日、購入アカウント数および使用可能アカウント数が表示されます。

=== ライセンス情報

アカウントを作成するには、 {product-name} のライセンスが必要です。ライセンスの購入、更新、変更時は、その最新のライセンス情報にてZimbraサーバーを更新する必要があります。管理コンソールのグローバル設定ページにある *ライセンスを更新ウィザード* から、新しいライセンスのアップロードとインストールができます。 *ライセンスのアクティベーション* を使用すると、インストールされているライセンスがアクティベーションされます。

*ホーム > 設定 > グローバル設定 > ライセンス* で遷移したライセンス情報ページには、ライセンスID、利用開始日、満了日、購入アカウント数および使用可能アカウント数が表示されます。

使用中のアカウント数が購入したアカウント数に達すると、アカウントの新規作成ができなくなります。作成可能なアカウント数を追加で購入するか、既存の(使用していない)アカウントを削除することで、アカウントの新規作成が可能となります。作成可能なアカウント数を追加で購入する場合は、Zimbraの営業部までご連絡ください。

Zimbraのネットワーク版の機能を中断せずに継続使用する場合、ライセンスの満了日より30日間前に更新する必要があります。なお、ライセンスが満了されるまでの30日間は管理コンソールにログインするとリマインド用通知メッセージが表示されます。

=== ライセンスの満期

{product-name} のネットワーク版のライセンスが満了した場合、管理コンソールおよびすべてのユーザーのウェブクライアントにて、ライセンスが満了された警告メッセージが表示されます。ライセンスの満了から30日間の猶予期間が発生します。猶予期間内では警告メッセージが表示されますが、すべての機能は継続して使用できます。

猶予期間を過ぎるとオープンソース版の機能へ自動的に切り替わります。ライセンスの満了後は、以下の重要な機能が使用できなくなります。

* バックアップと復元
* Exchangeウェブサービス(EWS) -- _EWSは別売りのライセンス機能です_
* ハイファイなドキュメントプレビュー
* Outlook用のZimbraコネクタ
* S/MIME

ライセンス契約したユーザー数の上限に達した場合、アカウントの作成も削除もできなくなります。

ライセンスの更新予定がない場合は、{product-name}の無料オープンソース版(FOSS)へアップグレードすることにより、アカウントの新規作成と既存アカウントの削除が可能となります。その場合、{product-name}のネットワーク版と同じバージョンのFOSS版を選択してから、最新のFOSS版へ更新されることをお勧めします。

=== 更新

使用中のアカウント数が購入したアカウント数に達すると、アカウントの新規作成ができなくなります。作成可能なアカウント数を追加で購入するか、既存の(使用していない)アカウントを削除することで、アカウントの新規作成が可能となります。作成可能なアカウント数を追加で購入する場合は、Zimbraの営業部までご連絡ください。

Zimbraのネットワーク版の機能を中断せずに継続使用する場合、ライセンスの満了日より30日間前に更新する必要があります。なお、ライセンスが満了されるまでの30日間は管理コンソールにログインするとリマインド用通知メッセージが表示されます。

== ライセンスを更新する

Zimbraのライセンスの更新、変更時は、その最新のライセンス情報にて {product-name}
メールボックスサーバーを更新してください。管理コンソールから、あるいはコマンドラインでzmlicenseコマンドを使用することで、ライセンスの更新が可能です。

[source, bash]
----
zmlicense
----

管理コンソール: ::
*ホーム > 設定 > グローバル設定 > ライセンス*

ライセンスの更新

. 管理コンソールへ接続するパソコンにZimbraのライセンスを保存します。

. 管理コンソールにログイン後、
*ホーム > 設定 > グローバル設定 > ライセンス* に遷移し、画面の右上 *ギア* アイコンにある
*ライセンスを更新* をクリックします。 ライセンス インストール ウィザードが開きます。

. 保存したライセンスファイルをブラウザで選択し、*次へ* をクリックすると、ライセンスファイルがサーバーへアップロードされます。

. *インストール* をクリックします。アップロードしたライセンスがサーバーにインストールされます。

. *ギア* アイコンにある *ライセンスのアクティベーション* をクリックします。{product-name}のアップグレード時は、ネットワーク版の機能を継続するためにただちにアクティベーションする必要があります。

ライセンスの情報が自動で更新されます。キャッシュされたアカウントライセンスの数は各メールボックスサーバーにて自動リフレッシュされます。
