= ユーザーアカウントの管理
:toc:

== ユーザーアカウントのステータス

管理コンソール: ::
*ホーム > 管理 > アカウント*

アカウントのステータスにより、ユーザーのログインとメール受信の可否が決まります。このステータスは、管理コンソールの *管理* ペインに表示されます。

.ステータス - ユーザーアカウント
[cols="1,5",options="header",]
|=======================================================================
|ステータス |説明

|アクティブ |
メールボックスアカウントの通常の状態です。メールは配信され、ユーザーはクライアントインタフェースにログインできます。

|メンテナンス |
ログイン不可で、このアカウント宛のメールは全てMTAのキューに並びます。

バックアップ中やアカウントのインポート/エクスポート/復元時、このステータスがアカウントに自動設定されることをご注意ください。

|保留 |
新規作成されたアカウントで、まだアクティブになる準備が終わっていないとき。保留中、ログイン不可で、メールはバウンスされます。

|ロック |
ログイン不可で、メールはこのアカウントに継続配信されます。メールアカウントが危険にさらされている（未認証エンティティが使用）と思わしき場合、管理者はこのロックステータスを設定できます。

|閉鎖 |
ログイン不可で、メールはバウンスされます。サーバーから削除せずに、削除済みアカウントとする場合にこのステータスが使用されます。閉鎖によるアカウントライセンスへの影響はありません。

|ロックアウト |
不正なパスワードでのログイン試行時、自動でセットされるステータスです。ロックアウトは、マニュアルでは管理者でも設定できません。設定で許容されているログイン試行回数を超えた場合にセットされます。ロックアウトの期間も設定可能です。

管理者はロックアウトのステータスをいつでも解除できます。

|=======================================================================

== アカウントを削除する

管理コンソール: ::
*ホーム > 管理 > アカウント*

管理コンソールからアカウントを削除できます。これにより、アカウントはサーバーから消去され、メッセージストアにあるメッセージが削除され、ライセンスの使用中アカウント数が変更されます。

[TIP]
アカウント削除前に、アカウントの完全バックアップを実行してアカウント情報を保存してください。バックアップの詳細は <<backup_and_restore,バックアップと復元>> の章を参照してください。

== アカウントのメールボックスを閲覧する

すべてのフォルダ、カレンダー予定およびタグを含めて、特定のアカウントのメールボックス内容をすべて管理コンソールから閲覧できます。

管理コンソール: ::
*ホーム > 管理 > アカウント -> _アカウント名_*

_アカウント名_ を選択後、*ギア* アイコンから *メールを表示* を選択します。対象ユーザーのZWCアカウントが別ウィンドウで開かれます。

この機能では、管理者とユーザーは同一アカウントに同時にログインできるため、困っているユーザーのアカウントに直接アクセスし、サポートすることができます。

アカウントにアクセスするメールを表示アクションは全て `audit.log` に記録されます。

== 電子メールのエイリアスを使用する

メールのエイリアスは、特定のメールアカウントに全メールをリダイレクトするメールアドレスです。エイリアスはメールアカウントではありません。各アカウントにいくつでもエイリアスを設定できます。

管理→エイリアスペインからエイリアスを選択時、設定されているエイリアスが全て内容ペインに表示されます。エイリアスの作成、特定のエイリアスのアカウント情報の閲覧、エイリアスの対象アカウントの変更、エイリアスの削除ができます。

== 配布リストを管理する

配布リストとは、メールアドレスの集合が共通メールアドレス内にリストアップされたものです。配布リストへの送信時、そのリスト内の全員にメッセージを送信していることになります。あて先項目には配布リストのメールアドレスが表示されます。個々の受信者のアドレスが閲覧されることはありません。

メンバーリストを管理する管理者が必要な配布リストの作成や、リストのメンバーを自動で追加・削除するダイナミック配布リストの作成ができます。ダイナミック配布リストの詳細は、
<<using_dynamic_distribution_lists,ダイナミック配布リストを使用する>> を参照してください。

ユーザーがメンバーになっている配布リストは、管理→アカウント→メンバーページから確認できます。Zimbraユーザーのメールアドレスが配布リストに追加されると、その配布リスト名がユーザーこのアカウントのメンバーページに反映されます。配布リストの削除時、このアカウントのメンバーページからその配布リスト名が消去されます。

=== 配布リストの購読ポリシーを管理する

配布リストのメンバー管理のための購読ポリシーをセットアップできます。リストのオーナーは配布リストのプロパティページから、購読ポリシーを管理できます。

[cols="1,3a",options="header",]
|=======================================================================
|オプション |詳細

|新しい購読の要求 |

* *自動的に受け入れる* -- 誰でも購読メンバーになれます。

* *リストのオーナーの承認が必要* --  ユーザーが購読するためには、配布リストのオーナーにメッセージを送信し、オーナーはそのメールの依頼に答えます。

* *自動的に拒否する* -- 誰も配布リストに追加できません。

|購読解除の要求 |

* *自動的に受け入れる* --  誰でもリストから除名できます。

* *リストのオーナーの承認が必要* -- ユーザーが配布リストからリストから除名されるには、配布リストのオーナーにメッセージを送信します。オーナーは除名のメール依頼を承認する必要があります。

* *自動的に拒否する* -- ユーザーはリストから除名できません。

|=======================================================================

=== 配布リストのオーナーが使用できる管理オプション

配布リストにオーナーを登録すると、オーバーはZWCの自身のアカウントのアドレス帳、配布リストフォルダから管理することができます。リストのオーナーは、リストの編集のために、配布リストを右クリックして *グループを編集* を選択できます。

メンバーの追加・削除のほか、オーナーが設定できる配布リストのプロパティに次のようなものがあります。

* グローバルアドレスリストに表示されないように、配布リストをプライベートとしてマーク

* リストへメッセージ送信できるユーザーを管理

* メンバーの購読ポリシーの設定

* 他のオーナーの追加

=== 配布リストを作成する

配布リストの作成は、本項の手順を参考にしてください。

管理コンソール: ::
*ホーム > 管理 > 配布リスト*

. 画面の右上にある *ギア* アイコンから *新規* をクリックします。

. *メンバー* ページで、配布リストの名前を入力します。スペースは使用できません。他の項目は任意です。

. 右側の「このリストにメンバーを追加」から、配布リストに追加するメンバーを検索します。追加するメンバーを選択して、 *選択項目を追加* をクリックします。ページに表示されたアドレス全てを追加したいなら、 *このページを追加* をクリックします。会社のリストに存在しないメンバーを追加したいなら、 *または下にアドレスを入力* 項目にメールアドレスを正確に入力します。

. *次へ* をクリックし、配布リストの *プロパティ* ページに進みます。
+
.配布リストプロパティオプション
[cols="1,3a",options="header",]
|=======================================================================
|配布リストプロパティオプション|詳細

|メール受信可 |
デフォルトで有効です。配布リストがメッセージを受信すべきでないなら、このオプションを無効にします。

|GALに表示しない |
このオプションを有効にすると配布リストがグローバルアドレスリスト(GAL)に表示されません。このオプションを利用して、配布リストのメールアドレスの存在を知るユーザーを制限できます。

|メールサーバー |
デフォルトで「自動」が設定されます。特定のメールサーバーを指定する場合、「自動」を無効にし、一覧からサーバーを特定します。

|ダイナミックグループ |
このチェックボックスを有効にすると *メンバーURL* 項目が表示されます。ダイナミック配布リストを作成します。詳細は以下の <<create_dynamic_distribution_lists,ダイナミック配布リストを使用する>> を参照してください。

|新しい購読の要求 |
以下のいずれかを選択します。

* 自動的に受け入れる
* リストのオーナーの承認が必要
* 自動的に拒否する

|購読解除の要求 |
以下のいずれかを選択します。

* 自動的に受け入れる
* リストのオーナーの承認が必要
* 自動的に拒否する

|=======================================================================

. *メンバー* ページで、配布リストを直接メンバーとするか間接メンバーとするかを選択します。

. 配布リストにエイリアスを追加すべきなら、作成します。

. 配布リストを他のユーザーにも管理させるなら、*オーナー* ページから、対象者のメールアドレスを入力します。

. 配布リストが受信するメッセージの返信方法を設定します。

. *完了* をクリックします。配布リストが有効になり、URLが作成されます。

=== 配布リストへのアクセスを管理する

配布リストの作成後は、配布リストのメンバーを閲覧できるユーザーや配布リストへメッセージ送信できるユーザーを管理できます。デフォルトでは、全ユーザーに全配布リストへのアクセス権があります。本章では、CLIから行なう配布リストへのアクセス管理について説明します。

配布リストにアクセスできるユーザーを制限するには、ドメインの個々のユーザーにアクセス権を与えます。あるいは、ドメインのユーザーにだけ配布リストへのアクセスを許可したいなら、ドメインに対するアクセス権を与えることができます。ドメインにアクセス権を与えると、ドメインにある全配布リストがその権限を継承します。

個々の配布リストに対する権限を付与すると、配布リストへのアクセスが認められる特定のユーザーを設定することができます。

配布リストへのアクセス制限はコマンドラインの
`zmprov grantRight` (`grr`) コマンドで実行可能です。

[NOTE]
権限付与についての詳細は、 <<delegated_administration,管理権限の委任>>を参照してください。

==== 配布リストのメンバーを閲覧できるユーザー

デフォルトでは、全ユーザーが配布リストのメンバーのメールアドレスを閲覧できます。配布リストのメールアドレスに、「+」が吹き出し表示されます。クリックして、配布リストを展開することができます。配布リスト内のメールアドレスが一覧表示されます。ユーザーは、この展開されたリストから、個々のアドレスを選択できます。

個別のユーザーやドメインに、配布リスト内のメールアドレス閲覧を制限します。
--
* 個別のユーザー
+
[source,bash]
----
zmprov grr domain <ドメイン名> usr <アドレス@ドメイン> viewDistList
----

* ドメイン内全ユーザー
+
[source,bash]
----
zmprov grr domain <ドメイン名> dom <example.com> viewDistList
----

* 配布リストに権限を付与し、特定のユーザーにリストを閲覧させる
+
[source,bash]
----
zmprov grr dl <dll_name@example.com> usr <アドレス@ドメイン>
----
--

==== 配布リストへメッセージ送信できるユーザー

デフォルトでは、すべてのユーザーがすべての配布リストにメッセージ送信できます。誰が配布リストにメッセージを送れるかを定義するために、ドメインや配布リストに権限を付与できます。使用する権限のない配布リストにメッセージを送信しようとすると、あて先の配布リストへメッセージを送信する権限がない旨を伝えるメッセージが送信されます。

[NOTE]
*ホーム > 設定 > グローバル設定 > MTA* にある *Milterサーバー* は有効でなければなりません。

個別のユーザーやドメインに、配布リストへのメッセージ送信を制限します。

* ドメイン内のあるユーザーのみにすべての配布リストへのメッセージ送信を許可。
+
[source,bash]
----
zmprov grr domain <ドメイン名> usr <アドレス@ドメイン> sendToDistList
----

* ドメイン内の全ユーザーにすべての配布リストへのメッセージ送信を許可。
+
[source,bash]
----
zmprov grr domain <ドメイン名> dom <example.com> sendToDistList
----

ユーザータイプによる、個々の配布リストへのアクセス許可とその解除の方法です。

* 特定の内部ユーザーにアクセスを許可。
+
[source,bash]
----
zmprov grr dl <dlname@example.com> usr <username@example.com> sendToDistList
----
+
アクセス許可を解除。
+
[source,bash]
----
zmprov rvr dl <dlname@example.com> usr <username@example.com> sendToDistList
----

* 配布リストのメンバーのみにアクセスを許可。
+
[source,bash]
----
zmprov grr dl <dlname@example.com> grp <dlname2@example.com> sendToDistList
----
+
アクセス許可を解除。
+
[source,bash]
----
zmprov rvr dl <dlname@example.com> grp <dlname2@example.com> sendToDistList
----

* ドメイン内の全ユーザーのみにアクセスを許可。
+
[source,bash]
----
zmprov grr dl <dlname@example.com> dom <example.com> sendToDistList
----
+
アクセス許可を解除。
+
[source,bash]
----
zmprov rvr dl <dlname@example.com> dom <example.com> sendToDistList
----

* 外部ドメイン内の全ユーザーのみにアクセスを許可。
+
[source,bash]
----
zmprov grr dl <dlname@example.com> edom <example.com> sendToDistList
----
+
アクセス許可を解除。
+
[source,bash]
----
zmprov rvr dl <dlname@example.com> edom <example.com> sendToDistList
----

* すべての内部ユーザーのみにアクセスを許可。
+
[source,bash]
----
zmprov grr dl <dlname@example.com> all sendToDistList
----
+
アクセス許可を解除。
+
[source,bash]
----
zmprov rvr dl <dlname@example.com> all sendToDistList
----

* すべてのパブリック電子メールアドレスにアクセスを許可。
+
[source,bash]
----
zmprov grr dl <dlname@example.com> pub sendToDistList
----
+
アクセス許可を解除。
+
[source,bash]
----
zmprov rvr dl <dlname@example.com> pub sendToDistList
----

* 特定の外部メールアドレスにアクセスを許可。
+
[source,bash]
----
zmprov grr dl <dlname@example.com> gst <someone@foo.com> "" sendToDistList
----
+
アクセス許可を解除。
+
[source,bash]
----
zmprov rvr dl <dlname@example.com> gst <someone@foo.com> "" sendToDistList
----

==== Active Directoryのアカウントによる配布リストのメンバーの閲覧を有効にする

Active Directory配布リストのメンバーをメッセージやアドレス帳から確認には、Active DirectoryのGALグループハンドラを、Active Directoryごとに、{product-abbrev}のGalSyncアカウント内に設定する必要があります。

本項の手順で、Active DirectoryごとのGalSyncアカウントを更新します。この設定を行なうには、GalSyncアカウント名とそのGALSyncアカウント内の全データソースを認識している必要があります。

. GalSyncアカウントのZimbraIDを表示します。
+
[source,bash]
----
zmprov gd {ドメイン名} zimbraGalAccountId
----
+
アカウント名の検索
+
[source,bash]
----
zmprov ga {GAL同期アカウントのzimbraId} name
----

. GalSyncアカウントのデータソースを表示します。
+
[source,bash]
----
zmprov gds {ドメインのGAL同期アカウント名}
----

. Active Directoryのグループハンドラを有効にします。
+
[source,bash]
----
zmprov mds {ドメインのGalSyncアカウント名} {ADのデータソース名} \
 zimbraGalLdapGroupHandlerClass com.zimbra.cs.gal.ADGalGroupHandler
----

[[using_dynamic_distribution_lists]]
== ダイナミック配布リストを使用する

ダイナミック配布リストは、メンバーを自動的に管理します。ユーザーは、リストに自動で追加・削除されます。ダイナミック配布リスト作成時、メンバーURLが指定されます。このメンバーURLは、含まれているはずのメンバーの識別に使用されます。このメンバーURLは、管理コンソールの配布リストのプロパティページで閲覧できます。

ダイナミック配布リストは、管理コンソールまたはコマンドラインから作成できます。URL内には、ダイナミック配布リストに追加されるユーザータイプの判別用に、特有のオブジェクトクラスを指定します。例えば、ダイナミック配布リストを、オブジェクトクラス = zimbraAccountで設定したとします。すると、新規アカウントの作成やアカウントの削除時、このダイナミック配布リストは更新されます。

すべてのモバイル、POP/IMAPのユーザーにダイナミック配布リストを作成できます。

配布リストのフィルタールールも変更することができます。配布リストを編集すると、新しいルールに従って、参加するメンバーが更新されます。

[[create_dynamic_distribution_lists]]
=== ダイナミック配布リストを使用する

ダイナミック配布リストは前述のとおり、管理コンソールまたはCLIから作成できます。

管理コンソール: ::
*ホーム > 管理 > 配布リスト*

. 右上の *ギア* アイコンより、 *新規* をクリックします。

. *メンバー* ページから、ダイナミック配布リストの名前を入力します。スペースは使用できません。リストにメンバーを追加しないでください。

. *次へ* をクリックし、*プロパティ* ページで設定します。
+
.ダイナミック配布リストのオプション
[cols="1,4a",options="header",]
|=======================================================================
|オプション |説明

|メール受信可 |
デフォルトで有効です。配布リストがメッセージを受信すべきでないなら、このオプションを無効にします。

|GALに表示しない |
このオプションを有効にすると配布リストがグローバルアドレスリスト(GAL)に表示されません。このオプションを利用して、配布リストのメールアドレスの存在を知るユーザーを制限できます。

|メールサーバー |
デフォルトで　*自動* が設定されます。特定のメールサーバーを指定する場合、　*自動* を無効にし、一覧からサーバーを特定します。

|ダイナミックグループ |
このチェックボックスを有効にします。

|権限管理で使用可能 |
このチェックボックスを無効にします。

|メンバーURL |
メンバーURLはLDAP URLのフィルターの一種で、リストに追加・削除するユーザータイプを決めます。

このリストのURLを入力します。コマンドでは `ldap://??sub?` がURLです。
様々なダイナミック配布リストの作成のため、フィルターの組み合わせを自由にメンバーURLに追加します。

.すべてのユーザー、GALアカウント、スパム/ハムのリスト
====
----
ldap:///??sub?(objectClass=zimbraAccount)
----
====

.委任された管理者のリスト
====
----
ldap:///??sub?(&(objectClass=zimbraAccount)(zimbraIsDelegatedAdminAccount=TRUE))
----
====

.アクティブなアカウントすべて
====
----
ldap:///??sub?(&(objectClass=zimbraAccount)(ZimbraAccountStatus=active))
----
====

.役職が「Manager」のユーザーすべて
====
役職はアカウントの *連絡先情報の役職* から取得します。 この例ではこの項目にManagerが設定されています。
----
ldap:///??sub?(&(objectClass=zimbraAccount)(title=Manager))
----
====

|新しい購読の要求 |
*自動的に拒否する* を選択します。

|購読解除の要求 |
*自動的に拒否する* を選択します。

|=======================================================================

. ダイナミック配布リストにエイリアスを追加すべきなら、作成します。

. ダイナミック配布リストを他のユーザーにも管理させるなら、*オーナー* ページから、対象者のメールアドレスを入力します。

. 返信先メールアドレスをセットアップしたいなら、ここに入力します。配布リストへの返信は全て、このメールアドレスに送信されます。

. *完了* をクリックします。ダイナミック配布リストが作成されます。

指定したフィルターに基づき、リストにユーザーが自動追加されます。管理者がユーザーを追加・削除するとリストは更新されます。

[NOTE]
元は管理コンソールで作成されたダイナミック配布リストをCLIを使用して編集するには、そのダイナミック配布リストの `zimbraIsACLGroup` を必ず *FALSE* にする必要があります。

---

CLIの `zmprov` コマンドでダイナミック配布リストを管理できます。コマンドでは `ldap:///??sub?` がURLです。様々なダイナミック配布リストの作成のため、フィルターの組み合わせを自由にメンバーURLに追加します。

. すべての新規・既存アカウントのダイナミック配布リストを作成します。
+
すべてのユーザー、GALアカウント名、スパム/ハムのアカウント名が含まれます。ユーザーアカウントの削除時、自動的にリストから削除されます。
+
[source,bash]
----
zmprov cddl <all@domain.com> zimbraIsACLGroup FALSE \
  memberURL 'ldap:///??sub?(objectClass=zimbraAccount)'
----

. 提供サービスを作成し、ユーザーに指定します。
+
提供サービスを作成します。特定の条件、例えば「全マネージャー」など、に基づき、作成した提供サービスをユーザーに指定すると、その提供サービス用のダイナミック配布リストを簡単に修正することができます。
+
.特定の提供サービスにアクティブアカウントがあるユーザーが全員入っているダイナミック配布リスト
====
[source,bash]
----
zmprov cddl <allusers@domain.com>  zimbraIsACLGroup FALSE \
  memberURL 'ldap:///??sub?(&(objectClass-zimbraAccount) (zimbraCOSId=513e02e-9abc-4acf-863a-6dccf38252e3) (zimbraAccountStatus=active))'
----
====
+
.役職に基づいてユーザーが全員入っているダイナミック配布リスト
====
この実行には、アカウントの連絡先情報に *役職* が設定されていなければなりません。この例は役職に「Manager」が設定されています。
[source,bash]
----
zmprov cddl <allmanagers@domain.com> zimbraIsACLGroup FALSE' \
  memberURL ldap:///??sub?(&(objectClass-zimbraAccount) (zimbraCOSId=513e02e-9abc-4acf-863a-6dccf38252e3) (title=Manager))'
----
====
+
.委任された管理者全員のダイナミック配布リスト
====
[source,bash]
----
zmprov cddl <alldelegatedadmins@domain.com> zimbraIsACLGroup FALSE \
  memberURL 'ldap:///??sub?(&(objectClass-zimbraAccount) (zimbraCOSId=513e02e-9abc-4acf-863a-6dccf38252e3) (zimbraIsDelegatedADminAccount=TRUE))'
----
====

== メールボックスを移動する

メールボックスは、同じLDAPサーバーを共有するZimbraサーバー間で移動できます。

メールボックスの移動は管理コンソールやCLIコマンドから実行できます。 `zmmboxmove` を使用すれば、サーバーを停止せずに、サーバー間のメールボックス移動ができます。

移動先のサーバーが、メールボックス移動プロセスを管理します。移動はバックグランドで動作するため、アカウントは、ほぼ全てのデータが移動し終わるまで、アクティブモードのままです。アカウントは、最終データ移動のわずかな間、ロックされますが、すぐにアクティブモードに戻ります。

メールボックス移動プロセスは以下の手順で実行されます。

* メールボックスブロブが移動先のサーバーに移されます。

* 内容がほぼ移されると、アカウントはメンテナンスモードに切り替わります。

* データベーステーブル、インデックスディレクトリ、変更されたブロブ全てが移されます。

* アカウントはアクティブモードに戻されます。

メールボックスが移動先サーバーに移動後、元サーバーにまだコピーがありますが、ステータスは閉鎖です。ユーザーはログイン不可、メールは配信されません。旧メールボックスの削除前に、データが完全に新メールボックスへ移されていることを確認してください。

* メールボックスを新サーバーに移動。
+
[source,bash]
----
zmmboxmove -a <アドレス@ドメイン> --from <旧サーバー> --to <新サーバー>
----

* 旧サーバーからメールボックスを削除。
+
[source,bash]
----
zmpurgeoldmbox -a <アドレス@ドメイン> -s <旧サーバー>
----

=== メールボックスを移動するグローバル設定のオプション

メールボックス移動に関するグローバル設定のオプションとして、メールボックス移動時、検索インデックス、ブロブ、HSMブロブを除外するように設定できます。以下の設定オプションを、移動元サーバーあるいは移動先サーバーで設定できます。

* `zimbraMailboxMoveSkipSearchIndex` --
検索インデックスデータを含めない場合、移動後にメールボックスを再インデックスしないといけません。

* `zimbraMailboxMoveSkipBlobs` --
メールボックスに紐づくブロブは、プライマリとセカンダリボリューム(HSM)込みで、除外されます。

* `zimbraMailboxMoveSkipHsmBlobs` --
移動中のメールボックスのためのHSMブロブが既に存在するとき、有用です。 `zimbraMailboxMoveSkipBlobs` が設定されていないものHSMボリュームにあるブロブをスキップしたい場合にこのオプションを設定してください。
