[[admin-ng-guide]]
= 管理NG

[[delegated-admin-provisioning]]
== 委任管理のプロビジョニング


[[what-is-the-delegated-admin-provisioning]]
=== 委任管理のプロビジョニングとは


委任管理のプロビジョニングとは、ユーザーへドメイン管理の権限を付与したり、またその編集や取消を行なうことのできる処理全般を指します。

全ての委任管理のプロビジョニング処理は、下記にて実施することができます。

* 管理拡張機能の管理NGタブから。
* CLIから _zimbraユーザー_ にて該当の _zxsuite_ コマンドを実行。

[[granting-delegated-admin-rights-to-a-user]]
=== 委任管理の権限をユーザーへ付与する


[[add-da-from-the-administration-zimlet]]
==== 管理拡張機能から

管理拡張機能の管理NGタブ内、`委任された管理者` セクションにある `追加` ボタンをクリックします。

下記情報の入力が促されます。

* アカウント: 委任管理の権限を付与したいメールアドレス
* ドメイン: 委任された管理者による管理の対象となるドメイン
* 委任された認証: チェックがオンのとき、委任された管理者は選択されたドメインの全メールボックスの `メールを表示` 機能を利用できます。
* 権限の制限: 委任された管理者が対象ユーザーアカウントの機能タブの内容を編集できるかどうかを定義します。
* 機能を編集: 委任された管理者が対象ユーザーアカウントの `機能` タブの内容を編集できるかどうかを定義します。

WARNING: `権限の制限` の値より、 `ドメイン単位での割り当て使用量` が小さい場合、
`権限の制限` は無効になります。 +
ディスク容量と容量制限はギガバイト単位(gb)、メガバイト単位 (mb)、キロバイト単位(kb)のいずれも入力可能です。

[[add-dafrom-the-cli]]
==== CLIから

委任管理の権限をユーザーへ付与するには、 `doAddDelegationSettings`
コマンドを使用します。

....
構文:
   zxsuite admin doAddDelegationSettings {account} {domain} [attr1 value1 [attr2 value2...]]

パラメーターリスト

名前             データ型       期待値            初期値
account(M)       String
domain(M)        String
viewMail(O)      Boolean    true|false         false
editFeatures(O)  Boolean    true|false         false
adminQuota(O)    String                        -1

(M) == 必須パラメーター, (O) == 任意のパラメーター

使用例:


zxsuite admin doAddDelegationSettings john@example.com example.com viewMail true adminQuota -1
ドメインexample.comの委任された管理者としてJohnを追加。このドメインのメールを表示する権限あり。また、ユーザーに容量を割り当てられる権限なし。

zxsuite admin doAddDelegationSettings john@example.com example.com adminQuota 0
ドメインexample.comの委任された管理者としてJohnを追加。ユーザーに無制限の容量を割り当てられる権限あり。

zxsuite admin doAddDelegationSettings john@example.com example.com adminQuota 10gb
ドメインexample.comの委任された管理者としてJohnを追加。各ユーザーに10GBまでは容量を割り当てられる権限あり。
....

[[editing-the-rights-of-an-existing-delegated-admin]]
=== 既存の委任管理の権限を編集する

[[edit-da-from-the-administration-zimlet-1]]
==== 管理拡張機能から

管理拡張機能の管理NGタブ内、`委任された管理者` の一覧から1件選択し、`編集` ボタンをクリックします。

対象の行のダブルクリックにより、編集することも可能です。

[[edit-da-from-the-cli-1]]
==== CLIから

既存の委任管理の権限を編集するには、
`doEditDelegationSettings` コマンドを使用します。

....
構文:
   zxsuite admin doEditDelegationSettings {account} {domain} [attr1 value1 [attr2 value2...]]

パラメーターリスト

名前             データ型       期待値
account(M)       String
domain(M)        String
viewMail(O)      Boolean    true|false
editFeatures(O)  Boolean    true|false
adminQuota(O)    String

(M) == 必須パラメーター, (O) == 任意のパラメーター

使用例:

zxsuite admin doEditDelegationSettings john@example.com example.com viewMail true adminQuota -1
ドメインexample.comの委任された管理者としてのJohnの権限を編集。このドメインのメールを表示する権限をありにし、ユーザーに容量を割り当てられる権限をなしにする。

zxsuite admin doEditDelegationSettings john@example.com example.com adminQuota 0
ドメインexample.comの委任された管理者としてのJohnの権限を編集。ユーザーに無制限の容量を割り当てられる権限をありにする。

zxsuite admin doEditDelegationSettings john@example.com example.com adminQuota 10gb
ドメインexample.comの委任された管理者としてのJohnの権限を編集。各ユーザーに10GBまでは容量を割り当てられる権限をありにする。
....

[[revoke-delegated-admin-rights-from-a-user]]
=== 委任管理の権限を取り消す

[[from-the-administration-zimlet-2]]
==== 管理拡張機能から

管理拡張機能の管理NGタブ内、`委任された管理者` の一覧から1件選択し、`削除` ボタンをクリックします。

[[from-the-cli-2]]
==== CLIから

委任管理の権限を取り消すには、
`doRemoveDelegationSettings` コマンドを使用します。

....
構文:
   zxsuite admin doRemoveDelegationSettings {account} {domain}

パラメーターリスト

名前          データ型
account(M)    String
domain(M)     String

(M) == 必須パラメーター, (O) == 任意のパラメーター

使用例:

zxsuite admin doRemoveDelegationSettings john@example.com example.com
Johnはドメインexample.coの管理者ではなくなる。
....

[[quota-management]]
== 容量管理

[[what-is-quota-management]]
=== 容量管理とは

管理NGでは、システム管理者が `権限の制限` と `ドメイン単位での割り当て使用量` という２種類の容量制限を設定できます。

どちらも必須ではありません。つまり、設定されていない場合、委任された管理者は任意の容量をユーザーに与えることも、容量制限のないドメインにすることもできます。

[[the-grant-limit]]
=== `権限の制限`

`権限の制限` とは、委任された管理者のプロパティのひとつです。

このプロパティの値は、委任された管理者がユーザーに与えることのできるメールボックス容量の制限値を示しています。委任された管理者の設定からこの値の入力・変更を行ないます。

このプロパティの値には、下記３つの選択肢があります。

* なし : 委任された管理者は、メールボックスに関する容量属性を編集できません。
* カスタム : 委任された管理者は、指定された値までであれば付与できます。この値はドメイン/提供サービス(COS)の容量設定にオーバーライドします。
* 無制限 : 委任された管理者はメールボックスに対する容量を制限なく付与できます。これはドメイン/提供サービス(COS)の容量設定にオーバーライドします。

[[the-domain-quota]]
=== `ドメイン単位での割り当て使用量`

`ドメイン単位での割り当て使用量` とは、*管理者のタイプに関わらず* 、そのドメインのメールボックスに与えることのできる容量の制限値を示すプロパティです。

WARNING: メールボックスに対する容量を制限なく付与することは、ドメイン単位での割り当て使用量にオーバーライドします。

[[grant-limit-vs-domain-quota]]
=== `権限の制限` vs `ドメイン単位での割り当て使用量`

`権限の制限` と `ドメイン単位での割り当て使用量` は、制限ベースで互いに排他です。

つまり、以下のシナリオが起こりえます。

* システム管理者が、許可されたドメイン単位での割り当て使用量よりも大きな容量をユーザーに付与。
* 委任された管理者が、許可されたドメイン単位での割り当て使用量よりも大きな容量をユーザーに付与。
* 委任された管理者の権限の制限の値が、許可されているドメイン単位での割り当て使用量よりも低い。

このシナリオをひとつずつ検証してみます。

[[a-global-admin-grants-a-user-a-higher-quota-than-the-allowed-domain-quota]]
==== システム管理者が、許可されたドメイン単位での割り当て使用量よりも大きな容量をユーザーに付与


ドメイン単位での割り当て使用量は管理者ではなくドメインに適用されるため、ユーザーが使用できる最大容量は、 `ドメイン単位での割り当て使用量` の設定で許可されている容量制限値となります。

[[a-delegated-admin-grants-a-user-a-higher-quota-than-the-allowed-domain-quota]]
==== 委任された管理者が、許可されたドメイン単位での割り当て使用量よりも大きな容量をユーザーに付与

委任された管理者の権限の制限の値のほうが許可されているドメイン単位での割り当て使用量より大きい場合、ユーザーが使用できる最大容量は、 `ドメイン単位での割り当て使用量` の設定で許可されている容量制限値となります。

[[a-delegated-admins-grant-limit-is-lower-than-the-domain-quota]]
==== 委任された管理者の権限の制限の値が、許されているドメイン単位での割り当て使用量よりも小さい

許可されたドメイン単位での割り当て使用量のほうが大きい場合、委任された管理者がユーザーに付与できる最大容量は、委任された管理者の権限の制限として定義されている容量制限値です。権限の制限のないシステム管理者の場合は、ドメイン単位での割り当て使用量で許可された範囲内で付与できます。

[[domain-limits]]
== ドメイン制限

[[what-is-domain-limit-management-a.k.a.-domain-settings]]
=== ドメイン制限の管理とは(`ドメイン設定` とも言います)

ドメイン制限の管理は、管理NGモジュールの一機能です。システム管理者は、管理者のタイプに関わらず遵守しなければならないドメインレベル制限を設定することができます。

ドメイン制限を破るには、ドメイン制限自体を変更するしかありません。

[[domain-limits-1]]
=== ドメイン制限

* グローバルアカウント制限: このドメインで作成可能な最大アカウント数。
* ドメイン単位での割り当て使用量: 管理者のタイプに関わらず、そのドメインのメールボックスに付与可能な容量の制限値。
* 提供サービス(COS)制限:ドメインのユーザーが使用できる提供サービスと、提供サービス(COS)の最大ユーザー数(アカウント制限)を定義します。

[[edit-the-limits-of-a-domain]]
=== ドメイン制限の編集

[[from-the-administration-zimlet-3]]
==== 管理拡張機能から

管理拡張機能の管理NGタブ内 `ドメイン設定` の一覧には、Zimbraインフラにある全ドメインが表示されます。

ドメイン制限を編集するには、 `ドメイン設定` の一覧から1件選択し、 `編集` ボタンをクリックします。

[[from-the-cli-3]]
==== CLIから

CLIからドメイン制限を編集するには、 `setDomainSettings`
コマンドを使用します。

....
構文:
   zxsuite admin setDomainSettings {domain} [attr1 value1 [attr2 value2...

パラメーターリスト

名前                       データ型       期待値                   初期値
domain(M)                  String
account_limit(O)           Integer                                       設定変更しないこと。
domain_account_quota(O)    String                                        設定変更しないこと。
cos_limits(O)              String     cosname1:limit1,cosname2:limit2    設定変更しないこと。

(M) == 必須パラメーター, (O) == 任意のパラメーター

使用例:


zxsuite admin setDomainSettings example.com account_limit 100 domain_account_quota 100mb cos_limits cos1:30,cos2:80

ドメインexample.comのグローバルアカウント制限には100アカウント、
ドメイン単位での割り当て使用量の制限値には100メガバイト、提供サービス(COS)のアカウント制限としてcos1には30、cos2には80を設定します。

Note: 提供サービス(COS)のアカウント制限に-1を設定すると、制限はなくなります。

....

[[reset-the-limits-of-a-domain]]
=== ドメイン制限のリセット

[[from-the-administration-zimlet-4]]
==== 管理拡張機能から

管理拡張機能の管理NGタブ内 `ドメイン設定` の一覧には、Zimbraのインフラにある全ドメインが表示されます。

ドメイン制限をリセットするには、 `ドメイン設定` の一覧から1件選択し、`リセット` ボタンをクリックします。その後表示される確認用ポップアップ画面で `OK` をクリックします。

[[from-the-cli-4]]
==== CLIから

CLIからドメイン制限をリセットするには、
`resetDomainSettings` コマンドを使用します。

....
構文:
   zxsuite admin resetDomainSettings {domain}

パラメーターリスト

名前         データ型
domain(M)    String

(M) == 必須パラメーター, (O) == 任意のパラメーター
....

[[zimbra-administration-as-a-delegated-admin]]
== 委任された管理者としてZimbraを管理する

[[accessing-the-zimbra-administration-console-as-a-delegated-admin]]
=== 委任された管理者としてZimbra管理コンソールにアクセスする

Zimbra管理コンソールにアクセスするには、ウェブブラウザからメールサーバーポート7071に接続し、自身のZimbra認証を使用してログインします。

例: https://mail.domain.com:7071

[[delegated-admin-can-and-cant-table]]
==== 委任された管理者ができること・できないことの一覧

参照用に以下、委任された管理者が管理NGモジュールでできること・できないことを表に記します。

[cols=",",options="header",]
|=======================================================================
|できること |できないこと
|委任管理権限を持つドメインに属するアカウント一覧の閲覧 |他のドメインに属するアカウント一覧の閲覧

|委任管理権限を持つドメインに属するユーザーアカウントの編集 |他のドメインに属するユーザーアカウントの編集

|委任管理権限を持つドメインに属するエイリアス、配布リスト、リソースの編集 |他のドメインに属するエイリアス、配布リスト、リソースの編集

| |システム管理者アカウントの編集

| |システム管理権限あるいは委任管理権限を他のユーザーへ付与

|委任管理権限を持つドメインのアカウントを作成
 |他のドメインのアカウント作成

|対象アカウントのドメインで使用できる提供サービス(COS)を選択|対象サーバーで使用できる提供サービス(COS)を任意で設定

| |提供サービス(COS)の設定

| |サーバー本来の機能を妨げる可能性のあるドメイン設定の編集

| |サーバー設定の閲覧・編集

| |グローバル設定の閲覧・編集
|=======================================================================

[[overview-of-the-zimbra-administration-console-for-delegated-admins]]
==== 委任された管理者としてログインした場合のZimbra管理コンソール使用概要

* `管理`:
** `アカウント`: 委任管理権限を持つドメインに属するアカウントの管理
** `エイリアス`: 委任管理権限を持つドメインに属するアカウントエイリアスの管理
** `配布リスト`: 委任管理権限を持つドメインに属する配布リストの管理
** `リソース`:委任管理権限を持つドメインに属するリソースの管理
* `設定`: 委任管理権限を持つドメインの設定の閲覧
* `検索`: 高度な検索の実行
* `Network NG`
** `モバイルタブ`: 委任管理権限を持つドメインに属するクライアント・モバイルデバイス間の同期管理
** `管理タブ`: 委任管理権限を持つドメインに属する委任された管理者の一覧と容量利用に関する情報の閲覧
* `キーワード検索機能バー`: 簡易検索の実行
* `[ユーザー名]`: Zimbra管理コンソールからのログアウト

[[delegated-admin-log-browsing]]
== 委任された管理者のログ閲覧

[[what-is-delegated-admin-log-browsing]]
=== 委任された管理者のログ閲覧とは

システム管理者は全管理者のアクティビティ情報を検索ベースでグラフィックなログブラウザから簡単にトラッキングすることができます。

[[the-admin-ng-log-browser]]
=== 管理NGのログブラウザ

管理NGのログブラウザは、管理拡張機能の管理NGタブにある `ログ閲覧` ボタンからアクセスできます。ボタンクリックで開く `ログ閲覧` 用ポップアップ画面にて、表示させたいログを絞込むことができます。

使用可能なフィルター

* `基本` フィルター
** `管理者`: あるドメイン管理者の操作ログのみを表示させるフィルター
** `アクション`: 特定のアクションのログのみを表示させるフィルター。対象アクションについては後述を参照してください。
* `高度な` フィルター
** `クライアントIP`: 指定したIPアドレスからの操作ログのみを表示させるフィルター
** `ログイン表示`: このチェックボックスをオンにすると、ドメイン管理者がZimbraウェブクライアントにログインした時間も表示されます。
** `結果`: すべて、成功、失敗のいずれかのログのみを表示させるフィルター
** `スタート` と `エンド`: この期間のログのみを表示させるフィルター(デフォルト：当日)

`詳細` ボタンをクリックすると、選択したフィルターの結果がログブラウザに表示されます。

[[the-action-filter]]
=== `アクション` フィルター

管理者が実行可能な全操作が `アクション` フィルターのドロップダウンに入っています。

管理者の操作をトラッキングし、トラブルシューティングを行なうには下記の操作が重要です。

* `Auth`: 全てのZWC認証
* `DelegateAuth`: 全ての委任認証。 `メールを表示` ボタンからの操作と _zmmailbox_ コマンド `-z` オプションの実行が対象になります。
* `CreateAccount`: 全てのアカウント作成
* `DeleteAccount`: 全てのアカウント削除
* `Set Password`: 全てのメールボックスパスワード変更
* `RemoveAccountAlias`:全てのエイリアス削除
* `DeleteDistributionList`: 全ての配布リスト削除

[[reports-and-informations]]
== レポートと情報

[[admin-ng-monthly-reports]]
=== 管理NGの月間レポート

システム管理者は管理NGモジュールに備わった `月間レポート` 機能を利用して、委任された管理者による操作や対象月のドメイン状態をトラッキングすることができます。
月間レポートシステムの詳細
各月初日に、管理NGログの集積データに基づくレポートが管理NGモジュールによって自動生成されます。

[[how-does-the-monthly-report-system-work]]
=== 月間レポートシステムの詳細

各月初日に、管理NGログの集積データに基づくレポートが管理NGモジュールによって自動生成されます。

この月間レポートには下記の情報が掲載されます。

[cols=",",options="header",]
|=======================================================================
|グローバルレポート|
|最初のログアクション |管理者が今月最初に操作したときのタイムスタンプ

|最後のログアクション |管理者が今月最後に操作したときのタイムスタンプ

|管理者最終ログイン |管理者が最後にログインしたときのタイムスタンプ

|最も活動的だった管理者 |ログに記録された操作数が最も多い管理者名

|最もよく使われたIPアドレス |管理者のログインで最も使用されたIPアドレス

|アカウント総数 |メールボックス総数

|作成アカウント総数|月間で作成されたメールボックス数

|削除アカウント総数|月間で削除されたメールボックス数

|作成ドメイン総数 |月間で作成されたドメイン数

|作成配布リスト総数 |月間で作成された配布リスト数

|削除配布リスト総数 |月間で削除された配布リスト数
|=======================================================================

[cols=",",options="header",]
|=======================================================================
|ドメインレポート  |
|ドメイン |このデータの参照先ドメイン名

|管理者最終ログイン |管理者が最後にログインしたときのタイムスタンプ

|アカウント/最大アカウント数 |現在のアカウント数と最大アカウント数

|現在のドメインサイズ |ドメインの全メールボックスで使用中の総容量

|最大ドメイン容量 |全メールボックスの最大容量合計 (`無制限` のメールボックスは除く)

|制限なしアカウント |制限のないメールボックス数

|制限なしアカウント容量 |制限のない全メールボックスで使用中の総容量

|ドメイン内システムリソース |ドメイン内のシステムリソースアカウント数

|ドメインごとの“カレンダーリソース”アカウント |ドメインのカレンダーリソースアカウント数

|成功したドメインアクション |このドメインで管理者が成功した操作回数

|失敗したドメインアクション|このドメインで管理者が失敗した操作回数
|=======================================================================

[cols=",",options="header",]
|=======================================================================
|管理者レポート |
|管理者 |このデータの参照先管理者名

|成功したログイン |管理コンソールへのログイン成功回数

|失敗したログイン |管理コンソールへのログイン失敗回数

|“メールを表示” アクション |この管理者の `メールを表示` 機能月間使用回数

|最終ログイン |この管理者が管理コンソールへ最後にログインしたときのタイムスタンプ

|最もよく使われたIPアドレス |この管理者のログインで最も使用されたIPアドレス

|アクション数合計 |この管理者が月間で実施した操作回数

|作成したアカウント数 |この管理者が月間で作成したアカウント数

|削除したアカウント数 |この管理者が月間で削除したアカウント数
|=======================================================================

[[how-to-access-the-monthly-reports]]
=== 月間レポートへのアクセス方法

[[from-the-administration-zimlet-5]]
==== 管理拡張機能から

`月間レポート` へのアクセス方法

* システム管理者としてZimbra管理コンソールにログインします。
* 管理拡張機能の管理NGタブ画面右上にある、`月間レポート` ボタンをクリックします。
* 表示させたい月を選択し、`レポートを表示` ボタンをクリックします。

[[from-the-cli-5]]
==== CLIから

CLIから月間レポートを表示するには、`getMonthlyReport` コマンドを使用します。

....
zxsuite admin getMonthlyReport [attr1 value1 [attr2 value2...

パラメーターリスト

名前        データ型       期待値            初期値
month(O)    String     mm/yyyy            12/2012
local(O)    Boolean    true|false         false

(M) == 必須パラメーター, (O) == 任意のパラメーター

使用例:

zxsuite admin getMonthlyReport
前月の月間レポートを表示します。

zxsuite admin getMonthlyReport month 11/2012
2012年11月の月間レポートを表示します。

....

[[partial-reports]]
==== 部分レポート

当月分の部分レポートを作成するには、`doMonthlyReport` コマンドを使用します。

....
zxsuite admin doMonthlyReport [attr1 value1 [attr2 value2...

パラメーターリスト

名前         データ型     期待値              初期値
month(O)    String     mm/yyyy            12/2012
force(O)    Boolean    true|false         false

(M) == 必須パラメーター, (O) == 任意のパラメーター

使用例:

zxsuite admin doMonthlyReport
前月の月間レポートを生成し、それを現在の管理NGのログパスに保存します。

zxsuite admin doMonthlyReport month 01/2013
当月の部分月間レポートを生成しますが、ディスクへの保存はしません。

** 備考**

このコマンドは月に一度自動実行され、前月分のレポートファイルを作成します。既存のレポートファイルを上書きするには、パラメーター'force'をtrueに設定してください
....

[[the-admin-ng-log-path]]
=== 管理NGのログパス

管理NGモジュールでは、全ての月間レポートは、月間レポート生成に使用するログや `管理ログ閲覧` 機能で使用するログと共に
`/opt/zimbra/conf/` ディレクトリ内のパスに格納されます (デフォルトは `/opt/zimbra/conf/zextras/zxadmin/`)。
このパスはZimbraのアップデート中に削除されることがないため、デフォルトパスになっています。

[[the-admin-ng-log-path-structure-and-contents]]
==== 管理NGのログパスの構造と内容

管理NGのログパスは、下記ファイルを格納するフラットなディレクトリです。

* 1件以上の `YYYY_MM` ファイル。各ファイルには、ファイル名と同じ年月のログが格納されています。
* 0件以上の `YYYY_MM.report` ファイル。各ファイルには、ファイル名と同じ年月の月間レポートが格納されています。
* 0件以上の `YYYY_MM.X` ファイル。各ファイルには、ファイル名と同じ年月のログが格納されています。このファイルは管理NGのログパスを変更したときに作成されます。

[[changing-the-admin-ng-log-path]]
==== 管理NGのログパスの変更

WARNING: 管理NGのログパスを変更する前に、この項を精読するようにしてください。手順を誤るとログを損失し、 `月間レポート` や `管理ログ表示` への信頼を落とす要因になります。

管理NGのログパスを安全に変更するには、下記手順に従ってください。

* ログの格納先となるフォルダを作成します。
** このフォルダのオーナーを `zimbra:zimbra` にします。
** `zimbra` ユーザーはこのフォルダに対する読み書き権限が必要です。
** このフォルダは空でなければなりません。
* システム管理者にてZimbra管理コンソールにログインします。
* 管理拡張機能の管理NGタブを開きます。
*  `基本モジュール設定` のセクションにて、管理ログパスの付近にある変更ボタンをクリックします。
* 新しいパスを入力し、`パス変更` をクリックします。
* エラーが表示されたら、旧ログパスの全内容を移動します。
** 旧ログパス内に、 `.report` ファイルと `.X` ファイルしか表示されなくなりますが正常な結果です。現在のログファイルは部分的なものであることを知らせるため、拡張子が `.1` になります。それ以前の `.X` ファイルの拡張子はそれぞれ１つ増分されます。

[[configuration-reset]]
== 設定リセット

[[what-is-the-admin-ng-configuration-reset]]
=== 管理NGの設定リセットとは

管理NGの設定リセットとは、システム管理者がサーバーから一切の委任権限を完全にワイプできる機能です。

これは管理NGモジュールの設定をクリーンアップする `ロールバック` 機能ではありません。設定リセットの対象は管理NGとZimbra両方の委任権限になります。

WARNING: 管理NGの設定リセットを使用すると、サーバーにある全ての委任権限が完全にワイプされ、環境は初期状態に戻されます。管理委任設定のみがワイプされるため、他のデータへの影響はありません。

[[what-does-the-admin-configuration-reset-clear]]
==== 管理設定リセットのクリア対象

下記の設定が管理設定リセットでクリアされます。

* サーバーにある全アカウントの `isDelegatedAdmin` アカウントプロパティ
* 下記についての全てのアクセス制御エントリと全てのアクセス制御リスト
** ユーザー
** ドメイン
** 提供サービス
** ローカル設定
** サーバー設定
** Zimlet

[[when-should-i-use-the-admin-config-reset]]
==== 管理設定リセットを利用する場面

管理設定リセットは下記場合を除き、利用しないでください。

* 他に仕方のない状況のため、完全リセットする場合
** 不正なアクセス制御エントリまたはアクセス制御リストの設定が1件以上存在するせいでZimbra管理コンソールが不安定または不適切に表示される(ブランクページが表示される、1件以上のUI項目が表示されないなどの)場合に、最終手段として管理設定リセットを使用してください。

* 管理NGモジュールの使用をやめる場合
** アクティブなNetwork NGライセンスがない場合にも、リセット機能は使用できます。留意すべきこととして、マニュアル操作で設定した委任設定が全てワイプされます。

[[how-do-i-use-the-admin-configuration-reset]]
==== 管理設定リセットの使用方法

*本当に* 管理委任設定のリセットを実行したい場合は、下記CLIコマンドを実行するだけで済みます。

`zxsuite core doDeleteAllDelegatedRights`

コマンドの誤使用を避けるため、確認用文字の入力が促されます。
