[[MIG-88-incremental-migration-with-backup-from-old-to-88]]
= Backup NGを利用したZimbra8.8.0への増分移行

[[MIG-88-description]]
== 概要説明

* 本書では、Backup NGを利用した増分移行の実施方法を説明します。
* 商用環境の移行を目的とし、システム停止時間を最短化すること、そしてユーザーにとって透過性のあるものを目指し設計しています。
** 正確な計画に従い、正しく実行されれば、システムが停止することはありません。ユーザーへの影響も限りなくゼロに近づきます。
* 移行元のサーバーは、Zextras Suiteまたは Zimbra Suite Plusでなければなりません。
** Zimbra8.8のいずれかからサポートされているZimbraバージョンからの移行を本書の対象としています。
* 特に指定がない限り、本書に記載のCLIコマンドはzimbraユーザーで実行してください。

[[MIG-88-what-will-be-migrated]]
=== 移行対象

* メールとメールフォルダ
* 連絡先と連絡先リスト
* 予定とカレンダー
* タスクとタスクリスト
* 文書とブリーフケース
* 共有情報
* ユーザーのプリファレンス
* ユーザー設定
* 提供サービスの設定
* ドメイン設定

[[MIG-88-what-will-not-be-migrated]]
=== 移行対象外

* サーバー設定 (参照用に移行されますが復元はされません)
* グローバル設定 (参照用に移行されますが復元はされません)
* カスタマイズ内容 (Postfix, Jetty等)
* 処理中に移動または削除されたアイテムは、移行先サーバーでの移動・削除はされません。
* 処理中に変更されたプリファレンス (パスワード等) は、各インポート先でリセットされます。

WARNING: 増分移行は、サーバーtoサーバーのミラーリングのセットアップ用には設計されていません。複数インポートを利用して元サーバーをミラーしたコピーを作成しようとしても、*ミラーの* コピーは作成されません。インポート処理では削除が行なわれないからです。

[[MIG-88-source-data]]
== 元データ

移行元サーバーのデータは、Zextras Suiteまたは Zimbra Suite Plusから取得します。

* Zextras SuiteはZextraのウェブサイト https://www.zextras.com で取得可能です。
* Zimbra Suite PlusはZimbraののウェブサイト https://www.zimbra.com で取得可能です。

[[MIG-88-software-installation]]
=== ソフトウェアのインストール
Zextras Suiteまたは Zimbra Suite Plusを取得したら、次のインストール処理に従ってください。

* rootユーザーが所有しているサーバー内ディレクトリにパッケージをコピーします。
* `tar zxf` を使用してパッケージを展開します。
* `zextras_suite-[version]`
または `zimbra_suite_plus-[version]` という名称で新たに作成されたディレクトリ内に移動します。
* rootにて、インストール用スクリプト `./install.sh all` を実行します。
* インストールウィザードに従い、ソフトウェアEULAを受け入れ、CoreとZimletコンポーネントをインストールします。
* インストールが完了したら、本書に沿って処理を進めます。

WARNING: Zextras Suiteまたは Zimbra Suite Plusをインストールするにはmailboxdサービスの再開が必要です。これはインストール中に実行されます。

[[MIG-88-pre-migration-checks]]
== 移行前チェック

[[MIG-88-servers]]
=== サーバー

* 移行元サーバー: Backup NGまたはZimbra Suite Plusが実行中のZimbraサーバーであれば、移行元とすることができます。
* 移行先サーバー: Backup NGまたはZimbra Suite Plusが実行中のZimbraサーバーであれば、移行先とすることができます。

[[MIG-88-storage]]
=== ストレージ

* 移行元サーバー：移行元サーバー上でBackup NGが現在有効でない場合、 `/opt/zimbra/store/` のフォルダサイズと同等の空ディスク容量があることを確認してください (エクスポートされるサイズは通常、オリジナルサイズの70パーセントまで縮小化されます。gzipアルゴリズムを使ってエクスポートデータが圧縮されるためと全zimbraアイテムが重複排除されるためです) 。
* 移行先サーバー: `/opt/zimbra/store/` のフォルダサイズと移行元サーバーにある `export` フォルダサイズを合算したサイズよりも大きな空ディスク容量があることを確認してください。

[[MIG-88-data-transfer]]
=== データ転送

データの転送方法は様々ですが、rsyncによる手段を推奨します。速度と利便性の観点で妥当であるためです。

データ転送の大部分は移行元サーバーがまだ実行中・機能中の間に実行されます。しかしながら、転送はネットワーク経由であるため、あらかじめ緻密に計画してください。そうすれば、移行前に *全てのデータ* を転送し終えることができます。

[[MIG-88-alternative-ways-to-transfer-your-data]]
==== データ転送の代替案

転送手段は必要であればリモートリンクからドライブの物理的な移動まで、何でもかまいません。

....
ハイウェイでは速度が落ちるテープでいっぱいの
ステーションワゴンの帯域幅を決して少なく見積もることのないようにしてください。
--Tanenbaum, Andrew S. (1996). Computer Networks. New Jersey: Prentice-Hall. 
p. 83. ISBN 0-13-349945-6.
....

[[MIG-88-dns]]
=== DNS

実際のDNS上のMXレコードのTTLの値を300に設定してください。こうすることで、移行元サーバーと移行先サーバー間の切り替えが早くなります。

[[MIG-88-the-setup]]
== 移行のセットアップ

[[MIG-88-step-1-coherency-checks]]
=== 手順１: 一貫性チェック

データ関連の問題を回避するため、移行元サーバーで下記のチェックを実行してください。

* http://wiki.zimbra.com/wiki/Ajcody-Notes-No-Such-Blob#Zmblobchk_for_5.0.6.2B_Systems[zmblobchk]:
ZimbraのメタデータとBLOB間の一貫性をチェックします。
* http://wiki.zimbra.com/wiki/Zmdbintegrityreport[zmdbintegrityreport]:
Zimbraのデータベースの完全性をチェックします。

エラーが見つかった場合は、Zimbraの公式ドキュメントにある記載に従い修正してください。

また、全てのメールボックスの再インデックス化を実行することを推奨します。

[[MIG-88-step-2-network-ng-modules-setup]]
=== 手順２: Network NG のセットアップ

両サーバーで下記を実行し、Real Time Scannerを無効にしてください

....
zxsuite backup setProperty ZxBackup_RealTimeScanner false
....

WARNING: データエクスポートのための専用デバイスの使用を強く推奨します。エクスポートのパフォーマンスの向上のためとシステムのパフォーマンスへの影響を抑えるためです。

デバイスをパス `/opt/zimbra/backup/` にリンクさせてください。また、zimbraユーザーにはこのパスに対する読み書き権限がなければなりません。

[[MIG-88-step-3-data-export-smartscan]]
=== 手順３: データのエクスポート (SmartScan)

移行元サーバー上で下記コマンドを実行して、SmartScanを実行してください。
....
zxsuite backup doSmartScan
....

デフォルトのバックアップパス (/opt/zimbra/backup/ng/) に全データがエクスポートされることになります。

[[MIG-88-pro-tip-single-domains-export]]
==== ヒント: 単一ドメインのエクスポート

全ドメインではなく、１つまたは複数のドメインだけを移行することもできます。その場合は、SmartScanの *代わりに* 次のコマンドを実行します。

....
zxsuite backup doExport /path/to/export/folder/ domains yourdomain.com,yourdomain2.com[..]
....

留意すべきこととして、 `SmartScan` で開始した場合はずっと `SmartScan` で、 `単一ドメイン` での方法で開始した場合は、ずっと `単一ドメイン` での方法で移行を続ける必要があります。この2つの方法は混在できません。

[[MIG-88-data-export-smartscan-via-the-administration-zimlet]]
==== 管理拡張機能からデータのエクスポート (SmartScan)

下記のとおり、管理拡張機能からデータエクスポートを実行することもできます。

[[MIG-88-step-4-data-synchronization]]
=== 手順４: データの同期

WARNING: エクスポートしたデータを移行先サーバーへ移動するとき、移行先サーバーにある移動先フォルダがBackup NGのバックアップパスでないことを確認してください。移行先サーバーでBackup NGをすでに使用中、または使用予定がある場合、障害の要因になりかねません。

_(rsync以外の方法でデータ転送を行なう場合は、以下手順をスキップしてかまいません。)_

_rsync_ を使用して
/opt/zimbra/backup/ng/ 内のデータを移行先サーバーのディレクトリへコピーしてください (zimbraユーザーに対象フォルダへの読み書き権限があることを確認してください) 。 _screen_ や _tmux_ などのターミナルマルチプレクサを使用してください。この処理のコマンドは、ネットワーク速度や対象データの量によっては、かなりの長時間がかかるかもしれません。

....
[run this command as Root]
rsync -avH /opt/zimbra/backup/ng/ root@desinationserver:/path/for/the/data/
....

[[MIG-88-alternate-synchronization-method]]
==== その他の同期方法

これまで提案してきた方法は、帯域幅の広い環境の場合は最良です。一方で、大量のデータが初回同期の対象となる可能性があります。rsyncによる手段が遅いと感じる場合は、デバイス (仮想環境で実行中ならそのおおもとのディスクファイル) の物理的な移動を検討することになるかもしれません。

ディスク移動後はリンクをリモートで移行元サーバーに戻すことができます (例：SSHFS) 。移行の一環である「追加同期」で対象となるデータは少量だからです。なおこの場合、移行元サーバーのデバイスを/opt/zimbra/backup/ng/として再リンクさせ、そこに必要となる全ての権限を付与しておいてください。

[[MIG-88-step-5-first-import]]
=== 手順５: 初回インポート

エクスポートした全データを移行先サーバーへインポートします。

....
zxsuite backup doExternalRestore /path/for/the/data/
....

Network NGが移行先サーバーへデータをインポートしている間、安心してお待ちください。

''警告: この手順後はバックアップパスを編集・削除しないでください''

[[MIG-88-first-import-via-the-administration-zimlet]]
==== 管理拡張機能からの初回インポート

管理拡張機能を使用してデータのインポートをするという選択肢もあります。管理拡張機能からインポート中、インポートされるアカウントリストから全てのシステムアカウント (GalSync、Ham、Spam、Quarantineなど) が削除されることを確認してください。

[[MIG-88-step-5-alternate-first-import-for-large-migrations-advanced-users-only]]
=== 手順５(別案): 大規模移行時の初回インポート

ここからは、エクスポート・インポートに何時間もあるいは何日もかかるような巨大インフラを移行する管理者向けの別案を紹介します。

全データを移行先サーバーへインポートするのではなく、
`プロビジョニングのみ` インポートすることで、ドメインや提供サービス、アカウントだけ移行先サーバーに作成し、メールボックスの全内容を移行対象外とすることができます。

....
zxsuite backup doExternalRestore /path/for/the/data/ provisioning_only TRUE
....

上記コマンドを実行後、メールフローを新サーバーに切り替えます。切り替えが完了したら、`実際の` インポートを開始します。

....
zxsuite backup doExternalRestore /path/for/the/data/
....

こうすることでシステムユーザーの接続先が移行先サーバーに変わります。古いメールの復元が進行中の移行先サーバーに、新しいメールが配信されるようになります。

このアプローチにはメリットとデメリットがあります。

*メリット*

* アイテムのインポートは一度だけ、かつ、その後修正・削除はされないため、`標準の` 増分移行に比べると、不整合になる割合が減少します。
* 移行元サーバーへの影響を減らすオプションがあります (例：移行元サーバーを急いで閉鎖する場合、都合が良いです) 。

*デメリット*

* 処理のタイミングによっては、システムユーザーへの影響度が高まります。ユーザーがメールボックスを使用している間にもアイテムは復元中だからです。
* 稼働中のシステムでインポートを行なうため、速度低下が気になるかもしれません。

[[MIG-88-the-situation-so-far]]
== これまでの状況

この時点で、ほとんどのデータが移行先サーバーへインポートされました。移行元サーバーはまだ稼働中で、機能しています。これから、実際の移行を準備します。

[[MIG-88-the-migration]]
== 移行

[[MIG-88-step-6-pre-migration-checks]]
=== 手順６: 移行前チェック

メールフローを切り替える前に、必ず、移行先サーバーにおける稼動準備が整っていることを確認してください (ファイヤーフォール、DNS設定、セキュリティシステムなど) 。

[[MIG-88-step-7-the-switch]]
=== 手順７: 切り替え

ついに切り替えの瞬間です。この手順が終わる頃、移行先サーバーが稼動し機能しています。

* 手順３、手順４、手順５を繰り返します (新しいデータのみエクスポート・同期化される) 。
* メールフローを新サーバーへ切り替えます。
* 移行元サーバーにメールが一切届かなくなったら、手順３、手順４、手順５を繰り返します。

移行先サーバーは、現在稼動し機能しています。

[[MIG-88-step-8-post-migration-checks]]
=== 手順８: 移行後のチェック

次のコマンドを実行して、共有の不整合をチェックします。

....
zxsuite backup doCheckShares
....

不整合が見つかった場合は下記コマンドを実行します。このコマンドで、１つめの引数に使用したインポートマップファイルをパージし、不整合な共有をすべて修正します。

....
zxsuite backup doFixShares
....

マップファイルは、移行先サーバーのバックアップパス内にある
`map_[source_serverID]` です。

[[MIG-88-step-9-galsync]]
=== 手順９: Galsync

Zimbra管理コンソールから、インポートした全てのGalSyncアカウントを削除します。その後必要に応じて、インポートした全てのドメインのGalSyncアカウントを新規に作成します。そして、次のコマンドを使用して、全てのGalSyncアカウントを再同期化します。

....
zmgsautil forceSync -a galsync.randomstring@domain.com -n [resourcename]
....

[[MIG-88-step-10-message-deduplication]]
=== 手順１０: メッセージの重複排除

移行後はHSM NGモジュールを使って、ボリューム重複排除を実行することを強く推奨します。

[[MIG-88-what-now-1]]
=== その後

* 新サーバーのBackup NGを初期化し、全データに問題がないことを確認します。

[[MIG-88-incremental-migration-faq]]
== 増分移行に関するFAQ

[[MIG-88-q-do-i-need-a-valid-license-in-order-to-perform-an-incremental-migration]]
=== Q: 増分移行を行なうには、有効なライセンスが必要でしょうか。

はい。試用版または購入版、いずれかのライセンスが必要です。

[[MIG-88-q-what-will-be-migrated]]
=== Q: 移行対象となるものは何ですか。

サーバー設定を除いた全てが対象となり、サーバー設定には次のものが含まれます。

* ユーザーのデータ
* ユーザーのプリファレンス
* 提供サービスの設定
* ドメイン設定

[[MIG-88-q-will-i-lose-my-shares-will-i-need-to-re-configure-all-my-shares]]
=== Q: 共有は破棄されますか？ 既存の共有は全て再設定する必要がありますか？

いいえ、そのようなことありません。

[[MIG-88-q-how-should-i-transfer-the-exported-data-between-my-servers]]
=== Q: エクスポートデータのサーバー間での転送はどのように行なえばよいでしょうか。

転送手段は必要性に沿うものであれば、何でもかまいません。何を求めているのか、それだけは整理しておく必要はあります。

迅速なデータ移動が必要な場合、サーバー間でのUSBディスクの物理移動という手段は適していないかもしれません。

信頼性のおける手段でのデータ移動が必要な場合、お使いのインターネット回線が不安定ならSSHFS経由でエクスポートフォルダを移行先サーバーにリンクさせる手段は適していないかもしれません。
