[[provisioning_user_accounts]]
= ユーザーアカウントのプロビジョニング
:toc:

アカウントがプロビジョニングされると、システム管理者はメールボックスを作成し、当初のメールアドレスを設定し、{product-name}のアプリケーションおよび機能を使用するために提供サービスを適用します。

アカウントを1つずつ設定することも、別サーバーから複数の既存アカウントを移行することもできます。

== ユーザーアカウントを作成する

ユーザーアカウントを追加する前に、使用する機能やアクセス権限を決める必要があります。対象の機能を持つ提供サービスをアカウント作成時に設定することも可能ですし、機能をアカウントに個別設定することも可能です。詳細は
<<class_of_service_and_accounts,アカウントの提供サービスについて>> を参照してください。

アカウントへ設定した提供サービスに適切な機能が備わっている場合、アカウントに個別設定を追加で行なう必要はありません。
アカウントを作成するとZimbraのLDAPサーバーに適切な情報が設定されます。ユーザーが最初にログインしたとき、あるいはユーザーアカウント宛にメッセージが配信されたとき、メールボックスサーバー上にそのメールボックスが作成されます。

標準のアカウントを作成します。

管理コンソール: ::
*ホーム -> 3 アカウントの追加 -> 1. アカウントを追加*

. *アカウント名* セクションにて、必要最低限の情報であるアカウント名と姓を入力します。
+
デフォルト提供サービスが自動適用されます。

. *完了* をクリックし、アカウントを作成します。

続けて、個々のアカウントの特性や機能を設定することができます。アカウントに対する変更内容は提供サービスにオーバーライドします。

== 既存のアカウントの移行およびアカウントメールのインポート

--
[WARNING]
Zimbra 管理コンソールのUI上での ZCS アカウント移行がサポート終了しており、2019年12月17日までテクニカルガイダンス期間となります。
なお、すべてのアカウント移行の代替案として、
https://zimbra.audriga.com/[audriga社の移行ソリューション]
の利用を推奨しております。
--

管理コンソールからアカウント移行用ウィザードを使用して、一度に複数のアカウントをプロビジョニングすることができます。一般IMAPサーバーや別の{product-abbrev}
サーバーからアカウントをインポートできます。

[NOTE]
7.2以降の{product-abbrev}に存在するアカウントのみ{product-abbrev} 8へ移行できます。

また、カスタム作成したXMLファイルからプロビジョニング対象のアカウント名をインポートすることも可能です。

移行用ウィザードで、アカウントのプロビジョニングとデータのインポートを一度に実行できます。または、1回目のウィザードでアカウントのプロビジョニング、2回目でそのアカウントにデータをインポートできます。

既存のLDAPディレクトリやXMLファイルからアカウントレコードを取得する場合、新たに作成するアカウント用パスワードの要件を設定しておく必要があります。選択肢には、アカウントごとにランダムなパスワードを自動生成する方法と全アカウントに同一パスワードを設定する方法があります。また、初回ログイン時にユーザーにパスワードを変更させることもできます。

プロビジョニングが完了すると、このウィザードが新規アカウント一覧の.csvファイルを作成します。このファイルに生成されたパスワードも含まれています。今後の参照用にダウンロードしておくことを推奨します。ただし、ファイルは安全な場所に格納してください。プロビジョニングしたアカウントのパスワード情報が含まれているからです。

スプリットされたドメイン環境を使用している場合、ウィザードにSMTPのホストとポートを設定できます。スプリットされたドメイン環境に関する詳細は以下のWiki記事を参照ください。
https://wiki.zimbra.com/wiki/Split_Domain

[[migrating_accounts]]
=== Zimbraサーバーからアカウントを移行する

{product-abbrev} 7.2.0以降に依存しているアカウントを{product-abbrev} 8へ移行できます。

管理コンソール: ::
*ホーム -> 3 アカウントの追加 -> 3. 移行と共存*

// list
. *メールサーバーの種類* にて、 *{product-name}* を選択します。

. アカウントをプロビジョニングしている場合、*アカウントレコードをインポートしますか* に *はい* を選択します。メールのデータを今回インポートしない場合、*メールをインポートしますか* に *いいえ* を選択します。

. *次へ* をクリックします。

. 概要のページに *別のZimbra LDAPディレクトリからインポート* が選択されていることを確認します。 *次へ* をクリックします。

. *一括提供オプション* のページでパスワードをランダムに設定するか、固定のパスワードを設定するかを選択します。
+
.一括提供の機能
[cols="1,2",options="header",]
|=======================================================================
|一括提供の機能 |説明

|各アカウントにランダムパスワードを生成 |

ランダムパスワードの生成を選択した場合、パスワードの長さを設定する必要があります。パスワードは6から64文字まで設定可能です。

デフォルトは8文字です。

ランダムパスワードの生成を使用する場合、ユーザーへパスワードを伝えるためにアカウントとパスワードが発行される*.csvファイルをダウンロードする必要があります。


|すべての新規アカウントに同じパスワードを使用 |
すべての新規アカウントに同様のパスワードを使用するを選択した場合、使用するパスワードを入力します。

|初回ログイン後にパスワードの変更をユーザーに要求 |
ユーザーの初回ログイン時にパスワード変更を強制するようになるため、このオプションの使用を推奨します。

|SMTPホスト / SMTPポート |
スプリットのドメイン環境の場合、SMTPのホスト名とポートを指定します。

|=======================================================================

. *次へ* をクリックします。

. *ディレクトリ接続* のページでサーバーへ接続する情報を入力します。
+
.ディレクトリ接続のオプション
[cols="1,2a",options="header",]
|=======================================================================
|ないドメインを自動的に作成 |詳細

|ないドメインを自動的に作成 |
このオプションを有効にすると、アカウントのインポート時、アカウントのドメインが存在しない場合にドメインを作成します。

このオプションを有効にしない場合、サーバーに存在しないドメインのアカウントは作成されません。無効にすると、事前に作成した特定のドメインのアカウントのみを簡単にインポートできます。


|取得する最大レコード数 |
一度にインポートできる最大のアカウント数を指定します。基準は無制限 (0) となっています。

|サーバー名、LDAP URL、ポートおよびSSLを使用|
* LDAP URLは `ldap://<ldapdirectory.example.com>` の形で入力します。
* デフォルトのポートは389ですが、変更できます。
* SSLを使用している場合、チェックします。

|バインドDN |
Zimbraの設定はデフォルトで以下となります。
`uid=zimbra,cn=admins,cn=zimbra`

|バインドパスワード |
サーバーのパスワードを入力します。

|LDAPフィルター |
LDAP検索フィルターを指定します。インポートしたいアカウント情報の種類の検索条件を定義できます。デフォルトのフィルター (*objectclass=zimbraAccount*)
では、メールアドレス、アカウントIDおよびアカウントの属性が含まれています。

|LDAP検索ベース |
LDAP全体に検索するサブセクションを指定します。

|=======================================================================

. *次へ* をクリックします。
+
*アカウント移行のウィザード* は指定したディレクトリサーバーへ接続し、確認したドメイン数、アカウント数、そして{product-abbrev}上で既に存在しているアカウント数を取得し、レポートとして表示します。また、指定したパスワードのオプションも表示します。

.  発行したレポートの確認後、*次へ* をクリックします。  アカウントは {product-name} のサーバーにプロビジョニングされます。

.  プロビジョニングされたアカウントとパスワードが記載されている.csvファイルをダウンロードします。なお、ウィザードを終了すると、発行した.csvファイルが自動的に削除されるため、再ダウンロードおよび再発行することができません。ご注意ください。

=== 一般IMAPサーバーからアカウントを移行する

以下の手順にて、IMAPよりZimbraサーバーへアカウントをプロビジョニングできます。

管理コンソール: ::
*ホーム -> 3 アカウントの追加 -> 3. 移行と共存*

// list
. *メールサーバーの種類* にて、*一般IMAPサーバー* を選択します。

. アカウントをプロビジョニングしている場合、「アカウントレコードをインポートしますか」に *はい* を選択します。メールのデータを今回インポートしない場合、「メールをインポートしますか」に *いいえ* を選択します。

. *次へ* をクリックします。

. *概要* のページで「別のZimbra LDAPディレクトリからインポート」が選択されていることを確認します。  *次へ* をクリックします。

. *一括提供オプション* のページでパスワードをランダムに設定するか、固定のパスワードを設定するかを選択します。
+
.一括提供の機能
[cols="1,2",options="header",]
|=======================================================================
|一括提供の機能 |説明

|各アカウントにランダムパスワードを生成 |
ランダムパスワードの生成を選択した場合、パスワードの長さを設定する必要があります。パスワードは6から64文字まで設定可能です。

デフォルトは8文字です。

ランダムパスワードの生成を使用するを選択した場合、ユーザーへパスワードを伝えるためにアカウントとパスワードが発行される*.csvファイルをダウンロードする必要があります。

|すべての新規アカウントに同じパスワードを使用 |
すべての新規アカウントに同様のパスワードを使用する場合、使用するパスワードを入力します。

|初回ログイン後にパスワードの変更をユーザーに要求 |
ユーザーの初回ログイン時にパスワード変更を強制するようになるため、このオプションの使用を推奨します。

|SMTPホスト / SMTPポート |
スプリットされたドメイン環境の場合、SMTPのホスト名とポートを指定します。

|=======================================================================

. *次へ* をクリックします。

. *ディレクトリ接続* のページにサーバーへ接続する情報を入力します。
+
.ディレクトリ接続のオプション
[cols="1,2a",options="header",]
|=======================================================================
|ディレクトリ接続のオプション |説明

|ないドメインを自動的に作成 |
このオプションを有効にすると、アカウントのインポート時、アカウントのドメインが存在しない場合にドメインを作成します。

このオプションを有効にしない場合、サーバーに存在していないドメインのアカウントは作成されません。無効にすると、事前に作成した特定のドメインのアカウントのみを簡単にインポートできます。

|取得する最大レコード数 |
一度にインポートできる最大のアカウント数を指定します。デフォルトは無制限 (0) となっています。

|サーバー名, LDAP URL, ポート, およびSSLを使用 |
* LDAP URL は `ldap://<ldapdirectory.example.com>` The
* デフォルトのポートは389ですが、変更できます。
* SSLを使用している場合、チェックします。


|バインドDN |
サーバーのバインドDNを指定します。
`uid=zimbra,cn=admins,cn=zimbra`

|バインドパスワード |
サーバーのパスワードを入力します。

|LDAP フィルター |
LDAP検索フィルターを指定します。インポートしたいアカウントの情報の種類の検索条件を定義できます。デフォルトのフィルター (*objectclass=zimbraAccount*) では、メールアドレス、アカウントID、アカウント属性が含まれています。
フィルターを自由に変更できます。

|LDAP 検索ベース |
LDAP全体に検索するサブセクションを指定します。

|=======================================================================

. *次へ* をクリックします。
+
移行のウィザードは指定したディレクトリサーバーへ接続し、確認したドメイン数、アカウント数、そして {product-abbrev}上で既に存在しているアカウント数を取得し、レポートとして表示します。また、指定したパスワードのオプションも表示します。

. 発行したレポートの確認後、 *次へ* をクリックします。  アカウントは{product-name}のサーバーにプロビジョニングされます。

. プロビジョニングされたアカウントとパスワードが記載されている.csvファイルをダウンロードします。なお、ウィザードを終了すると、発行した.csvファイルが自動的に削除されますので、再ダウンロードおよび再発行することができません。ご注意ください。

=== XMLファイルからアカウントを移行する

インポートするアカウントの情報をXMLファイルに保存し、XMLファイルをZimbraへアップロードすることで、アカウントをプロビジョニングできます。

管理コンソール: ::
*ホーム -> 3 アカウントの追加 -> 3. 移行と共存*

// list
. *メールサーバーの種類* にて、元のサーバーの種類を選択します。

. アカウントをプロビジョニングしている場合、「アカウントレコードをインポートしますか」に *はい*
を選択します。メールのデータを今回インポートしない場合、「メールをインポートしますか」に *いいえ*
 を選択します。

. *次へ* をクリックします。

. *概要* のページに *XMLファイルからインポート* を選択し
*次へ* をクリックします。

. XMLファイルの横にある *参照* ボタンをクリックし、XMLファイルを選択します。*次へ* をクリックするとアップロードします。

. オプションを確認のページにて、XMLファイルに確認したドメイン数、アカウント数、そして{product-abbrev}上で既に依存しているアカウント数をレポートとして表示します。また、指定したパスワードのオプションも表示します。

. 内容に問題がない場合、*次へ* をクリックします。内容が正常ではない場合、XMLファイルを修正してから進みます。
+
*次へ* をクリックした場合、XMLファイルに確認したアカウントは{product-name}サーバーへプロビジョニングされます。

. プロビジョニングされたアカウントとパスワードが記載している.csvファイルをダウンロードします。なお、ウィザードを終了すると、発行した.csvファイルが自動的に削除されますので、再ダウンロードおよび再発行することができません。ご注意ください。

=== 特定のアカウントへメールをインポートする

メールのインポートをしたいアカウントリストを指定する場合、アカウントを選択するか、XMLファイルでアカウントを選択することで、指定できます。

[NOTE]
この手順の作業を行なう前に、アカウントは{product-abbrev} サーバー上にプロビジョニングされていなければなりません。

管理コンソール: ::
*ホーム -> 3 アカウントの追加 -> 3. 移行と共存*

// list
. *メールサーバーの種類* にて、元のサーバーの種類を選択します。

. *アカウントレコードをインポートしますか* に *いいえ* を選択します。
. *メールをインポートしますか* に *はい* を選択します。

. *次へ* をクリックします。

. *インポートのオプション* のページで、メールをインポートするアカウントを指定する方法を選択します。

. *次へ* をクリックします。
+
インポートするアカウントを選択する場合、手順7へ進みます。
XMLファイルでアカウントを指定する場合、手順9へ進みます。

. インポートするアカウントを選択する場合、検索ボックスで追加するアカウントを検索します。ドメイン、またはユーザー名で検索できます。検索するテキストを入力せずに「検索」をクリックすると、すべてのアカウントが結果に表示されます。
+
メールデータをインポートするアカウントを左から選択し、「追加」のボタンをクリックし、右の *データインポートのためのアカウント*  リストへ移動します。

. *次へ* をクリックします。

. XMLファイルでアカウントを指定する場合、「参照」より使用するXMLファイルを選択します。

. *次へ* をクリックします。

. IMAP接続の詳細ページにて、エクスポートするサーバーのIMAPへ接続するための情報を記載します。IMAPのホスト名、ポートおよび管理者のログイン情報が必要となります。IMAPサーバーの情報入力を完了します。

. *次へ* をクリックします。

. オプションの確認ページにて、データのインポート詳細を確認します。問題がない場合、*次へ* をクリックし、データのインポートを開始します。

=== XMLファイルの例

アカウントのプロビジョニングやデータのインポートで使用するXMLファイルの例を以下に紹介しています。XMLファイルを作成する際にご参照ください。

.アカウントのプロビジョニングにXMLファイルを使用する
====
メールデータをインポートせずに、複数のアカウントをプロビジョニングする場合、以下のようなXMLファイルを使用します。

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ZCSImport>
<ImportUsers>
<User>
<sn>Sample</sn>
<givenName>Sam</givenName>
<displayName>Sam Sample</displayName>
<RemoteEmailAddress>ssample@example.com</RemoteEmailAddress>
<password>test123</password>
<zimbraPasswordMustChange>TRUE</zimbraPasswordMustChange>
</User>
<User>
<sn>Zackry</sn>
<givenName>Zak</givenName>
<displayName>Zak Zackry</displayName>
<RemoteEmailAddress>zzackry@example.com</RemoteEmailAddress>
<password>test123</password>
<zimbraPasswordMustChange>TRUE</zimbraPasswordMustChange>
</User>
</ImportUsers>
</ZCSImport>
----
====

.外部にホストしているドメインからアカウントのプロビジョニングにXMLファイルを使用する
====
以下の例では、メールデータをインポートせずに、外部にホストしているドメインのアカウントを複数、プロビジョニングします。

下記例の場合、新しく作成したアカウントの `zimbraMailTransport` の属性に {product-abbrev}サーバーの替わりに、指定している外部のSMTPサーバーが設定されます。

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ZCSImport>
<SMTPHost>smtp.example.com</SMTPHost>
<SMTPPort>25</SMTPPort>
<ImportUsers>
<User>
<sn>Sample</sn>
<givenName>Sam</givenName>
<displayName>Sam Sample</displayName>
<RemoteEmailAddress>sam@example.com</RemoteEmailAddress>
</User>
<User>
<sn>Zackry</sn>
<givenName>Zak</givenName>
<displayName>Zak Zackry</displayName>
<RemoteEmailAddress>zzackry@example.com</RemoteEmailAddress>
</User>
</ImportUsers>
</ZCSImport>
----
====

.メールのインポートにXMLファイルを使用する
====

以下の例では、{product-abbrev}でアカウントをプロビジョニングせずに、IMAP通信でGmailのアカウントからメールデータをインポートします。メールデータをインポートする前に、アカウントが{product-abbrev}にプロビジョニングされている必要があります。

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ZCSImport>
<IMAPHost>imap.gmail.com</IMAPHost>
<IMAPPort>993</IMAPPort>
<ConnectionType>ssl</ConnectionType>
<UseAdminLogin>0</UseAdminLogin>
<ImportUsers>
<User>
<sn>Sample</sn>
<givenName>Sam</givenName>
<displayName>Sam Sample</displayName>
<RemoteEmailAddress>sam@example.com</RemoteEmailAddress>
<RemoteIMAPLogin>sam@example.com</RemoteIMAPLogin>
<remoteIMAPPassword>test123</remoteIMAPPassword>
</User>
</ImportUsers>
</ZCSImport>
----
====

== 外部LDAPから新しいアカウントを自動的にプロビジョニングする

外部LDAPからの新しいアカウントの自動プロビジョニングは、CLIで対応します。本項で、サポートしているCLI属性と自動プロビジョニング方法について説明します。

=== 概要

{product-abbrev}のドメインに、外部LDAP認証、preauth、SPNEGOのような外部LDAPの認証方法を設定している場合、{product-abbrev}にユーザーアカウントを自動作成できます。プライマリのメールアドレスやデフォルトのアカウント属性は外部のディレクトリよりマッピングされます。外部ディレクトリのデータからのアカウントの新規作成方法や作成タイミングを設定できます。

下記３つのモードが自動プロビジョニング設定でサポートされています。

[cols="1,5",options="header",]
|=======================================================================
|モード |説明

|Eagerモード |
{product-abbrev} は外部のディレクトリを定期的に確認し、新規アカウントを自動作成します。新規ユーザーの確認のために外部ディレクトリをポーリングする頻度、各回における処理可能な最大ユーザー数、特定のサーバーでアカウントの自動プロビジョニング対象としてスケジューリングするドメインを管理できます。

概要:
<<eager_mode_configuration,Eagerモードの自動プロビジョニングを設定する>>

| Lazyモード |
ユーザーの初回ログイン時、自動プロビジョニングをサポートしている認証方法の１つでZWCにログインしたときにそのユーザーが{product-abbrev}ディレクトリに存在しなければ、そのユーザーのために{product-abbrev}内に新規アカウントが自動作成されます。

概要:
<<lazy_mode_configuration,Lazyモードの自動プロビジョニングを設定する>>

|Manualモード |
自動プロビジョニングは実行されません。代わりに、管理者がマニュアル操作で、設定されている外部自動プロビジョニングLDAPソースを検索し、その検索結果から１つエントリを選択し、その外部エントリのために該当のZimbraアカウントを作成します。

Guidelines are provided in
<<manual_mode_configuration,Manuralモードの自動プロビジョニングを設定する>>

|=======================================================================

自動でアカウント作成する際、アカウント名 (@の左にある部分) は外部ディレクトリに存在するユーザー属性よりマッピング (取得) されます。これは `zimbraAutoProvAccountNameMap` 内に定義します。また、姓、名、電話番号、住所、など、他のアカウント情報は `zimbraAutoProvAttrMap` に指定された属性にて、外部ディレクトリからマッピング (取得) されます。Zimbraの属性へマッピングすべき属性を決めるため、外部ディレクトリの属性をレビューすることができます。

自動作成したアカウントへの提供サービスの設定はマニュアル操作で作成したアカウントと同じように決定します。

* ドメインに特定の提供サービスを設定している場合、新規作成したアカウントにはその提供サービスが設定されます。

* ドメインに特定の提供サービスを設定していない場合、 {product-abbrev} のデフォルト提供サービスが設定されます。

アカウントが自動作成された場合、サーバーから *ようこそ* のメッセージが自動で受信されるように設定できます。ドメイン
`AutoProvNotification` 属性にてメッセージの件名や本文を管理します。

=== 自動プロビジョニングの属性

本項では、外部LDAPディレクトリから新規アカウントの自動プロビジョニングを設定するときに使用できる `zmprov` コマンドを紹介します。

`zimbraAutoProvMode`::
 EAGER、LAZY、MANUALから自動プロビジョニングで使用するモードを設定します。１つのドメインでモードを複数、有効化できます。

`zimbraAutoProvAuthMech`::
LDAP, PREAUTH, KRB5, SPNEGOのいずれかから認証方法を設定します。LAZYモードの場合に有効です。
ユーザーが指定した外部認証方法で認証された後、ユーザーのアカウントがZimbraのディレクトリに存在していない場合、アカウントがZimbraのディレクトリに自動作成されます。

`zimbraAutoProvLdapURL`::
自動プロビジョニングで使用する外部LDAPソースのLDAP URLを設定します。

`zimbraAutoProvLdapStartTlsEnabled`::
自動プロビジョニングで外部LDAPサーバーにアクセスする際、StartTLSのプロトコルを使用するか否かです。デフォルトの設定はFALSEです。

`zimbraAutoProvLdapAdminBindDn`::
自動プロビジョニングで使用するLDAP検索のバインドDNを設定します。

`zimbraAutoProvLdapAdminBindPassword`::
自動プロビジョニングで使用するLDAP検索の管理バインドパスワードを設定します。

`zimbraAutoProvLdapSearchBase`::
自動プロビジョニングで `zimbraAutoProvLdapSearchFilter` と共に使用するLDAP検索ベースを設定します。 +
設定されていないとき、LDAPのルートDSEが使用されます。

`zimbraAutoProvLdapSearchFilter`::
自動プロビジョニングで使用するLDAP検索フィルターのテンプレートを定義します。LAZYモードの場合、 `zimbraAutoProvLdapSearchFilter` または
`zimbraAutoProvLdapBindDn` を設定する必要があります。
+
2つとも設定されている場合、 `zimbraAutoProvLdapSearchFilter` が優先されます。詳細は <<auto_provisioning_placeholders,プレースホルダー>> を参照してください。

`zimbraAutoProvLdapBindDn`::
自動プロビジョニングで使用するLDAP外部フィルターのテンプレートを指定します。LAZYモードの場合、 `zimbraAutoProvLdapSearchFilter` または
`zimbraAutoProvLdapBindDn` を設定する必要があります。
+
2つとも設定している場合、 `zimbraAutoProvLdapSearchFilter` が優先して適用されます。詳細は <<auto_provisioning_placeholders,プレースホルダー>> を参照してください。

`zimbraAutoProvAccountNameMap`::
アカウント名のローカル部分を含む外部ディレクトリ内の属性名を定義します。この名前は、Zimbraアカウントの作成に使用されます。指定されていないとき、アカウント名のローカル部分は、Zimbraへの認証に使用された最初のユーザー名になります。

`zimbraAutoProvAttrMap`::
外部エントリの属性値から {product-abbrev} のアカウント属性へマッピングするための属性を定義します。値は `{外部属性}={zimbra属性}` 形式にします。設定されていないとき、外部ディレクトリの属性は {product-abbrev} アカウントへ取り込まれません。
+
[IMPORTANT]
--
誤ったマッピング設定は、アカウント作成が失敗する原因となります。下記は不正なマッピング条件の例です。

* 無効な外部ソース属性名
* 無効なzimbra属性名
* 外部ソース属性には複数の値があるが、Zimbra属性の値は1つのみ
* 構文の違反 (例えば、外部ソース属性のStringだが、Zimbra属性がInteger型など)
--

`zimbraAutoProvNotificationFromAddress`::
新規アカウントが受信する「ようこそ」メッセージの *差出人* を定義します。設定されていないとき、メール通知は新規作成されたアカウントに送信されません。

`zimbraAutoProvNotificationSubject`::
ユーザーの自動プロビジョニング時にユーザーに送信される通知メッセージの件名の作成に使われるテンプレート。
+
使用可能な変数: `${ACCOUNT_ADDRESS}`, `${ACCOUNT_DISPLAY_NAME}`

`zimbraAutoProvNotificationBody`::
ユーザーの自動プロビジョニング時にユーザーに送信される通知メッセージの本文の作成に使われるテンプレート。
+
使用可能な変数: `${ACCOUNT_ADDRESS}`, `${ACCOUNT_DISPLAY_NAME}`

`zimbraAutoProvListenerClass`::
自動プロビジョニングのリスナーのクラス名を定義するドメイン設定。使用するクラスは
`com.zimbra.cs.account.Account.AutoProvisionListener` のインターフェースを実装している必要があります。各アカウントがZimbraに自動作成された後、独立したリスナーが呼ばれます。サーバーの拡張としてリスナーをプラグインすると、外部LDAPディレクトリでアカウントの自動プロビジョニング状況を更新するなどのタスク管理が可能になります。
+
EAGERプロビジョニングの各インターバルで、{product-abbrev} は `zimbraAutoProvLdapSearchFilter`
の値に基づきLDAP検索を実行します。検索結果のエントリはこのバッチでの自動プロビジョニング候補です。 `zimbraAutoProvLdapSearchFilter`
には、{product-abbrev}の既存アカウントがヒットしない条件を設定しておく必要があります。設定されていないとき、同じアカウントが何度も作成されます。
{product-abbrev}でアカウントの自動プロビジョニングが完了すると、
`com.zimbra.cs.account.Account.AutoProvisionListener.postCreate
(Domain domain, Account acct, String external DN)` が自動プロビジョニングのフレームワークから呼ばれます。顧客は、AutoProvisionListenerのインターフェースを{product-abbrev}のサーバー拡張に実装して、 `AutoProvisionListener.postCreate()` を呼ばせるようにします。このpostCreateを実装すると、例えば、{product-abbrev}にプロビジョニングされたばかりのアカウントに、外部ディレクトリ属性を設定できます。この属性は、 `zimbraAutoProvLdapSearchFilter` に条件として設定できるため、このエントリは次のインターバルのLDAP検索結果に返ってこなくなります。

`zimbraAutoProvBatchSize`::
EAGER自動プロビジョニングの各インターバルで処理される最大アカウント数を定義するドメイン設定 | グローバル設定。

`zimbraAutoProvScheduledDomains`::
サーバーでのEAGER自動プロビジョニングが予定されているドメインをリストアップするサーバー属性。予定のドメインの `zimbraAutoProvMode` は EAGERモードが有効である必要があります。EAGER自動プロビジョニングについて、１つのサーバー上でドメインを複数、スケジュールできます。また、EAGER自動プロビジョニングについて、複数のサーバー上で１つのドメインをスケジュールできます。

`zimbraAutoProvPollingInterval`::
EAGERモード中の、アカウントのポーリングとプロビジョニングのインターバルを定義するドメイン設定|グローバル設定。
`zimbraAutoProvBatchSize` と
`zimbraAutoProvScheduledDomains` に設定されたドメイン数にも影響されるため、実際のインターバルはこの定義より長くなる可能性があります。
+
各インターバル中、自動プロビジョニングのスレッドは `zimbraAutoProvScheduledDomains` 内のドメインをすべて確認し、 `domain.zimbraAutoProvBatchSize` の値になるまで新規アカウントを自動作成します。この処理時間が `zimbraAutoProvPollingInterval` よりも長くなると、`zimbraAutoProvPollingInterval`
になる前に、次のインターバルがすぐに起動されます。
+
* サーバーが起動した時点でこの値が「0」の場合、自動プロビジョニングのスレッドは開始しません。
* サーバーが実行中にこの値を「0」に変更した場合、自動プロビジョニングのスレッドが終了します。
* サーバーが実行中にこの値を「0」から他の値に変更すると、自動プロビジョニングのスレッドが開始します。

[[auto_provisioning_placeholders]]
=== プレースホルダー

.自動プロビジョニング属性で利用するプレースホルダー
[cols="1,2,2",options="header",]
|=======================================================================
|タグ |説明 |結果

|%/n |ユーザー名と@ 記号  | _user1@example.com_ を返します。

|%u |@記号なしのユーザー名  | _user1_ を返します。

|%d |ドメイン  | _example.com_ を返します。

|%D |DCとしてのドメイン | _example,dc=com_ を返します。

|=======================================================================

[[eager_mode_configuration]]
=== Eagerモードの自動プロビジョニングを設定する

Eagerモードの場合、{product-abbrev} は自動プロビジョニングのため外部のディレクトリのアカウントを定期的に確認します。外部ディレクトリを確認するインターバル、各インターバルで処理可能な最大ユーザー数、自動プロビジョニング対象のサーバーやドメインを管理できます。

. {product-abbrev} のサーバーへログインし、Zimbraユーザーに切り替えます。
+
[source,bash]
----
zmprov
----

. EAGERモードを有効化します。
+
[source,bash]
----
md <example.com> zimbraAutoProvMode EAGER
----

. 各インターバルで処理可能な最大アカウント数を設定します。
+
[source,bash]
----
md <example.com> zimbraAutoProvBatchSize <#>
----

. アカウントのポーリングとプロビジョニングのインターバルを設定します。自動プロビジョニングのスレッドを起動するため、この値は「0」以外の値に設定する必要があります。デフォルトは15分です。
+
[source,bash]
----
ms <server.com> zimbraAutoProvPollingInterval <x minutes>
----

. 自動プロビジョニング対象のドメインを設定します。サーバーに複数のドメインを設定できます。
+
また、対象ドメインは複数サーバーに設定できます。
+
[source,bash]
----
ms <server.com> +zimbraAutoProvScheduledDomains <domain1.com> \
  +zimbraAutoProvScheduledDomains <domain2.com>
----

. 外部LDAPの詳細を設定します。

.. LDAP URLを設定します。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapURL "ldap://xxx.xxx.xxx.xxx:<port>"
----
+
一般的にLDAPはポート389を使用します。

.. (任意) StartTLSを有効化します。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapStartTlsEnabled TRUE
----

.. 自動プロビジョニング用のLDAP管理者バインドDNを設定します。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapAdminBindDn "cn=admin, dc=autoprov, dc=company, dc=com"
----

.. 自動プロビジョニング用のLDAP管理者の検索バインドパスワードを設定します。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapAdminBindPassword <password>
----

.. 自動プロビジョニング対象のユーザーを検索する際のテンプレートを設定します。
+
検索フィルター使用例
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapSearchFilter "(uid=<%placeholder>)"
----
+
サポート対象のプレースホルダーについては <<auto_provisioning_placeholders,プレースホルダー>> を参照してください。

..  自動プロビジョニングのLDAP検索ベースを設定します。
+
これは、ディレクトリ内のLDAP検索の開始地点です。`zimbraAutoProvLdapSearchFilter` で、と共に使用されます。設定されていないとき、LDAPディレクトリのルートである `rootDSE` が開始地点です。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapSearchBase "dc=autoprov,dc=company,dc=com"
md <example.com> zimbraAutoProvLdapBindDn <"placeholder1">
----
+
サポート対象のプレースホルダーについては<<auto_provisioning_placeholders,プレースホルダー>> を参照してください。

. (任意) 外部ディレクトリにて、アカウント名のローカル部分が依存する属性を指定します。新規アカウントを作成する際に、アカウント名のローカル部分が {product-abbrev} アカウント名として使用されます。なお、アカウント名のローカル部分を指定していない場合、 {product-abbrev}へ認証したユーザー名をローカル名として使用します。
+
[source,bash]
----
md <example.com> zimbraAutoProvAccountNameMap <value>
----

. (任意) 外部エントリの属性値から {product-abbrev} のアカウント属性へマッピングします。セットアップされていないとき、外部ディレクトリの属性は {product-abbrev} アカウントへ取り込まれません。値は `{外部属性}={zimbra属性}` 形式にします。
+
[IMPORTANT]
誤ったマッピング設定は、アカウント作成が失敗する原因となります。
+
外部エントリの値「sn」をZimbraアカウントの「displayName」にマッピングし、外部エントリの「description」の値を {product-abbrev} アカウントの「description」にマッピングします。
+
[source,bash]
----
md <example.com> +zimbraAutoProvAttrMap sn=displayName +zimbraAutoProvAttrMap description=description
----

. (任意) 新規作成アカウントに「ようこそ」のメッセージを送信したいとき、メッセージの _差出人_ を設定します。
+
[source,bash]
----
md <example.com> zimbraAutoProvNotificationFromAddress <name@example.com>
----

.  zmprovを抜けます。
+
[source,bash]
----
exit
----

[[lazy_mode_configuration]]
=== Lazyモードの自動プロビジョニングを設定する
LDAP、preauth、Kerberos 5およびSpnegoの外部認証にユーザーが認証した場合、Lazy モードの自動プロビジョニングが新規アカウントを作成します。

. {product-abbrev}のサーバーへログインし、Zimbraユーザーに切り替え、コマンドプロンプトでzmprovを入力します。

. LAZYモードを有効化します。
+
[source,bash]
----
md <example.com> zimbraAutoProvMode LAZY
----

. LAZYモードが使用する外部認証方法LDAP, PREAUTH, KRB5, SPNEGOを指定します。複数の認証方法を指定できます。
+
[source,bash]
----
md <example.com> zimbraAutoProvAuthMech <type> +zimbraAutoProvAuthMech <type2>
----

. 外部LDAPの詳細を設定します。

..  LDAP URLを設定します。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapURL "ldap://xxx.xxx.xxx.xxx:<port>"
----
+
一般的にLDAPはポート389を使用します。

..  (任意) StartTLSを有効化します。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapStartTlsEnabled TRUE
----

..  自動プロビジョニング用のLDAP管理者バインドDNを設定します。なお、
`cn=<LDAPadmin_name>, dc=autoprov, dc=<company_name>, dc=<com>` のフォーマットを使用する必要があります。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapAdminBindDn <"bindDN">
----
+
例:  `"cn=admin, dc=autoprov, dc=company, dc=com"`

..  自動プロビジョニング用のLDAP管理者の検索バインドパスワードを設定します。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapAdminBindPassword <password>
----

..  (任意) 自動プロビジョニング対象のユーザーを検索する際のテンプレートを設定します。
+
検索フィルター使用例
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapSearchFilter <"placeholder">
----
+
サポート対象のプレースホルダーについては <<auto_provisioning_placeholders,プレースホルダー>> を参照してください。
+
[NOTE]
LAZYモードにzimbraAutoProvLdapSearchFilter、またはzimbraAutoProvLdapBindDnを設定する必要があります。

..  自動プロビジョニングのLDAP検索ベースを設定します。`zimbraAutoProvLdapSearchFilter` と共に、LDAPの検索を開始する場所を指定します。なお、この値を設定しない場合、LDAPディレクトリのルートである `rootDSE` が自動的に使用します。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapSearchBase <"location">
----
+
<”location”>の例: `"dc=autoprov,dc=company,dc-com"`

..  (任意) アカウントのプロビジョニングで使用するLDAP外部DNテンプレートを設定します。
+
[source,bash]
----
md <example.com> zimbraAutoProvLdapBindDn "uid=%<placeholder1>, %<placeholder2>"
----
+
サポート対象のプレースホルダーについては<<auto_provisioning_placeholders,プレースホルダー>> を参照してください。

. (任意) 外部エントリのアカウント名のローカル部分が依存する属性を指定します。新規アカウントを作成する際に、アカウント名のローカル部分が{product-abbrev}アカウント名として使用されます。なお、アカウント名のローカル部分が指定されていない場合、{product-abbrev}へ認証したユーザー名をローカル名として使用します。
+
[source,bash]
----
md <example.com> zimbraAutoProvAccountNameMap <value>
----

. (任意) 外部エントリの属性値から {product-abbrev} のアカウント属性へマッピングします。セットアップされていないとき、外部ディレクトリの属性は {product-abbrev} アカウントへ取り込まれません。値は `{外部属性}={zimbra属性}` 形式にします。
+
外部エントリの値　*sn* をZimbraアカウントの *displayName* にマッピングし、外部エントリの「description」の値を {product-abbrev} アカウントの「description」にマッピングします。
+
[source,bash]
----
md <example.com> +zimbraAutoProvAttrMap sn=displayName +zimbraAutoProvAttrMap description=description
----

. (任意) 新規に作成したアカウントへ *ようこそ* のメッセージを送信希望の場合、メッセージの _差出人_ を設定します。
+
[source,bash]
----
md <example.com> zimbraAutoProvNotificationFromAddress <name@example.com>
----

. zmprovを抜けます。 +
 `exit`

[[manual_mode_configuration]]
=== Manuralモードの自動プロビジョニングを設定する

外部LDAPサーバーとの自動プロビジョニングを無効にするには、Manualモード設定を使用します。

. {product-abbrev}サーバーへログインし、Zimbraユーザーに切り替え、コマンドプロンプトでzmprovを入力します。

. Manualモードを有効化します。
+
[source,bash]
----
md <example.com> zimbraAutoProvMode MANUAL
----

== リソースを管理する

「リソース」とは、会議などに予約できる場所や機器のことです。
各会議室や、場所を固定しない機器 (視聴覚の機器、など) は、リソースアカウントとしてセットアップします。管理コンソールの *管理 >
リソース* にて、 {product-name}に設定しているリソースアカウントを管理できます。

ユーザーアカウントのカレンダー機能で、リソースをカレンダーに予約できます。リソースアカウントは、利用可･不可に基づき、予約依頼を自動で許可・拒否します。

管理者はリソースのメールボックスを定期的に監視する必要はありません。リソースのメールボックス内容は、メールの削除ポリシーにより、自動削除されます。

リソースウィザードを使用して、リソース設定を行ないます。以下のリソース詳細をアカウントに設定できます。

* リソースの種類：場所または機器

* 予定のポリシー

* カレンダー招待のコピーを転送するメールアドレス

* リソースの説明

* 問題が発生した際に対応可能の連絡先情報

* 場所の情報：ビル名、住所、部屋名、収容人数など

* リソースの自動返信メッセージや署名のカスタマイズ

リソースアカウントを作成するとLDAPサーバーにディレクトリのアカウントが作成されます。

リソースを予約するには、リソース機器や場所を会議に招待します。リソースの選択時、リソースの説明、連絡先、空き状況を閲覧できます。

会議の招待が送信されると、リソースアカウントにメールが送信されます。予定ポリシーに従い、リソースが空いていれば、リソースのカレンダーに会議が自動追加されてそのリソースは予約済みに表示されます。

=== リソースの予定ポリシーを設定する

リソースの予定ポリシーでは、リソースカレンダーの維持方法を設定できます。以下の予定ポリシーを使用できます。

* *繰り返し予約を自動拒否* -- リソースが1度に1つの会議にしかスケジューリングできないとき、この値は有効です。このリソースに繰り返し予約を入れることはできません。

* *使用可能な場合には自動的に受け入れ、競合する場合には自動的に拒否する* -- このオプションが選択されているとき、リソースが予約済みでない限り、自動で依頼が許可されます。リソースの空き時間が閲覧可能です。自動拒否のルールを編集して、競合する予約を許可できます。

* *手動で受け入れ、競合する場合には自動的に拒否する* -- このオプションが選択されているとき、競合する予約は全て、リソースアカウントに自動で拒否されます。競合していない予約依頼は、リソースカレンダーに仮予約としてマークされるため、マニュアル操作での許可が必要となります。これをセットアップするなら、招待をマニュアル操作で許可できるアカウントに招待のコピーが転送されるように設定する必要あります。自動拒否のルールを編集して、競合する予約を許可できます。

* *常に自動的に受け入れる* -- リソースアカウントは予約された予定を自動的に許可します。この場合、リソースの空き状況は反映されないため、複数の会議が同じ時間帯にそのリソースを予約する可能性があります。リソースは常に招待を受け入れるため、社外でよく会議に使う場所を参加者への招待に含めたい場合に使用することを推奨します。

* *自動的に受け入れない、自動的に拒否しない* -- リソースアカウントはマニュアル操作で管理されます。委任されたユーザーがリソースアカウントにログインし、すべての依頼をマニュアル操作で許可・拒否する必要があります。

*競合のルール* -- 管理者は、競合する場合には自動的に拒否するように設定されているアカウントに、しきい値をセットアップできます。部分的に許される繰り返し予定の全体に対するパーセンテージや、競合数として、設定します。

*競合の最大許容数* や *競合の最大許容パーセント* は、依頼された繰り返し予定日全て、使用できない場合も繰り返し予定がスケジューリングできるように設定されます。

競合があったとしても、競合の最大許容数または競合の最大許容パーセントのいずれかに達するまで、リソースは予約を許可します。部分予約が機能できるように、両項目に0以外の値を設定しておく必要があります。

==== リソースアカウントを管理する

リソースアカウントとしてログインすると、リソースのプリファレンスを設定できます。 *リソースアカウントのプリファレンス > カレンダー* から、ユーザーによるリソースカレンダー管理を設定できます。リソース管理には、次のオプションがあります。

* 招待の転送先。アカウントのプロビジョニング時に転送先アドレスがセットアップされていた場合、管理者はそのアドレスを変更できます。

* リソースを使用できるユーザー。アクセス許可セクションの招待のところから、
*内部ユーザーのみが自分を予定の招待できるようにする* を選択し、適切なユーザーメールアドレスをこのリストに追加してください。

リソースカレンダーを特定のユーザーに共有して管理者権限を付与することができます。管理者として委任されたユーザーは、そのカレンダーに対する全ての管理者権限を持つことになります。招待について、閲覧、編集、追加、削除、許可、拒否ができます。
