[[voice_service]]
= ボイスサービスの利用について
:toc:

Unified Communications(UC)は様々なモードの通信サービスを統合したものです。これによりユーザーはボイスメールで受信したものをClick-to-Callのような別のサービスで返信することが可能になります。

Zimbraではリアルタイムのボイス、電話、およびオンライン状態に含まれている通信サービスを非リアルタイムの電子メールやボイスメールのサービスと連携して機能しています。Zimbra Collaboration Server(ZCS)のボイスサービス機能には、ビジュアルボイスメール、Click-to-Call、およびオンライン状態（Ciscoのみ）のサービスが含まれています。また、ZCSはCiscoやMitelのサーバーをサードパーティ製のボイスサーバー（UCサーバー）として使用し、ZCSとZimbraウェブクライアント（ZWC）の通話を仲介します。

*注記:*  UCシステム管理者はUCサーバーのドキュメンテーションを参照し、UCサーバーの設定や管理をする必要がございます。

ボイスサービスは管理コンソールから有効化することができます。ユーザーはZWCのボイスタブからボイスサービス機能を使用します。

ユーザーがZWCアカウント上でボイスサービスへログインする際、UCサーバーへログインされます。初期のユーザーセットアップ完了後、ボイスサービスがシームレスとなり、アカウントに他の項目の設定は必要ありません。

ボイスサービス機能は以下を含みます。

* *Visual Voice Mail:* ボイスタブより、ユーザーがボイスメールを簡単に閲覧や傍聴、および発信者の名前、時間情報とメッセージの長さの詳細も確認できます。ユーザーは、メッセージの発信者への折り返し電話、メッセージを電子メールでの転送や返信、メッセージの保存や削除、および新規ボイスメッセージの受信通知などを設定することができます。サポートされているオーディオ形式にはWAVとMP3が含まれています。
* *Click-to-Call:* ZWCアカウントから電話発信を可能にする機能。ユーザーはメール本文中の電話番号をハイライトし、クリックすることでの電話発信、またはアドレス帳から連絡先の電話番号を選択で電話発信できます。ユーザーが登録された物理的な電話機、または仮想の電話機を経由し、宛先への通話が実行されます。Click-to-Callでは電話機から番号を入力する必要がなくなります。
* *Click-to-Chat:* (Ciscoクライアントのみ)CiscoのJabberクライアントとZCSを使用し、連絡先とチャットする機能。なお、連絡先のIMアドレスが既に連絡先情報として保存されている必要があります。連絡先の情報にアクセスし、IMのリンクをクリックすることで、チャットが開始します。
* *Presence:* (Ciscoクライアントのみ)ユーザーや連絡先が連絡可能な状態にあるかリアルタイムで表示する機能。CiscoのJabberを使用する場合、ユーザーのオンライン状態は手動、または自動で設定することができます。例えば、ユーザーが電話の通話を受けている場合、オンライン状態は自動的に「on a call」へ設定されます。設定可能なオンライン状態は available （連絡可能）、 away （離席）、on a call: （通話中）、または do not disturb （多忙）となります。

== 設定手順について
ボイスサービスの作成には、以下の設定手順を実行してください。

  . 適切なサーバーURLへアクセスします。詳細については「サードパーティのUnified Communicationsサーバーに利用について」 を参照ください。
  . ボイスサービスを作成します。詳細については「ボイス/チャットサービスの作成」 を参照ください。
  . ボイスサービスとボイス機能を有効化します。詳細については「ボイス/チャットのサービスを有効にする」 を参照ください。ボイス機能を有効化にするとZWC上にボイスのタブが表示されます。
  . ご利用のベンダーサーバーに対して、適切なZimletを有効化します。詳細については 「ボイス/チャットのZimletを有効にする」 を参照ください。
  
== ボイスサービスの利用条件
ZCSボイスサービスを使用するために以下の条件が必要です。

* *ボイスサービスのライセンス:* ボイスサービスの機能が含まれているZCSのライセンスが必要です。適切なライセンスを取得するには ライセンス のチャプターを参照ください。
* *Unified Communications Server（統合コミュニケーションのサーバー）:* Cisco、およびMitelのサードパーティ製Unified Communicationsサーバーの必要条件は以下に記載しています。以下の「サードパーティのUnified Communicationsサーバーに利用について」に詳細が記載されている通り、UCサーバーからのURLはZCSのボイスサービスの設定に使用されます。
** *Ciscoについて:*
*** *Cisco Unity Connection (UC) 8.5以降が必要* Cisco UCがボイスサービス設定に使用するボイスURLを生成します。
*** *Cisco Unified Communications Manager (CUCM) 7.1(3):* Click-to-Call機能を使用するため、Web Dial サービスを有効化する必要があります。Cisco CUCMがボイスサービス設定で使用される通話URLを生成します。
*** *Cisco Unified Presence Server (CUPS) 8.0:* Cisco CUPS を使用するためにPresence Webサービスを有効化にし、オンライン状態を監視するアプリケーションのユーザーも作成する必要があります。Cisco Communications Manager (CUCM) > User Managementにて設定できます。Cisco CUPSはボイスサービス設定で使用されるオンライン状態のURLを生成します。
*** *UCでの統合にCisco Jabber のクライアントが提供されます。*
** *Mitelについて:*
*** *Mitel Unified Communicator Advanced (Mitel UCA) 5.0.23.0 リリース以降が必要です。* Mitel UCAがボイスサービス設定に使用されるURLを生成します。
* *ZCS Zimlets:* Voice Preferences Zimlet, Cisco Click2Call Zimlet や Mitel Click2Call Zimlet  
  
== サードパーティのUnified Communicationsサーバーに利用について
ZCSボイスサービスはサードパーティ製のUnified Communications(UC)サーバーを経由し、ZCSとUCサーバー間の通話をブリッジします。UCサーバーのドメイン情報は許可されたプロキシーのドメインとしてZCSの管理コンソールへ追加されます。そのため、Click-To-Callやオンライン状態の機能、などにて、Zimletがボイスサービスの設定に使用される場合、UCサーバーへリクエストすることが
可能されます。UCサーバーがボイスサービスを設定する際、以下のURLを使用します。

== CiscoのURLについて

* *ボイスのURL:* ボイスURLはCisco UCサーバーのURLです。例として、「 https://xx.xx.xxx.xx 」のようなURLになります。ZCSサーバーはこのURLを使用し、Cisco UCサーバーからユーザーのボイスメールをユーザーの代理で取得します。
* *通話のURL:* 通話のURLはCisco CUCMサーバーのURLです。例として、https://xx.xx.xxx.xx/webdialer/services/WebdialerSoapService70 のようなURLになります。ZCSのCisco Click2Call ZimletがこのURLを使用し、通話をCisco CUCMサーバーへ仲介します。
* *オンライン状態のURL:* オンライン状態のURLはCisco CUPSサーバーのURLであり、セッションIDを生成するために使用されます。例として、 http://xx.xx.xxx.xx:8082/presence-service/users のようなURLになります。ZCSのEmail ZimletがこのURLを使用し、連絡先のオンライン情報をCisco CUPSのサーバーへFetchのリクエストを送信します。

*注記:* アプリケーションのユーザー名とパスワードはCisco Unified Presence Server(CUPS)で作成できます。

== MitelのURLについて
* *ボイスのURL:* ボイスのURLはMitelサーバーのURLです。例として、「 https://xx.xx.xxx.xx 」のようなURLになります。ZCSサーバーはこのURLを使用し、Mitel Voiceサーバーにユーザーのボイスメールをユーザーの代理で取得します。
* *通話のURL:* 通話のURLはMitelサーバーのURLです。例として、https://xx.xx.xxx.xx/webdialer/services/WebdialerSoapService70 のようなURLになります。ZCSのMitel Click2Call ZimletがこのURLを使用し、通話をMitelサーバーへ仲介します。
* *ユーザーのURL:* ユーザーのURLはMitelサーバーのURLです。ZCSはユーザー確認や認証でこのURLを使用します。

== ボイス/チャットサービスの作成
ZCSでボイス/チャットサービスを作成する際、ZCSとサードパーティ製のUCサーバーへの仲介が有効化されます。サービスはドメイン、提供サービス（COS）、また特定のユーザーに作成されます。

  . ZCS管理コンソールにて、 *ホーム>設定>ボイス/チャットサービス* のページを開きます。
  . 画面右上のギアアイコンより 、*新規* をクリックします。
  . ボイス/チャットベンダーの選択ページにて、ドロップダウンメニューからご利用のベンダーを選択します。
  . *OK*のボタンをクリックします。
  . ドメイン、COS、または特定のユーザーへボイスサービスを追加するため、 *表示名* を設定します。
  . 利用希望のボイスサービスに適切なURLを追加します。
  . *OK* のボタンをクリックします。

== オンライン状態を設定する（Ciscoのみ）
オンライン状態を設定する場合、オンライン状態のセッションIDを作成する必要があります。

  . ZCS管理コンソールにて、 *設定>ボイス/チャットサービス* のページを開きます。
  . オンライン状態のセッションIDを発行するボイスサービスを選択します。
  . 画面右上のギアアイコンより *セッションIDの生成* をクリックします。
  .  *オンライン状態のユーザー名* 、および *オンライン状態のパスワード* を入力します。これらの情報はオンライン状態のサーバーが使用し、ZCSとUCサーバーにボイスの接続を認証します。これによりZCSはユーザーのオンライン状態を取得することができます。
  . *OK* のボタンをクリックします。オンライン状態のセッションIDが発行され、 *オンライン状態のセッションID* として表示されます。
  
== ボイス/チャットのサービスを有効にする
ドメイン、COS、またはユーザーへ使用可能なボイス/チャットのサービスを作成したら、ボイス/チャットのサービスを有効にする必要があります。COSとユーザーアカウントについて、ZWCにボイスのタブを表示するためのボイス機能も有効にします。

== ドメインにボイス/チャットのサービスを有効にする
ドメイン>全般情報のページにて、ドメインにボイス/チャットのサービスをサービスを有効にします。

  . 管理コンソールで *設定>ドメイン* のページを開きます。
  . ボイスサービスを有効にするドメインを選択します。
  . 画面右上のギアアイコンより *編集* をクリックします。
  . *ボイスおよびチャット* の項目にて、作成したボイスサービスの表示名をドロップダウンメニューより選択します。
  . 画面右上に *保存* をクリックします。

== COSにボイス/チャットのサービスを有効にする
COSのボイス/チャットのサービスについて、ボイス/チャットのサービスを有効にしてから、ボイス機能を有効にします。

  . 管理コンソールで *設定>提供サービス* のページを開きます。
  . ボイスサービスを使用するCOSを選択します。
  . 右上のギアアイコンより *編集* をクリックします。
  . 全般情報のページにて、 *ボイスおよびチャット* にて作成されたボイスサービスの表示名をドロップダウンメニューから選択します。（画面右上の保存をクリックします）
  . 左メニューより、 *機能* をクリックします。
  . 機能のページにて、 *ボイス/チャット機能* の *ボイス機能の有効化* へチェックを追加します。このオプションが有効の場合、ZWC上でボイスのタブが表示されます。
  . 画面の右上に *保存* をクリックします。

== ユーザーアカウントにボイス/チャットのサービスを有効にする
ユーザーアカウントのボイス/チャットのサービスについて、ボイス/チャットのサービスを有効にしてから、ボイス機能を有効にします。

  . 管理コンソールにて、 *ホーム>管理>アカウント* のページを開きます。
  . ボイスサービスを有効にするアカウントを選択します。
  . 右上のギアアイコンより *編集* をクリックします。
  . 全般情報のページにて、 *ボイスおよびチャット* までスクロールします。
  . *ボイス/チャットサービス* のドロップダウンメニューから、作成したボイスサービスの表示名を選択します。
  . *チャット/ボイスのユーザー名* を追加します。これはサードパーティ製のUCサーバーにあるユーザーアカウント名となります。ユーザー名を追加しない場合、デフォルトのユーザー名が自動的に使用されます。例えば、「 user1@domain.com 」のユーザーの場合、デフォルトのボイスユーザー名は「 user1 」になります。
  . *ボイス/チャットサービス* のドロップダウンメニューから、作成したボイスサービスの表示名を選択します。
  . 左メニューより、 *機能* をクリックします。
  . 機能ページにて、ボイス/チャット機能までスクロールし、 *ボイス機能の有効化* にチェックを追加します。これによりZWC上でボイスのタブが表示されます。
  . 右上の *保存* をクリックします。
  
== ボイス/チャットのZimletを有効にする
ボイスサービスを設定する際に、サービスの有効化やUCサーバーへのリクエストを送信するために専用のZimletが使用されます。ボイスのプリファレンスZimletでユーザーインターフェースにボイスのページを追加し、ベンダー専用のClick2Call ZimletでClick to Callの機能を提供します。

  . 管理コンソールにて、 *ホーム>設定>Zimlet* のページを開きます。
  . ボイスのプリファレンスZimletを有効にします。
* 右ペインで *ボイスのプリファレンス* Zimletを選択します。
* 画面右上のギアアイコンより *配備* をクリックします。
  . ベンダー専用のClick2Call Zimletを有効にします。
* ご利用のベンダーサーバーに対する適切なZimletを選択します:
  . Ciscoをご利用の場合、 *Cisco Click2Call* のZimletを選択します。
  . Mitelをご利用の場合、*Mitel Click2Call* のZimletを選択します。
* 画面右上のギアアイコンより *配備* をクリックします。

Zimletの配備を解除する場合、Zimletを選択し、画面右上のギアアイコンより *配備解除* をクリックするか、 *ステータスの切り替え* で無効化できます。
