[#zimbra-pst-migration]
== Zimbra PST 移管ウィザード
Zimbra PST 移管ウィザードでは、Microsoft Outlook のパーソナルフォルダー (`PST`) ファイルを Zimbra Collaboration (ZCS) へ移管することが可能です。

このツールは2つのモードで運用することが可能です：

* GUI 型の移管ウィザード
* コマンドライン型の移管ツール

== 移管ウィザードのGUIについて
Zimbra PST 移管ウィザードでは、分かりやすいインターフェースでユーザー様が`PST`ファイルを Zimbra Collaborationサーバへ移管することが可能です。

このツールは4つのフェーズがあります。

ソース:: Zimbra Collaboration サーバへ移管する `PST` ファイルを特定し、選択する。
移管先:: Zimbra Collaboration サーバへのログイン情報を入力する。
オプション:: 移管するフィルダー、アイテム、などのオプションを指定する。
結果:: 移管の進歩状況、エラー、および警告を含め、移管のステータスを閲覧する。

[#source-info]
=== ソースの詳細
. *Source* をクリックします。
. *PST File* の横にある `...` をクリックし、ファイルのブラウザ画面を開きます。
. Zimbra Collaboration サーバへ移管する `PST` ファイルを選択します。
. ログの詳細レベルを選択します。ログは `%temp%/ZimbraMigration` のフォルダーへ記録し、移管の問題が発生した場合に調査するために利用します。問題が発生した場合、サポートはこれらのログファイルを依頼する場合がございます。ツールを検証する場合、ログレベルを *Verbose* に指定することを推奨しています。
+
ご注意ください：ディスクスペースを保護するため、ログファイルは自動的に7日間後に削除しますので、移管してから7日間後でのサポートが必要である場合、ログのバックアップを取得してください。移管中では、*Results* ページに *Open Log File* をクリックすることでログファイルを開くことが可能です。
+
. *Next* をクリックします。

[#destination-info]
=== 移動先の詳細
`PST` ファイルを移管するため、管理者が Zimbra Collaboration サーバ上でアカウントを作成し、移管ツールのアプリケーションと以下の情報を提供します。

. *Destination* にて、以下の詳細を記入します。
 Hostname:: Zimbra サーバのドメイン名
 Port:: 一般艇に、非セキュアの接続の場合、サーバが運用するポート番号は `80` ですが、セキュア接続のポート番号は `443` となります。
 Use Secure Connection:: ZCS へのSSLセキュアコミュニケーションのオプションを選択します。
 Username::  ZCS アカウントのメールアドレスを *\名前@ドメイン* の形式で移入します。
 Password:: ZCS アカウントのパスワードを記入します。
 . *Next* をクリックします。

[#select-options]
=== 移管オプションについて
. *Item Types* にて、インポートするアイテムを選択します。
. *Sent*, *Deleted Items* (trash), および *Junk* (Spam) のフォルダーも移管する場合、*Additional Folders* を選択します。
. *Filters*: 不要な `PST` アイテムを移管しないため、以下のフィルターオプションを活用します。
 * *Migrate On or After*: このオプションで指定した日時より前のメッセージを移管しないことがでいます。ツールは指定した日時より前のメッセージを無視します。
 * *Maximum message size*: メッセージサイズがメッセージの本文と添付ファイルを含めています。この値を空にした場合、Zimbra Collaboration サーバの最大メッセージサイズ設定を活用します。
** こちらのオプションにサイズを指定した場合、グローバル MTA 設定の最大メッセージサイズより大きく設定できません。デフォルトの最大メッセージサイズは 0 (サイズ上限はないことを示す) です。
+
ご注意：最大サイズを *0* に設定しても、Zimbra Collaboration サーバの上限を無視することができません。

  *Skip these folders, and their children (separate with a comma)*:: 移管を無視するフォルダー（サブフォルダーを含め）をコンマ区切りで記入します。
  *Skip previously migrated items*:: 以前に移管したアイテムを再度に移管しない場合、このオプションを活用します。
+
ご注意：最大メッセージサイズの値を管理コンソールの *設定* -> *グローバル設定* -> *MTA* 画面での確認、および変更することが可能です。
+
. *Save* をクリックしますと、設定情報をファイルとして保存し、移管ツールを再度に事項した場合に <<#source-info>> のページで Load ボタンで読み込むことが可能です。
. *Back* をクリックしますと、<<#source-info>> または <<#destination-info>> に詳細を変更することが可能です。
. *Migrate* をクリックしますと移管のプロセスが開始ます。

=== 移管の結果を閲覧する場合
結果ページでは、進歩状況、エラー、および警告を含め、`PST` ファイルの移管状況を確認することが可能です。

結果のログを閲覧する場合、アカウントをダブルクリックします。新しいタブにアカウントのログ情報が表示されます。

 Account:: 移管のステータスを表示します。プログレスバーで移管の進歩状況、およびステータスメッセージを示しています。*Min/Avg/Max* は該当アカウントにアイテムの移管に対する最低、平均、および最大時間（ミリ秒単位）です。Read/Write ではソースからデータの読み込み対Zimbra Collaboration サーバでのデータ書き込み時間を示します。これらのデータにて、ネットワーク/サーバのボトルネックを特定するために役立ちます。例えば、90%:10% が指定して場合、ソースがボトルネックであることを示します。
 ** Accountsにてアカウント名をダブルクリックしますと、追加のタブでフォルダー毎の移管状況、およびフォルダー毎でのボトルネック統計情報を確認できます。*X* をクリックすると開いているタブをクローズします。
 Open Log File:: `PST` ファイル移管に関連しているログファイルを開きます。ログファイルは `%temp%\ZimbraMigration\Logs\*.log` で保存してます。各移管は複数のログファイルを発行します。`*migrate.log` は全体的な移管セッションデータを含まれています。`*migrate-SUMMARY.log` は移管セッションから重要なイベントの要約を含まれています。また、移管する際に、各アカウントに対するログファイルが作成します： `*migrate [ソースアカウント名]` と `[移管先アカウント名].log`。
 Stop:: Stopをクリックしますと移管を中断します。再開する場合、前の画面へ戻り、Migrate ボタンを再度にクリックします。
 Exit:: Exitをクリックしますと移管ツールを終了します。

== 移管ウィザードのCLIについて
Zimbra PST 移管ウィザードはコマンドラインのインターフェースも提供しており、1つのコマンドで複数のオプションを運用することで、ユーザー様が`PST`ファイルを Zimbra Collaborationサーバへ移管することが可能です。

コマンドを実施するため、設定ファイル (`XML`) と `PST` ファイルが必要となります。
[#create-config-file]
=== 設定ファイルを作成する方法
. {product-name} を起動します。
. <<#source-info, ソース情報>> を指定します。
. <<#destination-info, 移管先の情報>> を指定します。
. 現在の移管に対する <<#select-options, オプション>> を選択します。
+
ご注意：こちらで指定したオプションはコマンドラインのツールで指定したオプションで上書きすることが可能です。
+
. 完了した場合、*Save* をクリックし、上記の設定を `XML` ファイルとして保存します。

=== ツールを実施する方法
構文::
`ZimbraMigrationConsole ConfigxmlFile=<XMLファイルの保存先> [arg1] [arg2] ...`

事例::
`ZimbraMigrationConsole ConfigxmlFile=../Config.xml Calendar=true Contacts=true`

事例の結果::
移管ツールは指定した `XML` ファイルと `PST` ファイルからのカレンダーと連絡先を移管します。

ご注意：ツールではXMLファイルを作成する際に <<#select-options, オプション>> を選択した際に同様なオプションを指定することが可能です。利用可能のオプションを確認する場合、ツールを `-help` のオプションで実行してください。

// [cols=2*,options="header"]
// |===
// | オプション | 詳細
// | `ConfigxmlFile=`           |   `xml` ファイルの保存先です。`xml`ファイルへの完全なるパスを記載する必要があります。
// | `DataFile=`                |   ユーザーへ移管するPSTファイルです。PSTファイルへの完全なるパスを記載する必要があります。
// | `ZimbraHost=`              |   Zimbra サーバのホスト名
// | `ZimbraPort=`              |   Zimbra サーバのポート番号
// | `ZimbraID=`                |   Zimbra のユーザーID
// | `ZimbraPwd=`               |   Zimbra アカウントのパスワード
// | `Mail=`                    |   `true` または `false`です。`true` の場合、すべてのメールを移管します。指定していない場合、<<#create-config-file>> で指定したオプションを活用します。
// | `Calendar=`                |   `true` または `false`です。 `true` の場合、カレンダーと予定を移管します。
// | `Contacts=`                |   `true` または `false`です。 `true` の場合、連絡先を移管します。
// | `Tasks=`                   |   `true` または `false`です。 `true` の場合、タスクを移管します。
// | `Sent=`                    |   `true` または `false`です。 `true` の場合、`Sent`（送信済み）のメールを移管します。
// | `DeletedItems=`            |   `true` または `false`です。 `true` の場合、`DeletedItems`(削除済み) のメールを移管します。
// | `Junk=`                    |   `true` または `false`です。 `true` の場合、`Junk` (迷惑メール) のメールを移管します。
// | `LogLevel=`                |   このオプションはログレベルをDebug, Info, または Trace に指定します。
// | `IsSkipFolders=`           |   `true` または `false`です。 このオプションは移管するフォルダーの無視フィルターを有効化します。
// | `FoldersToSkip=`           |   無視するフォルダー名をコンマ区切りでリストします。
// | `IsOnOrAfter=`             |   `true` または `false`です。 このオプションは移管するの日時フィルターを有効化します。
// | `MigrateOnOrAfter=`        |   YYYY-MM-DD の日時です。指定した日時より前のアイテムは移管しない。
// | `IsMaxMessageSize=`        |   `true` または `false`です。 このオプションはmaxmessagessize（メッセージの最大サイズ）のフィルターを有効化します。
// | `MaxMessageSize=`          |   最大のメッセージサイズ（数字）です。この値より大きいメッセージは移管しない。
// | `IsSkipPrevMigratedItems=` |   `true` または `false`です。以前に移管したアイテムを再度に移管するか指定します。
// | `Silent=`                  |   `true` または `false`です。 `true` の場合、コマンドライン上に`Press any key` のメッセージを返答しない。
// |===

要注意：コマンドラインのツールで指定したオプションは設定ファイルに指定したオプションを上書きします。

コマンドが正常に完了しましたら、コンソール上に移管のステータスが表示されます。
