Zimbra Chat
------------

[[about-this-document]]
=== 本書について

本書は、システム管理者を対象に記載しています。本書の目的は、プロダクトアーキテクチャについての深い見解によりトラブルシューティングを簡潔にすること、同時に、安定したカスタマイズに必要な知識を提供することです。

=== 概要

Zimbra Chatは、バージョン8.7.6以降のZimbraにベータ版ソフトウェアとして含まれています。そしてバージョン8.8.0で安定版となりました。Zimbra Chatは、Zimbraアカウント間での文字によるチャット機能であるため、シンプルかつダイレクトです。ZimletとZimbraの拡張機能で構成されています。

Zimbraの拡張機能はXMPPクライアントをあてているため、ユーザーはZimbraのウェブクライアントでZimletを使用する代わりに標準のXMPPクライアントを使ってチャットすることもできます。この２つの手段を同時に使用することもできます。


[[general-architecture]]
==== 一般的なアーキテクチャ

Zimbra Chat はZimbra用に設計されています。そしてXMPPサーバーを実装したZimbraサーバー拡張機能として稼動しながら、クライアント間での共有イベントを全て処理します。Zimbra Chatサーバー拡張機能ではChat Zimletとの連携に、XMPPとカスタムプロトコルを使用しています。

このサーバー拡張機能は、シングルユーザーの複数セッションを処理できます。セッション数に制限はありません。セッションごとに配信キューがあります。つまり、各セッションが全てのイベントを保持しており、それらをそのユーザーの別のセッションとして把握しています。

種類 (XMPPあるいはChat Zimlet) によってセッションが制限されることはありません。ユーザーはセッション間の衝突を気にすることなく、ZimbraウェブクライアントとXMPPクライアントの両方を同時に使用することができます。

[[components]]
==== コンポーネント

Zimbra Chatには、２つのパートがあります。

* Chat Zimlet
* Chat 拡張機能

Zimbra Chat拡張機能はChat Zimletがなくても正常に機能します。Chat ZimletはChat拡張機能といっしょに動作することを前提とし、設計・作成されています。

[[zimlet]]
===== Zimlet

Chat ZimletはChatを行なうクライアントコンポーネントです。他のZimlet同様、Zimbraウェブクライアント上で稼動し、管理されます。加えて、Zimbraウェブクライアントに完全に統合されており、同じグラフィックライブラリを使用しています。ZimletはChat拡張機能がなければ動作しません。Zimletと拡張機能はイベントの送受信に特殊なプロトコルを使用しているためです。Zimbraウェブクライアントのサポート対象であるバージョンと全てのブラウザで、Chat Zimletもサポートされます。

機能

* Zimbraウェブクライアントと統合。
* 仲間の一覧を管理します。ユーザーは、仲間を追加・編集・削除することができます。
* チャットルームごとに別のパネルが開きます。
* ユーザー個人の状態を管理します。
* 仲間の一覧にいるユーザーとの平文送受信を行ないます。
* 仲間の一覧にいるユーザーにオンライン状態を送信します。
* 仲間の一覧にいるユーザーのオンライン状態を表示します。

* 会話での絵文字 (顔文字) に対応します。絵文字は無料で http://emojione.com/ から提供されています。
* チャットの全内容をメールとして送信します。
* チャット履歴内の会話を検索します (拡張機能のオプションが有効である場合。<<sect:confkeys>>を参照してください) 。
* メッセージ受信時、通知をデスクトップに表示します。

[[extension]]
===== 拡張機能

Zimbra Chat拡張機能は、Zimbra Chatの要です。接続中のクライアント間でのイベント管理を行なう、完全なチャットサーバーです。

Zimbraのmailboxdサービスとの統合にZALを使用しています。

この拡張機能は、下記2種類の接続に対応可能です。

* Chat Zimletから受け取るSOAP接続。ZimbraのSOAPインフラを使用します。
* 互換性のあるクライアントからのXMPP接続。

機能

* 複数セッションからのイベントを処理します。
* Chat Zimlet クライアントからのSOAP接続を処理します。
* 互換性のあるクライアントからパブリックポート経由で受け取るXMPPを処理します  (平文とSSL) 接続 (<<sect:confkeys>>を参照してください)  。
* 各会話のチャット履歴をそのユーザーのメールボックス内、専用チャットフォルダに格納します (オプションが有効な場合のみ。<<sect:confkeys>>を参照してください)  。
* ユーザー間の関係をZimbraデータベースに格納します。

[[installation]]
=== インストール
バージョン8.8.0以降、Zimbra Chatは、全Zimbraパッケージと共にZimbraパッケージとして搭載されることになりました。

専用のインストールプロセスは必要ありません。

WARNING: システムのインストール中またはアップグレード中にZimbra Chatパッケージをインストールしなかった場合、パッケージインストールに関する一般ドキュメントを参照しながらインストールを行なってください。

[[upgrade]]
=== アップグレード

Zimbra Chatは他の全てのZimbraプラットホームと一緒にアップグレードされます。

専用のアップグレードプロセスは必要ありません。

[[troubleshooting]]
=== トラブルシューティング

本項には、管理者が問題を発見し解決できるようなヒントを記載します。解決策が見つからない場合、管理者は問題を報告するプロセスに従って、ガイドを受けることが可能です。

[[looking-for-errors]]
==== エラーの探索

このプロセスは、原因の特定、解決策の確定、あるいは報告を正確に行なうには、欠かせないプロセスです。

[[sect:zim-err]]
==== Chat Zimletのエラー

Chat Zimletのソースコード内のエラーを特定するには、まず、Zimbraウェブクライアントをデベロッパーモードにしてください。これにはZimbra環境のブラウザのURLに `?dev=1` を追加します。URLに `dev=1` を追加することで、Zimletを含むウェブクライアント全体と全てのソース (省略なし) がZimbraにロードされます。 +
Zimbraウェブクライアントをロードしている間にデベロッパーツールのブラウザを開きます。

デベロッパーツールのブラウザにあるコンソールに、Chat Zimletのログが表示されます。エラーが発生すると、それがコンソールに出力されます。

エラーがコンソールに出力されていないにもかかわらず動きが不正な場合はデベロッパーツール内にあるオプション `例外ブレイクポイント` を有効にします。これによりエラー発生時、そのエラーが起こったポイントとなる行で実行が停止します。

エラー発生時は、該当ファイル、該当行、そしてそのエラーに関するあらゆる詳細を送付してください。その際、適切な窓口を通してエスカレーションをするようにしてください。

エラーが検知されない場合、<<sect:ext-err>>項を参照してください。

[[sect:ext-err]]
==== Chat拡張機能のエラー

Chat拡張機能がスローした例外は `mailbox.log` に出力されます。例外有無のチェックは、本書内の該当の章を参照してください。
FAQに例外に対する解決策が記載されていない場合、その例外情報全体をそえて、適切な窓口を通してエスカレーションしてください。

FAQに例外に対する解決策が記載されていない場合、その例外情報全体をそえて、適切な窓口を通してエスカレーションしてください。

[[sect:tools]]
=== ツール

[[google-chrome-developer-tools]]
==== Google Chromeのデベロッパーツール

Zimbraウェブクライアントで予期せぬ動きがあった場合、Google Chromeのデベロッパーツールを使用して、その原因を探ります。

Google Chromeのデベロッパーツールを開くには

* メインメニューを開きます。
* その他のツールというメニューオプションを探します。
* デベロッパーツールを選択します。

すると新たに、タブがたくさん付いたパネルが表示されます。タブには次のものがあります。

* Console : サーバーコンソールのようなもの。ログ情報はこのタブに表示されます。JS Runtimeでの操作が可能です。
* Network : ネットワーク処理が表示されます。メールボックスへの要求、そしてメールボックスからの応答を見たい場合に使用できます。

[[firefox-developer-tools]]
==== Firefoxのデベロッパーツール

Firefoxのデベロッパーツールを開くには、メインメニューを開いた後、`開発ツール` ボタンをクリックします。

すると新たに、タブがたくさん付いたパネルが表示されます。タブには次のものがあります。

* Console : サーバーコンソールのようなもの。ログ情報はこのタブに表示されます。JS Runtimeでの操作が可能です。
* Network : ネットワーク処理が表示されます。メールボックスへの要求、そしてメールボックスからの応答を見たい場合に使用できます。


[[sect:gatheringinfo]]
=== システム情報の収集

トラブルシューティングプロセスの一環として、システム情報の収集は欠かせません。この項には、管理者が (「問題のエスカレーション方法」の項に記載されているように) 問題を正確に報告するに際し、必要かつ有用なシステム情報を収集できるようなヒントを記載します。

[[sect:gatheringinfo-zversion]]
==== Zimbraのバージョン

Zimbraのバージョンを確認するには下記コマンドを入力します。

------------
# zimbraユーザーとして
zmcontrol -v

------------

[[sect:gatheringinfo-extension]]
==== 拡張機能とZimletのバージョン

拡張機能とZimletのバージョンを確認するには下記コマンドを入力します。

---------------------------------------------------------------------------
# zimbraユーザーとして
java -cp /opt/zimbra/lib/ext/openchat/openchat.jar com.zextras.lib.OpenChat

---------------------------------------------------------------------------

[[sect:gatheringinfo-listzimlets]]
==== 配備したZimletの一覧

配備したZimletの一覧を確認するには下記コマンドを入力します。

-----------------------
# zimbraユーザーとして
zmzimletctl listZimlets

-----------------------

[[sect:gatheringinfo-userzimlets]]
==== ユーザーが使用できるZimletの一覧

そのユーザーが使用できるZimletの一覧を確認するには下記コマンドを入力します。

--------------------------------------------------------------
# zimbraユーザーとして
zmprov getAccount user@domain.tld zimbraZimletAvailableZimlets

--------------------------------------------------------------

[[sect:gatheringinfo-userzimlets-pref]]
==== Zimletのユーザープリファレンスの一覧

ユーザーが利用できるZimletのプリファレンスの一覧を確認するには下記コマンドを入力します。

------------------------------------------------------------
# zimbraユーザーとして
zmprov getAccount user@domain.tld zimbraZimletUserProperties

------------------------------------------------------------

[[sect:faq]]
=== F.A.Q.

[[Chat-zimlet-issues]]
==== Chat Zimletに関する問題

*ユーザーがログインしてもChat Zimletが機能しません。JavaScriptのエラーがいくつか出ています。どうすればよいでしょうか。*

この場合、原因はキャッシュ関連の問題であることが多いです。下記コマンドで全キャッシュをリフレッシュしてください。

-------------------------------------------------
# zimbraユーザーとして
zmprov flushCache -a zimlet com_zextras_chat_open

-------------------------------------------------

まだ問題が続くようであれば、エスカレーションしてください。

*ログインしてもChat Zimletが開始しません。サーバーが利用できないというポップアップが表示されます。どうすればよいでしょうか。*

TIP: 委任されたアクセス機能を使用してそのユーザーにログインした場合、Chat Zimletは開始しません (例：管理コンソールからのメールを表示ボタン) 。そのユーザーのプラバシーを保護するためです。

Chat拡張機能が `mailbox.log` に正しくロードされているかどうかを確認してください ( `mailbox.log` の見方は本書の該当項目を参照してください) 。

Zimbra拡張機能のロードはmailboxd のスタートアップ時、下記の行で実行されています。

-----------------------------------------------------------------------
xxxx-xx-xx xx:xx:xx,xxx INFO  [main] [] mailbox - OpenChat starting ...
xxxx-xx-xx xx:xx:xx,xxx INFO  [main] [] extensions - OpenChat started

-----------------------------------------------------------------------

まだ問題が続くようであれば、レポートに例外を記載の上、報告してください。

*他のZimletでサイドバー表示を利用している場合、チャットの仲間が一覧で見られません。どうすればよいでしょうか。*

Chat Zimletが使用しているコンテナは、他のZimletでも使えるものです。このコンテナの使用状況を検出して衝突を回避するようにしています。

このため、Chat Zimletは内部 `ブラックリスト` を使用します。互換性のない他のZimletを検知したときにドックモードへ切り替えてサイドバーモードを無効にするためです。

ただ、内部ブラックリストに掲載されていないZimletがサイドバー用コンテナを使用していると、この検出は失敗に終わる恐れがあります。

まだ問題が続くようであれば、衝突Zimletの名称を記載し、報告してください。

他のZimletがサイドバーを使用していたためにサイドバーモードから抜け出せなくなっている場合、下記コマンドでZimletのユーザー設定をリセットすれば、ドックモードに変えられます。

----------------------------------------------------------------------------------
# zimbraユーザーとして
# 対象の zimletのユーザープリファレンスをリセット。
zmprov modifyAccount user@example.com \
    -zimbraZimletUserProperties "com_zextras_chat_open:zxchat_pref_dockmode:FALSE"
zmprov modifyAccount user@example.com \
    -zimbraZimletUserProperties "com_zextras_chat_open:zxchat_pref_dockmode:TRUE"
# zimletのユーザープリファレンスをドックモードに変更。
zmprov modifyAccount user@example.com \
    +zimbraZimletUserProperties "com_zextras_chat_open:zxchat_pref_dockmode:TRUE"

----------------------------------------------------------------------------------

上記が終わったら、この修正を反映するため、Zimbraウェブクライアントをリロードします。

まだ問題が続くようであれば、報告してください。

[[Chat-extension-issues]]
==== Chat拡張機能に関する問題

*2つのサーバー間でサーバーtoサーバーのメッセージ配信ができません。どうすればよいでしょうか。*

2つのメールボックス間の接続に問題があるからかもしれません。両サーバーのポート `5269` が開いているかどうか、そして相互にサーバー接続できるかどうかを検証してください。

サーバーのポートが開いているかどうかは、Telnetクライアントを使用してポート `5269` へ接続し、確認します。

全て正常に機能しているようであれば、両サーバーの `mailbox.log` を開き、イベントを送信してみてください (例：テキストメッセージ1件) 。例外が表示された場合、そのエラーのヒントとなるものがないかどうかを確認してください。特に意味のあるような例外ではなかった場合、その例外を報告書に記載の上、問題を報告してください。

[[sect:how-to-escalate-an-issue]]
==== 問題のエスカレーション方法

問題を発見しても修正できなかった際、報告には下記の情報が必要です。

* 問題の詳細説明：期待していることと実際に起きていること。
* 問題を再現するのに必要な手順の詳細説明。
* インストール内容と環境についての詳細説明 (本書の「システム情報の収集」項を参照してください) 。
** サーバー情報：CPU、RAM、サーバー数およびサーバーごとの下記情報
*** Zimbraのバージョン
*** Chatのバージョン
*** インストール済Zimletの一覧
** クライアント情報
*** ブラウザ名とバージョン
*** サーバーとクライアント間で使用中の接続
*** クライアントのスキン (テーマ)
*** クライアントの言語
*** 対象のユーザーが利用できるZimletの一覧
* 問題に関するログ全て
** `mailbox.log`
+
ユーザーのプライバシーを保護するため、個人情報は削除してもかまいません。

[[advanced-topics]]
=== 高度なトピック

[[sect:sizing]]
==== サイジング

Zimbra Chatのストレス試験は実施中です。

2万ユーザーが使用しているZimbra環境において、負荷が約7%上昇したことが確認されています。

Zimbra Chat拡張機能の履歴がいちばん負荷の大きい機能です。メッセージ送信ではmimeのメッセージを作成するか更新するかのどちらかです。つまり、ほんの少しのキロバイト数が読まれるか書かれるかして、データベースのクエリがいくつか実行されるだけです。

TIP: 大規模に配備する場合、履歴機能の無効化を推奨します。この設定を編集するには <<sect:confkeys>>を参照してください。

[[sect:confkeys]]
==== 設定項目

Chat拡張機能は、ZimbraのCLIから簡単に設定できます。設定は全てLDAPに格納されます。 +

アカウントの設定を修正するには、下記コマンドを実行します。

---------------------------------------------------------------
# zimbraユーザーとして
zmprov modifyAccount account@example.tld {propertyName} {value}
---------------------------------------------------------------

zimbraChatServiceEnabled::
  `[boolean]`, 初期値: `true`

  Chatサービスを有効化。

  以下に適用可能
  * グローバル
  * サーバー
zimbraChatHistoryEnabled::
  `[boolean]`, 初期値: `true`, 適用にはmailboxの再開が必要。

  チャットフォルダ内のチャット履歴の書き込みを有効化。

  以下に適用可能
  * 提供サービス
  * アカウント
zimbraChatConversationAuditEnabled::
  `[boolean]`, 初期値: `false`

  チャットの会話用の専用ログを有効化。

  以下に適用可能
  * グローバル
  * ドメイン
zimbraChatXmppSslPortEnabled::
  `[boolean]`, 初期値: `false`, 適用にはmailboxの再開が必要。

  XMPPレガシーSSLポートを有効化。

  以下に適用可能
  * グローバル
  * サーバー
zimbraChatAllowUnencryptedPassword::
  `[boolean]`, 初期値: `false`

  XMPP経由の暗号なしパスワードログインを許可。

  以下に適用可能
  * グローバル
  * サーバー
zimbraChatXmppPort::
  `[port]`, 初期値: `5222`, 適用にはmailboxの再開が必要。

  XMPPの標準ポート。通常StartTLSと共に使用。

  以下に適用可能
  * グローバル
  * サーバー
zimbraChatXmppSslPort::
  `[port]`, 初期値: `5223`, r適用にはmailboxの再開が必要。

  XMPPレガシーSSLポート。

  以下に適用可能
  * グローバル
  * サーバー
zimbraChatAllowDlMemberAddAsFriend::
  `[boolean]`, 任意。

  配信リストの全メンバーを仲間として互いに登録。

  以下に適用可能
  *  配信リスト

[[sect:logs]]
==== ログ

[[sect:mailboxlog]]
===== mailbox.log

Mailboxログは、標準のLog4jのログです。以下、`mailbox.log` のサンプル行です。

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
xxxx-xx-xx xx:xx:xx,xxx INFO  [qtp1912962767-310:https://123.123.123.123:8443/service/soap/ModifyPropertiesRequest] [name=user@example.com;mid=6;ip=172.17.0.2;ua=ZimbraWebClient - GC58 (Linux)/8.6.0_GA_1153;] soap - ModifyPropertiesRequest elapsed=4
xxxx-xx-xx xx:xx:xx,xxx INFO  [qtp1912962767-310:https://123.123.123.123:8443/service/soap/ZxChatRequest] [] extensions - user@example.com changed status to AVAILABLE
xxxx-xx-xx xx:xx:xx,xxx INFO  [qtp1912962767-310:https://123.123.123.123:8443/service/soap/ZxChatRequest] [] soap - ZxChatRequest elapsed=24

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

各行は次の要素から構成されています。

xxxx-xx-xx xx:xx:xx,xxx::
  対象行のタイムスタンプ
INFO::
  対象行の種類
qtp…ModifyPropertiesRequest::
  ログの行へ書き込み要求したスレッドについての情報。通常はそのログの行をトリガーしたハンドラ。
name=…::
  ユーザーのセッションについての情報
soap -::
  ログの行のソース
ModifyPropertiesRequest elapsed=4::
  ログの行の内容

[[sect:zmmailboxdout]]
===== zmmailboxd.out


Mailboxログは、標準のLog4jのログです。下記は `zmmailboxd.out` のサンプル行です。

------------------------------------------------------------------------------------------------------------------
xxxx-xx-xx xx:xx:xx.xxx:INFO:oejs.SetUIDListener:main: Opened ServerConnector@397fbdb{HTTP/1.1}{0.0.0.0:8080}
xxxx-xx-xx xx:xx:xx.xxx:INFO:oejs.SetUIDListener:main: Opened ServerConnector@36ebc363{SSL-http/1.1}{0.0.0.0:8443}
xxxx-xx-xx xx:xx:xx.xxx:INFO:oejs.SetUIDListener:main: Opened ServerConnector@54d9d12d{SSL-http/1.1}{0.0.0.0:7071}

------------------------------------------------------------------------------------------------------------------

